### ISSUE TITLE
Brazier is working even if I don't light it and does not consume items 

### ISSUE THREAD

**Issue by OceanHobo** [MoriyaShiine/bewitchment#100]
So the title explains most of it. I almost didn't want to report it because I like how OP it is but I figured you guys would want to know. 

I'm using Bewitchment 1.16.5-8

I have the three items required for the haste buff in a brazier hung from the ceiling above my bed. I decided to save the buff for later since I didn't plan on mining the next day but noticed later I had the haste buff. I went back and checked and all the items are still there. Now every night I get a free haste buff and never light the brazier.

**Comment by Aelpecyem** [comment]
I am not exactly able to reproduce this, did you go through any other special measures?
