### ISSUE TITLE
Config is getting ignored

### ISSUE THREAD

**Issue by SlendyMan0** [MoriyaShiine/bewitchment#105]
Any attempt to change bewitchment config is ignored. I'm not certain, as I am not a modder and I'm not familiar with the API, but I suspect that it may be because all of variables in config are final, however I'm not sure and just pointing in a direction there I think the problem is. 

But I think that even if that would be fixed, not all problems would be gone. Mob entities are registered before the check for 0 weight, which means that only thing skipped are additional settings, such as biomes and spawn restrictors.

**Comment by TelepathicGrunt** [comment]
In AOF3 discord, a dev that was modifying Bewitchment to get the configs to work said this ```in BWConfig I just took Final out of all the configs, public final int ghostWeight = 6; to public int ghostWeight = 60; which makes their mod actually use the config value instead of the Final value.```
