### ISSUE TITLE
Really weird crash issue

### ISSUE THREAD

**Issue by stormdirus2** [MoriyaShiine/bewitchment#11]
I have a decently-sized modpack and I got a crash when I died. Might have something to do with me building the latest version of fermion to prevent another crash?
Im also using the requiem mod, and this crash specifically happens upon death.
[crash.txt](https://github.com/MoriyaShiine/bewitchment/files/5912407/crash.txt)

**Comment by MoriyaShiine** [comment]
Uhhh concern

Can you pinpoint exactly which combination of mods causes this

**Comment by stormdirus2** [comment]
I am confused beyond anything I can even describe.
The conflict is between FirstPersonMod, FabricAPI, and bewitchment, and I literally have no clue as to why. If you only use these the server just literally commits self death. If you use it with fermion you get that crash up there. I-uh what? WHAT??

It just makes no sense, its just a clientsided mod to render the player's character in 3d. I wonder if the same issue arises if I just die in 3rd person like what.

**Comment by Aelpecyem** [comment]
I don't see how bewitchment fabric is related to this? Can't seem to find it on the mod list

**Comment by stormdirus2** [comment]
WAit what?
I definitely had in it the mod folder, and I isolated it and firstperson as the direct cause. Without one of these mods it doesnt crash, and the crash up there happened with both. Why it didn't log, I have no clue. Specifically with only firstperson and bewitchment it doesnt even give a crash log, it just stops ths server suddenly.

It definitely happens, if you dont believe me build firstperson and use it with bewitchment and then /kill yourself.

**Comment by MoriyaShiine** [comment]
Doesn't seem to happen any more, tested with https://www.curseforge.com/minecraft/mc-mods/first-person-model/files/3239400
