### ISSUE TITLE
Phantom pledge prevents pledging to actual demons

### ISSUE THREAD

**Issue by Divineblaze** [MoriyaShiine/bewitchment#119]
After switching to version 10, any existing pledges have been replaced by phantom pledges that count as being pledged but aren't to an actual demon in the world. This means that the characters can't actually pledge to demons like Leonard or Baphomet. 

I haven't found a way to break the phantom pledge either, since there's no actual entity in the world anymore. Killing the old demon doesn't work. Updating to version 11 didn't seem to fix it either. When starting a new world, the pledging system works as expected.

<img width="450" alt="Screen Shot 2021-05-03 at 10 43 37 AM" src="https://user-images.githubusercontent.com/24281587/116906000-f1192f80-abfc-11eb-8dc1-3a6cf1ae946a.png">

**Comment by Aelpecyem** [comment]
this is caused by the tag not getting added to old worlds, pledges should have a default value for when none is found

**Comment by Divineblaze** [comment]
Is there anyway to fix it on my end?
