### ISSUE TITLE
License conflict between Bewitchment 1.12 and 1.16

### ISSUE THREAD

**Issue by Rosethorns** [MoriyaShiine/bewitchment#121]
You have specifically requested that no port be made of bewitchment 1.16 but it also implies bewitchment /at all/ 
"I will not port my mods to Forge, nor do I want someone else to port my mods either. Please don't ask."

Bewitchment 1.12 is MIT and the GPL license on this branch does not override the 1.12 version. There is also conflict that bewitchment is "your mod"

I just want to make sure that you are aware of this and what ever issue it is you have with Forge cannot stop someone from porting 1.12 bewitchment to Forge.

**Comment by MoriyaShiine** [comment]
Bewitchment 1.12 and Bewitchment 1.16 are, for all intents and purposes, different mods altogether. I own this version and the owner of the 1.12 version also doesn't want it on forge, however 1.12 is forge only, not to mention that version is discontinued. While nothing is stopping someone from porting the 1.12 version to newer versions, it would be a real dick move to go against our wishes.

**Comment by Rosethorns** [comment]
Do you have evidence that he doesn't want it on Forge? Or are we meant to take your word for it?

**Comment by MoriyaShiine** [comment]
You can ask him on the discord or wait for him to wake up and he can respond here.
