### ISSUE TITLE
Juniper saplings can place trees next to themselves

### ISSUE THREAD

**Issue by saltyseadoggo** [MoriyaShiine/bewitchment#122]
Version: 10
Juniper saplings can grow trees next to themselves instead of over themselves, leaving the sapling behind where it could theoretically grow a new tree at no additional cost. We have seen this multiple times growing large numbers of them in our survival mode.
Can be reproduced by simply making large numbers of juniper trees grow naturally (unknown if this happens with bone meal) until it occurs. Here is two instances in our survival world. Note that the grass under the saplings turned into dirt as if the tree was going to grow correctly; the grass under the left tree probably decayed with random ticks, as this screenshot wasn't taken immediately.
![2021-05-04_19 14 47](https://user-images.githubusercontent.com/69029346/117090611-a6d3a380-ad0d-11eb-838e-4acaea2e1d1c.png)

**Comment by MoriyaShiine** [comment]
From my experience, this is just a visual bug from Mojang's tree implementation. Right click or interacting with the sapling will destroy it since it's client side only, and it can't grow. If I'm wrong, please comment and I can open again.

**Comment by saltyseadoggo** [comment]
You were correct: the saplings disappeared on right click. However, the trees still grow off-center from where the sapling is, which doesn't match vanilla sapling behaviour, and they leave the bald dirt patch where the sapling was.

**Comment by MoriyaShiine** [comment]
I believe it has to do with the height of the tree and it being buggy because of being so short. Should I leave it as is, or make the tree taller?

**Comment by saltyseadoggo** [comment]
Their small stature makes them stand out a little bit more from acacia. However, them growing off center could conceivably break automated tree farms by growing the tree out of place or even replacing components with logs, so, if it's one or the other, I'd say make them taller and see if that makes them behave 100% of the time.
I know there's a Fabric development Discord server linked in on the official website that may be able to help you if you want the best of both worlds; see [here](https://discord.gg/v6v4pMv). You could also potentially ask the Biomes You'll Go devs on their Discord, as they've done a lot with trees in their mod. Their invite is [here](https://discord.com/invite/zQA4eez2eS). I'm not sure if they can help, but they might.

**Comment by MoriyaShiine** [comment]
I'll ask, thanks!
