### ISSUE TITLE
Demon Trading crashes

### ISSUE THREAD

**Issue by Padillak** [MoriyaShiine/bewitchment#123]
[Demon crash.txt](https://github.com/MoriyaShiine/bewitchment/files/6431528/Demon.crash.txt)

I am using bewitchment version 1.16.5-11 
whenever I try to trade with a the demon on my server the server crashes, unknown if this also happens on my solo worlds as I couldn't get the altar powerful enough even on creative.

**Comment by LordDecay26** [comment]
this only happens on multiplayer servers, btw. but yes we got the same crash. 
[crash-2021-05-06_16.32.14-server.txt](https://github.com/MoriyaShiine/bewitchment/files/6438108/crash-2021-05-06_16.32.14-server.txt)

**Comment by Eive1Me** [comment]
same
[crash-2021-05-08_14.36.04-server.txt](https://github.com/MoriyaShiine/bewitchment/files/6445788/crash-2021-05-08_14.36.04-server.txt)
