### ISSUE TITLE
Server Crash On Altar Placement

### ISSUE THREAD

**Issue by Ninonsand** [MoriyaShiine/bewitchment#124]
After placing the altar on a server, we get a complete server crash after a few minutes when the altar is at about 50% power.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/5/21 11:37 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.8)
	at net.minecraft.server.OperatorList.toString(OperatorList:51)
	at net.minecraft.server.OperatorList.toString(OperatorList:9)
	at net.minecraft.server.ServerConfigList.contains(ServerConfigList:82)
	at net.minecraft.server.PlayerManager.isOperator(PlayerManager:661)
	at net.minecraft.server.MinecraftServer.getPermissionLevel(MinecraftServer:1483)
	at net.minecraft.server.network.ServerPlayerEntity.getPermissionLevel(ServerPlayerEntity:1333)
	at net.minecraft.entity.Entity.getCommandSource(Entity:2849)
	at net.minecraft.advancement.AdvancementRewards.method_17978(AdvancementRewards:77)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.advancement.AdvancementRewards.apply(AdvancementRewards:77)
	at net.minecraft.advancement.PlayerAdvancementTracker.grantCriterion(PlayerAdvancementTracker:207)
	at net.minecraft.advancement.criterion.Criterion$ConditionsContainer.grant(Criterion:35)
	at net.minecraft.advancement.criterion.AbstractCriterion.test(AbstractCriterion:72)
	at net.minecraft.advancement.criterion.ItemDurabilityChangedCriterion.trigger(ItemDurabilityChangedCriterion:25)
	at net.minecraft.item.ItemStack.damage(ItemStack:310)
	at net.minecraft.item.ItemStack.damage(ItemStack:330)
	at com.terraformersmc.terraform.wood.block.StrippableLogBlock.onUse(StrippableLogBlock.java:55)
	at moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity.scan(WitchAltarBlockEntity.java:210)
	at moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity.tick(WitchAltarBlockEntity.java:117)
	at net.minecraft.world.World.tickBlockEntities(World:510)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:429)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:312)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
Details:
	Name: bewitchment:witch_altar // moriyashiine.bewitchment.common.block.entity.WitchAltarBlockEntity
	Block: Block{bewitchment:purple_stone_witch_altar}[facing=west,level=0,waterlogged=false]
	Block location: World: (119,66,40), Chunk: (at 7,4,8 in 7,2; contains blocks 112,0,32 to 127,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{bewitchment:purple_stone_witch_altar}[facing=west,level=0,waterlogged=false]
	Block location: World: (119,66,40), Chunk: (at 7,4,8 in 7,2; contains blocks 112,0,32 to 127,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block Entity NBT: {x:119,MaxPower:92,y:66,Items:[{Slot:1b,id:"minecraft:skeleton_skull",Count:1b}],z:40,id:"bewitchment:witch_altar",Power:92,Gain:2}
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:517)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)
-- Affected level --
Details:
	All players: 8 total; [class_3222['ScarlettBlade'/86, l='ServerLevel[world]', x=88.36, y=6.00, z=-55.23], class_3222['IlIBLIZZARDZIlI'/250, l='ServerLevel[world]', x=132.83, y=63.09, z=-10.53], class_3222['Grizguy34'/253, l='ServerLevel[world]', x=110.70, y=10.00, z=-58.67], class_3222['ChilloutJosh'/254, l='ServerLevel[world]', x=110.70, y=11.20, z=-57.92], class_3222['Inky_Scroll'/352, l='ServerLevel[world]', x=117.67, y=51.00, z=-11.76], class_3222['Roult'/213, l='ServerLevel[world]', x=91.30, y=10.00, z=-53.42], class_3222['Wyatts_'/509, l='ServerLevel[world]', x=91.16, y=11.00, z=-58.04], class_3222['Sektiss'/941, l='ServerLevel[world]', x=93.18, y=11.00, z=-57.09]]
	Chunk stats: ServerChunkCache: 3083
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,208), Chunk: (at 0,4,0 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 304231 game time, 462371 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 119407 (now: false), thunder time: 155802 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.15.0-112-generic
	Java Version: 1.8.0_282, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1481803208 bytes (1413 MB) / 3668967424 bytes (3499 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms128M -Xmx8192M
	Suspected Mods: Terraform Wood API (v1) (terraform-wood-api-v1), Bewitchment (bewitchment)
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antiqueatlas: Antique Atlas 5.4.4-fabric
		artifacts: Artifacts 3.2.0+fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axesareweapons: Axes Are Weapons 1.1
		bannerpp: Banner++ 2.0.2+mc.1.16.3
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		beebetter: Bee Better 1.8.0-1.16.4
		beholdersvariations: Beholder's Variations 0.3.2
		better_withered_mobs: Better Withered Mobs 1.5.1
		betterend: Better End 0.9.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		bewitchment: Bewitchment 1.16.5-11
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blast: BLAST 1.5.2
		blue_endless_jankson: jankson 1.2.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.0.2-1.16.5
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.1.7
		cardinal-components: Cardinal Components API 2.8.1
		cardinal-components-base: Cardinal Components API (base) 2.8.1
		cardinal-components-block: Cardinal Components API (blocks) 2.8.1
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.1
		cardinal-components-entity: Cardinal Components API (entities) 2.8.1
		cardinal-components-item: Cardinal Components API (items) 2.8.1
		cardinal-components-level: Cardinal Components API (world saves) 2.8.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.1
		cardinal-components-util: Cardinal Components API (utilities) 2.8.1
		cardinal-components-world: Cardinal Components API (worlds) 2.8.1
		castle_dungeons: Castle Dungeons 2.2
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.3.2
		cinderscapes: Cinderscapes 1.3.3
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.2-1.16.5
		couplings: Couplings 1.3.3
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		croptopia: Croptopia 1.3.5
		croptosis: Croptosis 1.1.0
		crowdin-translate: CrowdinTranslate 1.2
		culinaire: Culinaire 2.0
		dawn: Dawn API 1.8
		dragonloot: DragonLoot 1.0.5
		ducts: Ducts 1.0.4
		earlygame: EarlyGame 1.16.x-1.0.2
		eldritch_mobs: Eldritch Mobs 1.6.9
		expandedstorage: ExpandedStorage 5.6.33
		extraalchemy: Extra Alchemy 1.4.4
		extragenerators: Extra Generators 1.0.1-BETA
		fabric: Fabric API 0.34.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fabricshieldlib: Fabric Shield Lib 1.3.5-1.16.5
		fallingtree: FallingTree 2.11.3
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.4
		fasttransferlib: Fast Transfer Lib 0.2.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		geckolib3: Geckolib 3.0.33
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		gildednetherite: Gilded Netherite 1.0.0
		glassential: Glassential 1.16.4-1.1.5
		glimmeringpotions: Glimmering Potions 1.1.3-1.16.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		gravestones: Gravestones v1.9
		greater_eye: Greater Eye of Ender 1.1.5
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		harvest_scythes: Harvest Scythes 2.0.0
		hplus: Better Hoppers (Hopper+) 2.3.0
		impersonate: Impersonate 2.2.0
		improved-stations: Improved Stations 2.0.3
		intotheomega: Into the Omega 1.1.2-beta-1.16.2
		inventorysorter: Inventory Sorter 1.7.9-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kyrptconfig: Kytpt Config 1.1.6-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.8.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.1.0+1.16.3
		libstructure: Libstructure 1.3
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		minecraft: Minecraft 1.16.5
		miskatonicmysteries: Miskatonic Mysteries 0.0.3
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		musica: Musica 1.2.0
		notenoughcrashes: Not Enough Crashes 3.2.0
		nourish: Nourish 1.2.1
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.0.0+21w14a
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.10-1.16.5
		portaltags: Portal Tags 2.1.0
		quickshulker: Quick Shulker 1.1.14-1.16
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.2+build.132
		reroll: Reroll 1.2.1-1.16.5
		seasons: Fabric Seasons 1.1.1-BETA
		shulkerutils: shulkerutils 1.0.1-1.16
		somnus: Somnus API 0.0.11-1.16.5
		spark: spark 1.5.2
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.1
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.2+build.220
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemmod: Wither Totems Mod 0.3.2
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		veinmining: Vein Mining 0.0.7-1.16.5
		waystones: Waystones 1.1.1.1
		windchimes: Windchimes 1.1.1
		yungsapi: YUNG's API 1.16.5-Fabric-2
		zoob: Monster Of The Ocean Depths 3.0.0
	Player Count: 8 / 15; [class_3222['ScarlettBlade'/86, l='ServerLevel[world]', x=88.36, y=6.00, z=-55.23], class_3222['IlIBLIZZARDZIlI'/250, l='ServerLevel[world]', x=132.83, y=63.09, z=-10.53], class_3222['Grizguy34'/253, l='ServerLevel[world]', x=110.70, y=10.00, z=-58.67], class_3222['ChilloutJosh'/254, l='ServerLevel[world]', x=110.70, y=11.20, z=-57.92], class_3222['Inky_Scroll'/352, l='ServerLevel[world]', x=117.67, y=51.00, z=-11.76], class_3222['Roult'/213, l='ServerLevel[world]', x=91.30, y=10.00, z=-53.42], class_3222['Wyatts_'/509, l='ServerLevel[world]', x=91.16, y=11.00, z=-58.04], class_3222['Sektiss'/941, l='ServerLevel[world]', x=93.18, y=11.00, z=-57.09]]
	Data Packs: vanilla (incompatible), Fabric Mods, file/HarderEndcity.zip, file/Stoo's Survival Datapack v1.10d.zip, file/Tagged_Foods, file/bac_advancements
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by MoriyaShiine** [comment]
Can you try causing this with just bewitchment? This makes no sense

**Comment by Ninonsand** [comment]
I wasn't able to reproduce it in singleplayer unfortunately :( We're using blaze and cave's advancements and it seems that might have something to do with the problem. But disabling the datapack still results in a server crash

**Comment by MoriyaShiine** [comment]
Can you try to narrow down exactly what mod(s) are causing the crash?

**Comment by Ninonsand** [comment]
I don't know crash reports that well, but it looks like there is some advancement that happens when the altar is at about half power. Something is going wrong with checking for player's permissions because it mentions server operator. I'm not sure about the stripped log mentioned, but that's about all I can gather.

I've tried manually giving the advancement to the players and then retrying the altar but it still crashes.

**Comment by irunatbullets** [comment]
Not sure if this is the same crash but we've had a user with a crashing server due to the altar and possibly byg.

https://paste.alloffabric.com/zoxicexage.yaml

If this is unrelated I can make a new issue for it.
