### ISSUE TITLE
Werewolf form does not appear client side.

### ISSUE THREAD

**Issue by ZroNoh** [MoriyaShiine/bewitchment#125]
Basically a duplicate #84 but I'm not running a cracked server, nor do I have the extra addon the other poster had.
I'm using v1.16.5-8 on the modpack All of Fabric 3
https://mclo.gs/LlIvt5i

Normal Form:
![javaw_B8sL9bEAIK](https://user-images.githubusercontent.com/32776743/117390714-ac232080-aebc-11eb-8241-817e7ec9d622.png)

Werewolf Form:
![javaw_TMv4UxLZO9](https://user-images.githubusercontent.com/32776743/117390761-c2c97780-aebc-11eb-8d2b-8b8968aceeed.png)

Everybody else can see me as a werewolf, only I see myself as a stretched human. For some reason the bug fixed itself when I changed my skin but it came back after I closed my game.

**Comment by MoriyaShiine** [comment]
This isn't a problem on 1.16.5-11, All of Fabric uses an old version so you should ask them or wait for them to update
