### ISSUE TITLE
Error in server log - Latest bewitchment version

### ISSUE THREAD

**Issue by deadspidervenom** [MoriyaShiine/bewitchment#128]
while using "NotEnoughCrashes" to check for errors in another mod i noticed that it highlighted a error caused by bewitchment.

> java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Class moriyashiine.bewitchment.common.registry.BWCommands$FortuneArgumentType already has a serializer!
>         at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
>         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
>         at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1113) ~[?:?]
>         at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
>         at net.minecraft.server.MinecraftServer.reloadResources(MinecraftServer:1326) ~[intermediary-server.jar:?]
>         at net.minecraft.server.command.ReloadCommand.method_29480(ReloadCommand:22) ~[?:?]
>         at com.rubixdev.rug.RugServer.reload(RugServer.java:309) ~[fabric-rug-1.16.5-1.1.8.jar:?]
>         at com.rubixdev.rug.RugServer.onServerLoadedWorlds(RugServer.java:144) ~[fabric-rug-1.16.5-1.1.8.jar:?]
>         at carpet.CarpetServer.lambda$onServerLoadedWorlds$1(CarpetServer.java:108) ~[fabric-carpet-1.16.5-1.4.35+v210505.jar:?]
>         at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
>         at carpet.CarpetServer.onServerLoadedWorlds(CarpetServer.java:108) ~[fabric-carpet-1.16.5-1.4.35+v210505.jar:?]
>         at net.minecraft.server.MinecraftServer.handler$cjc000$serverLoadedWorlds(MinecraftServer:9231) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:339) ~[intermediary-server.jar:?]
>         at net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer:179) ~[?:?]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:645) ~[intermediary-server.jar:?]
>         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> Caused by: java.lang.IllegalArgumentException: Class moriyashiine.bewitchment.common.registry.BWCommands$FortuneArgumentType already has a serializer!
>         at net.minecraft.command.argument.ArgumentTypes.register(ArgumentTypes:74) ~[?:?]
>         at moriyashiine.bewitchment.common.registry.BWCommands.init(BWCommands.java:39) ~[bewitchment-1.16.5-11.jar:?]
>         at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41) ~[b598a0e4-9d96-4281-bc85-63c93a1a360a.jar:?]
>         at net.minecraft.server.command.CommandManager.handler$zfi000$fabric_addCommands(CommandManager:1547) ~[?:?]
>         at net.minecraft.server.command.CommandManager.<init>(CommandManager:233) ~[?:?]
>         at net.minecraft.resource.ServerResourceManager.<init>(ServerResourceManager:34) ~[?:?]
>         at net.minecraft.resource.ServerResourceManager.reload(ServerResourceManager:78) ~[?:?]
>         at net.minecraft.server.MinecraftServer.method_29437(MinecraftServer:1327) ~[intermediary-server.jar:?]
>         at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
>         ... 14 more

**Comment by MoriyaShiine** [comment]
Fixed as of https://github.com/MoriyaShiine/bewitchment/pull/127
