### ISSUE TITLE
Demons still crash when trading on servers

### ISSUE THREAD

**Issue by MitztheKat** [MoriyaShiine/bewitchment#129]
[crash-2021-05-10_22.03.42-server.txt](https://github.com/MoriyaShiine/bewitchment/files/6455232/crash-2021-05-10_22.03.42-server.txt)
[2021-05-10-7.log](https://github.com/MoriyaShiine/bewitchment/files/6455233/2021-05-10-7.log)
Hey there,
the issue still persists.
Thanks,
Mitz.
PS: as far as I know I'm using the latest version of bewitchment and such. if I ain't, I have no idea *why* it's not.

**Comment by MoriyaShiine** [comment]
There was an update an hour ago
