### ISSUE TITLE
Ghosts ignoring Candelabra

### ISSUE THREAD

**Issue by henkaa** [MoriyaShiine/bewitchment#137]
I am plying All of Fabric 3 - 2.7.4 ATM.
It has Bewtichment 1.16.5-12 installed.

It seems the Ghosts ignores the Candelabra, or am I using them wrong? I have placed them and lit them all over my house but I can still be attacked by Ghosts even if I stand like 2-3 blocks away from a Silver Candelabra.

**Comment by MoriyaShiine** [comment]
They only path away from it, if they're already targeting you then they'll ignore the candelabra

**Comment by henkaa** [comment]
Ok. Good to know.. but a little curious about the logic.. I have silver candelabras like 6 blocks apart and I still see ghosts flying around near them (when I am a bit away and they clearly not targeting me). What should be the avoidance distance on say a silver candelabra?

I just want a house where I am not constantly bothered by ghosts :)
