### ISSUE TITLE
[1.16.5] Pingspam borks Bewitchment on server when creating an altar due to thinking a fake player already exists.

### ISSUE THREAD

**Issue by VexTheWanderer01** [MoriyaShiine/bewitchment#139]
What it says on the tin. Running a server.
Crash report: https://pastebin.com/JRsie5TV
Edit: Its specifically a library IN pingspam, named Nevseti, however, I am using only pingspam.
Edit 2: Also, I should note with the ruined equipment mod, it spams the "awww, it broke" achievement from a fake_player due to a wooden axe, which is included in this log better, and the other one. https://mcpaste.io/6c32c3136f7d2332 Both of these issues stop when the 2 mods are removed. The achievement is actually from a data pack, which is odd. It spams less when the ruined equipment mod is removed, but still spams

**Comment by MoriyaShiine** [comment]
They (reasonably) don't do a check for artificial players, but I can't do anything to fix it. I would recommend reporting it to them. The line in question is https://github.com/BasiqueEvangelist/ne-v-seti/blob/32778773e6469674067bbc867afd9d23bfe16f0a/src/main/java/me/basiqueevangelist/nevseti/OfflineNameCache.java#L42
