### ISSUE TITLE
Ticking player Issue

### ISSUE THREAD

**Issue by TopHatSerpent2020** [MoriyaShiine/bewitchment#140]
ok well im having a issue with the Besmirchment addon like for some reason when i try to summon beezlebub all of a sudden the game crashes and i get a thing talking about "ticking player" and i was using the newest versions of both the mod and the addon

oh also i got some other mods installed as well 

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/26/21 5:13 PM
Description: Ticking player

java.lang.NoSuchMethodError: moriyashiine.bewitchment.api.BewitchmentAPI.usePlayerMagic(Lnet/minecraft/class_1657;IZ)Z
	at de.aelpecyem.besmirchment.common.item.ScrollOfTormentItem.method_7852(ScrollOfTormentItem.java:69)
	at net.minecraft.class_1799.method_7949(class_1799.java:1056)
	at net.minecraft.class_1309.method_6076(class_1309.java:2816)
	at net.minecraft.class_1309.method_5773(class_1309.java:2210)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_3222.method_14226(class_3222.java:434)
	at net.minecraft.class_3244.method_18784(class_3244.java:219)
	at net.minecraft.class_2535.method_10754(class_2535.java:232)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7375/684697499.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.aelpecyem.besmirchment.common.item.ScrollOfTormentItem.method_7852(ScrollOfTormentItem.java:69)
	at net.minecraft.class_1799.method_7949(class_1799.java:1056)
	at net.minecraft.class_1309.method_6076(class_1309.java:2816)
	at net.minecraft.class_1309.method_5773(class_1309.java:2210)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 216
	Entity Name: TopHatSerpent12
	Entity's Exact location: -279.38, 70.00, 3.60
	Entity's Block location: World: (-280,70,3), Chunk: (at 8,4,3 in -18,0; contains blocks -288,0,0 to -273,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:434)
	at net.minecraft.class_3244.method_18784(class_3244.java:219)
	at net.minecraft.class_2535.method_10754(class_2535.java:232)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$7375/684697499.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 722883392 bytes (689 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 0.5.0
		adventurez: AdventureZ 1.2.2
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.3.4-1.16.4
		besmirchment: Besmirchment 1.16.5-6
		betterend: Better End 0.9.6-pre
		betternether: Better Nether 5.0.7
		bewitchment: Bewitchment 1.16.5-15
		bssentials: Bssentials 3.x
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		castle_dungeons: Castle Dungeons 2.2
		chime: Chime 1.1.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.24
		cosmetic-armor: Cosmetic Armor 1.0.0
		curios: Curios API 0.0.13-1.16.5
		cyber-permissions: CyberPermissions 1.1
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.5
		dyetherite: Dyetherite 1.0.0+1.16.4
		ears: Ears 1.2.2
		enva: Environmental Armor 1.3.1
		extraorigins: Extra Origins 1.16.5-11
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.11.0
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		haema: Haema 1.7.0
		impersonate: Impersonate 2.2.1
		ironchest: Iron Chests 1.1.3
		ironfurnaces: Iron Furnaces 2.4.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		latoorigins: Lato Origins 0.6.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.4
		locki: Locki 0.2.0
		mermod: Mermod 1.3
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.4.0
		mobropes: Mob Ropes 1.16.4+1.0.2
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		originsplus: Origins Plus 0.0.2
		originsumbrellas: Origins: Umbrellas 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.1.0+21w18a
		phosphor: Phosphor 0.7.2+build.12
		playerabilitylib: Pal 1.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		requiem: Requiem 1.7.7
		requiemapi: Requiem-API 1.7.7
		respawnablepets: Respawnable Pets 1.16.5-2
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		satin: Satin 1.5.1
		simple_backpack: SimpleBackpack 1.0.38
		slimeorigin: Slimeorigin 3.0.0
		somnus: Somnus API 0.0.11-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		thearchitect: The Architect 1.0.0+1.16.5-fabric
		toastermod: Rise of the Toasters 1.1.6
		toomanyorigins: TooManyOrigins 0.1.3
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		transparent_cosmetics: Transparent Cosmetics 1.2.0
		trinkets: Trinkets 2.6.7
		wildfire_gender: Wildfire's Gender Mod 2.4.1
		winged: Winged Mod 1.16.5-2.0.5
		worldedit: WorldEdit 7.2.5+57d5ac9
		xaerominimap: Xaero's Minimap 21.8.1
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['TopHatSerpent12'/216, l='ServerLevel[New World]', x=-279.38, y=70.00, z=3.60]]
	Data Packs: vanilla (incompatible), minecraft:transparent_cosmetics, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by MoriyaShiine** [comment]
Report to Besmirchment, not here

**Comment by Aelpecyem** [comment]
agony

**Comment by TopHatSerpent2020** [comment]
sorry didn't realize there was a discord server for the addon
