### ISSUE TITLE
Werewolf crashing

### ISSUE THREAD

**Issue by TopHatSerpent2020** [MoriyaShiine/bewitchment#141]
well aside from the last issue i had with a addon (again i didn't realize there was a discord for that) but anyway im also having another issue with the werewolves like when a werewolf spawns like i randomly get crashed by them and why idk but like its not been happening as much now but like yesterday when i messed around with the mod i was randomly crashing when i spawned in a werewolf and like it wouldn't always happen like again it would be random and the crash report would talk about a "ticking entity" and the weirdest thing like when i hop back into the game with the werewolf it wouldn't crash, like as i said it seems a little random when it happens and well as i said it's not been happening now but in case it does happen again im just wanting to figure out whats going on with that

and also i do have other mods installed and i have tried the mod without the other mods yesterday and it still randomly crashed

https://pastebin.com/iC8a8pxX

**Comment by MoriyaShiine** [comment]
Can you see if this happens with only Bewitchment?

**Comment by TopHatSerpent2020** [comment]
so like just take out every other mod and leave only bewitchment and the mods it needs then test it out from there?

**Comment by MoriyaShiine** [comment]
yes

**Comment by TopHatSerpent2020** [comment]
alright then just being sure

**Comment by TopHatSerpent2020** [comment]
ok i tried it out on its own and it seems to work fine but when i throw in my other mods it crashes
