### ISSUE TITLE
Unable use Smithing Table to make Silvered items

### ISSUE THREAD

**Issue by Fade-Alchemist** [MoriyaShiine/bewitchment#142]
The recipes for silvered sword and silvered armor seem to have been removed. 
![image](https://user-images.githubusercontent.com/29619427/121648767-7514d180-ca5d-11eb-8ada-e8a13e71f892.png)
most recent version of bewitchment.

**Comment by Ayrion** [comment]
It has.

**Comment by MoriyaShiine** [comment]
The silver tools haven't existed for a while
