### ISSUE TITLE
All of the clothing added in the mod has no texture, it just has the purple and black checkered that happens when there is no texture

### ISSUE THREAD

**Issue by DeathlyCrane** [MoriyaShiine/bewitchment#143]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod or do not provide the version of the mod you are using.

You may delete this text when creating your issue.

**Comment by Ayrion** [comment]
Uninstall Optifine
