### ISSUE TITLE
Invisible water in cauldrons?

### ISSUE THREAD

**Issue by HmmLemon** [MoriyaShiine/bewitchment#146]
Version 1.16.5-15

Really strange visual problem with the witch cauldron. The cauldron can be filled and emptied, and will produce all the normal sounds, boiling, etc., but visually the cauldron appears to be empty. It functions otherwise completely normally and I am able to create elemental oils, but even as the ingredients are added and disappear, the cauldron continued to look empty. 

I've removed all mods except the required dependencies for Bewitchment, but the problem has remained. After briefly wondering if it might be my resource pack, I tried removing it but it also didn't fix the issue.

I don't know how best to show this in images, but if it would help, I can take some screenshots. If you need anything else I've not provided, please let me know.

**Comment by Sunconure11** [comment]
Do you have optifine installed?

**Comment by HmmLemon** [comment]
No I do not.

**Comment by nok-ko** [comment]
This problem seems to happen on the “Fabulous!” graphics setting.

![2021-06-15_21 00 31](https://user-images.githubusercontent.com/13428215/122155951-d7ceea00-ce1c-11eb-8d59-29f7ca3e4b4e.png)

**Comment by nok-ko** [comment]
@HmmLemon Were your graphics set to Fabulous?

**Comment by VoidLock92** [comment]
I can confirm that this was happening to me when I had my graphics set to "Fabulous" also. Changing it to fancy fixed the issue for me.

**Comment by MoriyaShiine** [comment]
I doubt I'll ever get to fixing this until I bother with rewriting the mod, so I'll close it and see if it's still relevant in the future
