### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DabbingEevee** [MoriyaShiine/bewitchment#147]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod or do not provide the version of the mod you are using.

You may delete this text when creating your issue.

when opening the betterend alloy furnace with bewitchment it crashes with the following. this is a mix of the logs and crash report with the error

[crash.txt](https://github.com/MoriyaShiine/bewitchment/files/6672771/crash.txt)

**Comment by MoriyaShiine** [comment]
Didn't see the crash report because you didn't delete the template

Regardless, this looks like an issue with Jumploader
