### ISSUE TITLE
Caduceus Staff awards “Return to Sender” Advancement

### ISSUE THREAD

**Issue by nok-ko** [MoriyaShiine/bewitchment#149]
Reported on Bewitchment 1.16.5-15

The Caduceus Staff shoots a fireball when right-clicked. This fireball will award the player the “Return to Sender” advancement when it hits and kills a Ghast, despite it not being a fireball the Ghast originally shot.

This is an issue that is probably not worth fixing.

**Comment by MoriyaShiine** [comment]
Couldn't figure this out but it doesn't matter that much anyway lol
