### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by olee** [MoriyaShiine/bewitchment#151]
Could you tell us on whether you intend to support 1.17 in the future?
I guess with the mod being based on fabric, this should be less of an effort than in the past, is it?

**Comment by MoriyaShiine** [comment]
Yes, please be patient. Ask these kinds of questions on the discord, github issues are for issues

**Comment by olee** [comment]
Well, github issues are also a place to track features and not only issues, but if you prefer this on discord that's fine 👍

**Comment by MoriyaShiine** [comment]
Yeah that's true, I'm just used to people coming here and asking "when will you add x" or "how do I become a vampire" and it got really annoying really quick lol. My original message may have been a little hostile, sorry if that was the case

**Comment by olee** [comment]
No no! Not at all :-)
I want to be patient with this because I myself maintained a larger mod for a long time and I know how annoying this can be.

That is why I think it might make sense to have an open tracking issue here to inform everyone looking for this information about the current state.

Anyway, I already saw you last announcement on Discord and I'm happily waiting for the 1.17 release.
If there's something I could do to help, just tell me and I might be able to support you there 👍
