### ISSUE TITLE
Totem of undying doesn't work during the transformation process

### ISSUE THREAD

**Issue by alexcrafteroreal** [MoriyaShiine/bewitchment#156]
Hi,
like the tittle says the Death protection poppet is not working and I can´t become a vampire
I have recorded this video to show you what I mean.
https://www.youtube.com/watch?v=qs4WNaBEhvw

**Comment by MoriyaShiine** [comment]
Poppet: you have to bind it to yourself lol

Transformations: you need the Susceptibility curse or "dying" to the creatures won't have any effect

**Comment by MoriyaShiine** [comment]
I have a very large brain and completely glossed over the fact that you did apply the curse. Can you test if it works with the poppet instead of the totem?

**Comment by alexcrafteroreal** [comment]
Hey! Thanks for the quick reply!
Binded the poppet to myself and it worked. And tried the vampirism with the poppet and aswell It worked. :D :D
It seem it was a problem of the totem of undying.

**Comment by MoriyaShiine** [comment]
I see, thanks for the report!
