### ISSUE TITLE
Game unable to startup after dying to vampire

### ISSUE THREAD

**Issue by Slompeyz** [MoriyaShiine/bewitchment#157]
Hey, I was trying to become a vampire (I had the curse of susceptibility and a bound death protection poppet) and I died to a vampire on the full moon, however my game immediately crashed and since then has not been able to start back up. Here's the crash report:
[crash-2021-07-03_03.12.17-server.txt](https://github.com/MoriyaShiine/bewitchment/files/6758009/crash-2021-07-03_03.12.17-server.txt)

**Comment by MoriyaShiine** [comment]
It's an issue with the Nourish integration, you can either remove or downgrade Nourish and wait for an update
