### ISSUE TITLE
Brazier chapter not unlocked. 

### ISSUE THREAD

**Issue by Fresh42069** [MoriyaShiine/bewitchment#159]
I can't unlock the chapter for the brazier even though I already crafted it. How do I fix it?

**Comment by MoriyaShiine** [comment]
Have you visited a nether fortress?

**Comment by Fresh42069** [comment]
No, I got nether wart from a bastion remnant

**Comment by MoriyaShiine** [comment]
That would be it, the advancement relies on you visiting the fortress

**Comment by Fresh42069** [comment]
I see thank you!
