### ISSUE TITLE
Not properly setting invisiblity when sneaking with specter bangle

### ISSUE THREAD

**Issue by doctor4t** [MoriyaShiine/bewitchment#162]
**Problem:** When sneaking with the specter bangle, this makes the player invisible. However, the entity invisibility tag is not set, so mods that rely on the isInvisible() method to do specific actions will not be compatible.

**Example:** The best example I have for this is Illuminations, where the pets and aura goes invisible with an invis potion, but not the specter bangle.

**How to fix:** Whenever making the player invisible, use setInvisible(true).

**Comment by VoidLock92** [comment]
Can confirm :) I was chatting with them about this. I was just about to make an issue :P
