### ISSUE TITLE
Polymorph illumination particles

### ISSUE THREAD

**Issue by VoidLock92** [MoriyaShiine/bewitchment#163]
At the current moment with the last fix in version 17 of Bewitchment illumination particles now get hidden with the spectral bangle properly allowing players to sneak with their particles. I wonder if there is a way to allow polymorph to hide particles also as these give away a players true identity. 

The same bit of code identifying a player as invisible might be able to be applied to the polymorph potion without actually making them go invisible. In a sense the player as we knew them is invisible and they look like another.

I'm not sure if this would be better suited for impersonations compatibility. But figured I would share it here as this is what we found on my server with my modpack. Players that impersonate someone else with polymorph must still go and turn off their particles then restart their game to get illumination particles to disappear and not blow their cover.

**Comment by MoriyaShiine** [comment]
This is probably something that should be reported to Imperosonate, if I were to make a solution on Bewitchment's end, it would be really hacky

**Comment by VoidLock92** [comment]
Sounds good :) I will report it to them and see what they can do. Thanks for the quick reply!
