### ISSUE TITLE
Flan support for cauldron protection

### ISSUE THREAD

**Issue by VoidLock92** [MoriyaShiine/bewitchment#164]
It would be great to have support for Flan to have Witches Cauldron protected by the 'Bucket' protection flag. I am not sure if they add that support or if it would be on your end. Either way not a big deal just thought I would mention that currently vanilla cauldrons are protected and players without the 'Bucket' permission cannot take liquids from them, but the Witches Cauldron is unprotected regardless, allowing players to steal brews.
![image](https://user-images.githubusercontent.com/21327041/126941640-04beba9a-d68a-43cc-b66a-fee5ef17eed9.png)

**Comment by MoriyaShiine** [comment]
Bewitchment is in maintenance-only mode right now, so unfortunately there aren't going to be any more features or compatibility for the current version.

**Comment by MoriyaShiine** [comment]
Ok well I can't do this, their maven seems to be broken

**Comment by VoidLock92** [comment]
Hmm alright. Thanks for trying :) I will report it to their dev and make sure they know about it.

**Comment by VoidLock92** [comment]
This is what they informed me:
![image](https://user-images.githubusercontent.com/21327041/127689276-fe3bd0b6-ddec-4837-b603-94af483a85a7.png)
