### ISSUE TITLE
Corruption mismatch (book issues)

### ISSUE THREAD

**Issue by VoidLock92** [MoriyaShiine/bewitchment#165]
I think this might be a miss type or the wrong image shown, not sure what ingredient is the real one but it has a confusing inconsistency I just thought I would let you know about.
![image](https://user-images.githubusercontent.com/21327041/127081730-2922e0cc-16f1-445d-97c3-757b95bd5f3a.png)

**Comment by MoriyaShiine** [comment]
Can you check what version you're on, pretty sure this was fixed

**Comment by VoidLock92** [comment]
bewitchment-1.16.5-17.jar

**Comment by VoidLock92** [comment]
I also found this in the book
![image](https://user-images.githubusercontent.com/21327041/127083908-fedac8ef-29f1-4505-ae35-87ff8edfa401.png)

**Comment by MoriyaShiine** [comment]
The layering should be reported to Patchouli, that's not something I can fix
