### ISSUE TITLE
Mundane potions can't be brewed?

### ISSUE THREAD

**Issue by Derpford** [MoriyaShiine/bewitchment#167]
I'm trying to brew a potion of absorption, per the book's advice.
1. Using a Mandrake Root and a Honey Bottle results in a failed brew.
2. Using a Honey Bottle by itself turns the water pink but does nothing else. I can't retrieve the brew afterward.
3. Tossing in redstone or glowstone after that does nothing. In fact, no matter what I throw in after that, nothing changes (except for wood ash, which clears the cauldron).

Regular brews work just fine, though adding Mundane brew ingredients obviously causes problems. Is there a hidden step somewhere in here?

**Comment by MoriyaShiine** [comment]
Did you have enough altar power? You need 150ME per ingredient

**Comment by Derpford** [comment]
Yeah, I tried both with an altar that had 150 power and with two altars with around 110 each.

**Comment by MoriyaShiine** [comment]
You can't combine altars

**Comment by Derpford** [comment]
All right, but with the altar that had 150 power I got no results. Does having a second altar nearby screw it up, even if one of the two altars has enough power? Also, it took a netherite candelabra and diamond sword to get it above 150 power, how am I supposed to get any more complex brews done?

**Comment by Ayrion** [comment]
It's best not to have any other altars around, for altar power you need a large variety of plants around the altar.

**Comment by MoriyaShiine** [comment]
Yes, having more than one screws it up. Blocks that use ME will grab from the closest altar regardless of which has the higher amount. I was unable to replicate this issue though, so I will close it

**Comment by Derpford** [comment]
I tried with one altar and still can't brew with a honey bottle. Modlist:

https://pastebin.com/bw8wi1hH
