### ISSUE TITLE
AppleSkin Compat

### ISSUE THREAD

**Issue by VoidLock92** [MoriyaShiine/bewitchment#172]
Compatibility for AppleSkin to auto remove the proper overlays when a player is non human would be awesome to prevent players from needing to do it by hand. 

Its dev told me this is the api for it
https://github.com/squeek502/AppleSkin/tree/1.16-fabric#for-mod-developers

Here is a link to the github ticket I had with them
https://github.com/squeek502/AppleSkin/issues/133

I know this is not a huge issue, but it would be greatly helpful going forward :) I know you said 1.16.5 is on maintenance, but maybe 1.17+ could have the compatibility if not 1.16. Love the mod thanks for all the hard work.

**Comment by MoriyaShiine** [comment]
Yeah I can work on it once 1.17 has the rest of its issues fixed, you can also reopen the flan issue since I wasn't expecting such a quick update (@Aelpecyem is very cool)

**Comment by VoidLock92** [comment]
Awesome sounds good :) Will do!

**Comment by VoidLock92** [comment]
Either I don't have permissions to reopen a ticket or I just don't know how. I cant seem to reopen the flan support ticket.
