### ISSUE TITLE
Downloading Bewitchment on the curse forge app makes it download the wrong version of cardinal components. 

### ISSUE THREAD

**Issue by toErIpNid** [MoriyaShiine/bewitchment#175]
Instead of latest you get a weird dev version which crashes the game on launch. 

MC Version: 1.17.1
Log: 
[crash-2021-08-09_23.38.08-client.txt](https://github.com/MoriyaShiine/bewitchment/files/6958998/crash-2021-08-09_23.38.08-client.txt)

**Comment by MoriyaShiine** [comment]
Dependency pulling on CurseForge seems broken right now, it only downloads 1 library and stops for me while a couple of days ago it worked just fine.
