### ISSUE TITLE
Mob audio way too loud (Fabric 1.17.1)

### ISSUE THREAD

**Issue by r00dboi** [MoriyaShiine/bewitchment#177]
Bewitchment custom mob sounds seem to be at max volume regardless of distance.

**Comment by CammiePone** [comment]
Which mobs in particular are you noticing this with? Most of the Bewitchment mobs do it the same way vanilla does.

**Comment by ItsWorldEater** [comment]
I've noticed it with ghosts, crows, snakes, owls, hellhounds, and a strange sinister laughter that I haven't been able to pinpoint yet.

**Comment by r00dboi** [comment]
Owls for sure, and I'm getting the sinister laughter too but can't find the culprit either. 

Ordinarily the mob noises get attenuated for distance but the Bewitchment mob sounds seem to be coming from the playermodel itself so discerning the source is kinda difficult.

The sounds themselves are quite nice despite the volume weirdness. Great job, love the mod!

**Comment by ItsWorldEater** [comment]
Yeah, I have a nice giggle every time I hear a crow, but my friend is saying that every time they fly over a desert, it sounds like there's a snake in their pocket.

**Comment by MoriyaShiine** [comment]
It has to do with sounds being in stereo and not mono, sound dev has been notified
