### ISSUE TITLE
Startup Crash Fabric 1.17

### ISSUE THREAD

**Issue by ZestyBlaze** [MoriyaShiine/bewitchment#178]
Crash Report: https://mystb.in/WorthIncludedTalent.yaml

Hey I got this crash when trying to create a world with Bewitchment installed, is there any more information you need from me?

**Comment by MoriyaShiine** [comment]
Clone of https://github.com/williambl/haema/issues/84, I don't think Will has updated compat properly but he's usually really fast about things
