### ISSUE TITLE
Unfired Jars not in game?

### ISSUE THREAD

**Issue by Whispyre** [MoriyaShiine/bewitchment#183]
Hey I'm new to the mod, and was watching a video on how to get started. It asked to make unfired jars, but I don't seem to have them as an option? I tried the recipe that was in the wiki and nothing came up so I checked REI to see if I had the recipe wrong. It just doesn't seem to exist? I'm sorry if this changed and it's not supped to be in the game, I tried googling it and nothing came up. So now I'm unsure on where to start. Thank you.

**Comment by MoriyaShiine** [comment]
Those are from a very very old version lol, the Book of Shadows has the most up to date information.

**Comment by Whispyre** [comment]
Ahh okay, thank you sorry for the trouble haha.

**Comment by MoriyaShiine** [comment]
No worries :p
