### ISSUE TITLE
Bewitchment "fake requirements" 

### ISSUE THREAD

**Issue by Emixiou** [MoriyaShiine/bewitchment#184]
Hi, here is my problem: when I want to run the game by using Fabric Loader, Fabric Api and Bewitchment in 1.17.1 (so the prerequisites) a pop-up appears telling me that the launch failed because Bewitchment requires "pehkui @ [*]". So I added the pehkui mod and again the pop-up appeared and said there was a missing mod: "impersonate". And when I added impersonate it asks for another mod again (and of course one of these "fake requirements" is not in the good version).
I don't know what to do... And I really want to play this mod this is why I'm asking for your help !

Here is a screenshot of the fail : 
![Screenshot_5](https://user-images.githubusercontent.com/88975284/129481539-088bdfbb-63af-4f86-befb-ff24539577e0.png)
(there is no crash changelogs)

**Comment by MoriyaShiine** [comment]
I don't know what a "fake requirement" is, but the list of dependencies is on the curseforge page (be it the relations tab (bad and inaccurate) or click on the file and s roll down
