### ISSUE TITLE
Cannot See That I Am A Werewolf

### ISSUE THREAD

**Issue by Pastastaar** [MoriyaShiine/bewitchment#185]
Howdy, I am a Stage 2 werewolf with the ability to transform back and forth between my forms and everyone can see my werewolf form. However, I cannot. Is there a way to fix this?

**Comment by MoriyaShiine** [comment]
What version are you using?

**Comment by Pastastaar** [comment]
For Minecraft version: 1.16.5!

**Comment by MoriyaShiine** [comment]
I meant the mod version lol

Regardless, this is fixed in 1.17 so I recommend you update
