### ISSUE TITLE
NullPointerException when trying to make a contract with a demon in 1.16.5-18

### ISSUE THREAD

**Issue by noclueumbreon** [MoriyaShiine/bewitchment#191]
Game inconsistently throws an error and crashes when trying to open the demon contracts menu. Unsure what causes this- crash log attached

Appears to be a problem with how the demon menu is rendered- I'm on Win10 with a 1920x1080 screen, running in fullscreen.

[crash-2021-08-27_09.06.45-client.txt](https://github.com/MoriyaShiine/bewitchment/files/7068265/crash-2021-08-27_09.06.45-client.txt)

**Comment by noclueumbreon** [comment]
Thanks for the response! Mind if I ask why the error only happens sometimes?

**Comment by MoriyaShiine** [comment]
Nobody knows lol, that's the issue with optifine. It's closed source and all rights reserved so it's impossible to see what optifine does without reverse engineering and guesses.

**Comment by noclueumbreon** [comment]
That's unfortunate- mind if I attempt to fork the repository and use my extremely limited java knowledge to sloppily remove the portrait methods? It'd be purely for personal use, and mostly just because I'm not sure there's a smart leaves alternative as of yet haha

**Comment by MoriyaShiine** [comment]
I don't mind if it's for personal use, but you could also use https://modrinth.com/mod/cull-leaves lol

**Comment by noclueumbreon** [comment]
Oh shit. Had no idea that existed- thank you for the help. Might try and fix the error in my off time anyways, but I wish you the best of luck in your next modding steps!

**Comment by MoriyaShiine** [comment]
Thanks! :)
