### ISSUE TITLE
Conflict with Artifality or its dependants.  

### ISSUE THREAD

**Issue by Silviyius** [MoriyaShiine/bewitchment#193]
Error: java.lang.IllegalStateException: Pose stack not empty
Exit Code: -1

https://pastebin.com/zuti0uJc

**Comment by MoriyaShiine** [comment]
Looks similar to https://github.com/Globox1997/MedievalWeapons/issues/28 and not an issue with Bewitchment but rather an issue with Artifality and Pehkui. I recommend making an issue on their github, ask them to check if they're canceling any methods to do with rendering and instead scale it to be invisible.

**Comment by Silviyius** [comment]
Thanks I posted the Issue with them.
