### ISSUE TITLE
Bewitchment On Server not generating ores and trees.

### ISSUE THREAD

**Issue by toErIpNid** [MoriyaShiine/bewitchment#194]
A friend of mine's server is not generating the trees and ores required to progress in the mod. It works fine on my own server, but not on his. We don't know if its a bug or what. 
https://pastebin.com/XhzwiUQa

**Comment by Friskygote** [comment]
Bewitchment is not on the list of loaded mods in that log. Make sure it's in the mods folder.

**Comment by MoriyaShiine** [comment]
That's a good point lol

**Comment by toErIpNid** [comment]
I'm confused. We all have bewitchment in our modpacks and can log onto the server without it kicking us out. Should they try a fresh install?

**Comment by Friskygote** [comment]
You probably should. 
Having Bewitchment on the client and entering a server without Bewitchment will not prevent you from joining. It would however be problematic if server had a mod (that is not server side only) and your client didn't.
The sole fact we can see from your log is that Bewitchment mod is simply not present on your list of mods. It can not load for various reasons like having a filename that doesn't end with .jar, or being corrupted in some way. Dropping a file from Bewitchment CurseForge page into mods folder should theoretically also help, unless newer versions could cause incompatibilities with other mods in the pack.
