### ISSUE TITLE
Please remove pehuki as dependent 

### ISSUE THREAD

**Issue by red2blue** [MoriyaShiine/bewitchment#195]
Pehuki is not compatible with a lot of mods...... the list is insane. 

Your mod is so amazing, and I've been using it and want to keep using it but Pehuki is really limiting my modpack. Is there any way you can make a config option or something that makes it so if you set something as false it disables pehuki as a dependency and removes what needs it in bewitchment? or something?

[1.17.1/Fabric]

**Comment by MoriyaShiine** [comment]
No, this isn't possible, sorry

**Comment by CammiePone** [comment]
What needs it is the transformations (vampires and werewolves) so if it was removed/disabled, you would lose out on those.

**Comment by red2blue** [comment]
Damn thats a shame =/. honestly, I would take losing out on those two mobs vs not being able to use a lot of other mobs while still using the rest of bewitchment. Not your fault though, I wish the guys at Pehuki would fix some of the issues.

**Comment by red2blue** [comment]
https://github.com/Virtuoel/Pehkui/issues

They have 64 open issues, you sure you still want to make it mandatory to use pehkui?

**Comment by CammiePone** [comment]
Considering both of us are on relatively good terms with Virtuoel, yeah. We know.
