### ISSUE TITLE
So funny thing actually I'm using the latest version of bewitchment and Fabric API and the latest fabric version and im not using any other mods and the game says "an unexpected issue has occurred" and I can't get it to run so every time I press play it crashes could you help? I really want to play the mod.

### ISSUE THREAD

**Issue by UwUsheep** [MoriyaShiine/bewitchment#201]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod, do not provide the version of the mod you are using, or are using "latest." "Latest" doesn't mean anything to developers, so please avoid using the term and state the specific version, even if it does happen to be the latest release at the time.

You may delete this text when creating your issue.

**Comment by MoriyaShiine** [comment]
Bewitchment has a lot of dependencies, be sure to install those. For more help, the discord is a much easier place; github issue trackers are for bugs
