### ISSUE TITLE
Crash when I open Better End Furnace

### ISSUE THREAD

**Issue by Pipiolo13** [MoriyaShiine/bewitchment#202]
Replicate:
- Install Bewitchment (latest 1.17.1 version)
- Install Better End (latest 1.17.1 version) 
- Put End Stone Melter Furnace
- Try to open this

Crash only happend on the client. Server don't stop

Log Crash here:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/20/21, 4:34 PM
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_17682()" because the return value of "moriyashiine.bewitchment.common.entity.DemonMerchant.getDemonTrader()" is null
	at moriyashiine.bewitchment.client.screen.DemonScreen.drawPortrait(DemonScreen.java:51)
	at moriyashiine.bewitchment.client.screen.DemonScreen.method_25394(DemonScreen.java:36)
	at net.minecraft.class_757.method_3192(class_757.java:1273)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$ccc000$fillPatchouliContext(class_128.java:521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$ccc000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:42)
	at net.minecraft.class_128.method_560(class_128.java:339)
	at net.minecraft.class_757.method_3192(class_757.java:1277)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Screen render details --
Details:
	Screen name: moriyashiine.bewitchment.client.screen.DemonScreen
	Mouse location: Scaled: (341, 178). Absolute: (683.000000, 357.000000)
	Screen size: Scaled: (683, 357). Absolute: (1366, 714). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Diatrabas'/302, l='ClientLevel', x=285.70, y=74.00, z=1008.41]]
	Chunk stats: 289, 121
	Level dimension: minecraft:the_end
	Level spawn location: World: (-169,95,-97), Section: (at 7,15,15 in -11,5,-7; chunk contains blocks -176,0,-112 to -161,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5495536 game time, 7006452 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Default-Dark-Mode-1.17-(v1.3.0).zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.14.0-0-MANJARO
	Java Version: 16.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1092570624 bytes (1041 MiB) / 3015704576 bytes (2876 MiB) up to 4429185024 bytes (4224 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A12-9800 RADEON R7, 12 COMPUTE CORES 4C+8G
	Identifier: AuthenticAMD Family 21 Model 101 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Wani [Radeon R5/R6/R7 Graphics]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 264.00
	Graphics card #0 deviceId: 0x9874
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10827.78
	Virtual memory used (MB): 6063.12
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms2432m -Xmx4224m
	Fabric Mods: 
		adorn: Adorn 2.1.5+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.11
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.1.3
		arcanus: Arcanus 1.14
		architectury: Architectury 2.4.26
		autoreconnect: AutoReconnect 1.3.2
		autosmeltenchant: AutosmeltEnchant 1.1.0
		bclib: BCLib 0.3.1
		beaconoverhaul: Beacon Overhaul 1.4.1+1.17
		betterend: Better End 0.11.0-pre
		betterpingdisplay: Better Ping Display 1.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		bewitchment: Bewitchment 1.17-6
		bigbeacons: Big Beacons 1.2.3
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		blockus: Blockus 2.2.8+1.17.1
		bno: Basic Nether Ores 1.17-6.0.0-Fabric
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.0
		charm: Charm 3.3.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		clumps: Clumps 7.0.7
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 2.0.1
		croptopia: Croptopia 1.6.3
		croptosis: Croptosis 1.1.3
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dataattributes: Data Attributes 1.0.4
		dawn: Dawn API 2.0.5
		detailab: Detail Armor Bar 2.4.3+1.17.1-fabric
		dragonloot: DragonLoot 1.0.9
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		durability101: Durability101 0.0.4
		eldritch_mobs: Eldritch Mobs 1.9.6
		emerald_tools: Emerald Tools 1.2.27
		enchant_giver: Enchant Giver 1.1.0
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricenchantments: Fabric Enchantments 0.4.2
		fabricloader: Fabric Loader 0.11.7
		factory: Factory 1.17.1-1.4.0
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.7
		gobber2: Gobber2 2.4.48
		grindenchantments: Grind Enchantments 1.4.0+1.17.1
		hplus: Better Hoppers (Hopper+) 3.0.1
		impersonate: Impersonate 2.3.3
		improved-stations: Improved Stations 2.0.7
		infinitevillagertrading: InfiniteVillagerTrading 1.17.1-fabric0.36.1-1.1
		inmis: Inmis 2.3.2-1.17.1
		inventoryhud: Inventory HUD + 3.4.0
		ironchests: Iron Chests for Fabric 1.4.3
		ironfurnaces: Iron Furnaces 1.17.1-2.6.1-fabric
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		justenoughkeys: Just Enough Keys 0.2.1
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9-BETA+1.17
		lapisreserve: Lapis Reserve 1.0.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		magna: Magna 1.5.5-1.17-pre4
		malilib: MaLiLib 0.10.0-dev.24
		maybe-data: Maybe data 1.0.1-1.17
		mcda: MC Dungeons Armors 1.7.10
		mcdw: MC Dungeons Weapons 3.4.2
		megane: megane 5.4.0
		megane-base: megane-base 5.4.0
		megane-fabric-transfer: megane-fabric-transfer 5.4.0+1.3.0-fc40aa9d18
		megane-kibe: megane-kibe 5.4.0+1.8.1-BETA-1.17
		megane-runtime: megane-runtime 5.4.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.4.0+2.0.0-beta1
		megane-vanilla: megane-vanilla 5.4.0+1.17.1
		memoryusagescreen: Memory Usage Screen 1.2
		mermod: Mermod 1.8
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.11
		moenchant_lib: Mo'Enchantment Library 0.1.4
		moenchantments: Mo'Enchantments 1.18.0
		more_gems: More Gems 1.2.35
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		net_objecthunter_exp4j: exp4j 0.4.8
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		omega-config: OmegaConfig 1.0.8
		optifabric: OptiFabric 1.11.20
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		patchouli: Patchouli 1.17-54-FABRIC
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.3.0
		playerex: PlayerEx 3.0.4
		polymorph: Polymorph 0.0.13-1.17.1
		prefab: Prefab 2.1.5
		promenade: Promenade 2.1.2
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.3.1+1.17.1
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.0.275-alpha
		shulkerutils: shulkerutils 1.0.4-1.17
		simplyplatinum: Simply Platinum 3.0
		smootherbedrock: Smoother Bedrock 1.0.1
		somnus: Somnus API 0.0.14-1.17.1
		spellbound: Spellbound 1.5.0
		spirit: Spirit 1.1.0
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stuffz: StuffZ 2.3.2
		taxfreelevels: Tax Free Levels 1.2.1
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		things: Things 0.2.5
		toms_storage: Tom's Simple Storage Mod 1.1.16
		totemicoverhaul: Totemic Overhaul 1.2
		traverse: Traverse 4.0.0-beta.2
		trinkets: Trinkets 3.0.4
		tweakmyclient: TweakMyClient 1.1.10+build.26
		tweed: Tweed 3.0.0-beta.26
		upgradedshulkers: Upgraded Shulkers 1.0.2-1.17
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanillaexcavators: Vanilla Excavators 1.1.0
		ward_blocks: Ward Blocks 1.1.8
		waystones: Waystones 2.0.4
		wthit: wthit 3.9.0
		xaerominimap: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.16.1
		xp_storage: XP Storage 1.4.2+1.17.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD CARRIZO (DRM 3.42.0, 5.14.0-0-MANJARO, LLVM 12.0.1) GL version 4.6 (Core Profile) Mesa 21.2.1, AMD
	Window size: 1366x714
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/Default-Dark-Mode-1.17-(v1.3.0).zip
	Current Language: Español (España)
	CPU: 4x AMD A12-9800 RADEON R7, 12 COMPUTE CORES 4C+8G
	OptiFine Version: OptiFine_1.17.1_HD_U_G9
	OptiFine Build: 20210831-004129
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6 (Core Profile) Mesa 21.2.1
	OpenGlRenderer: AMD CARRIZO (DRM 3.42.0, 5.14.0-0-MANJARO, LLVM 12.0.1)
	OpenGlVendor: AMD
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_G9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /home/jhonatan/MultiMC5-Cracked-Linux/bin/instances/F Mods 1.17.1 Aternos/.minecraft/.optifine/OptiFine_1.17.1_HD_U_G9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by MoriyaShiine** [comment]
I don't even know how you're running Optifine since it's specifically marked to not launch if you have it installed, but that's what causes the crash
