### ISSUE TITLE
Coffin malfunction

### ISSUE THREAD

**Issue by mogneto** [MoriyaShiine/bewitchment#203]
There's a bug where you can't use the coffin, even as a vampire.

**Comment by MoriyaShiine** [comment]
I can't reproduce this as any of the transformations, what version of the mod are you using

**Comment by mogneto** [comment]
Last version

**Comment by MoriyaShiine** [comment]
That doesn't mean anything

**Comment by mogneto** [comment]
wdym?

**Comment by MoriyaShiine** [comment]
"Latest" is a useless measurement, it means nothing to mod developers

**Comment by mogneto** [comment]
ok, let me check here

**Comment by mogneto** [comment]
ok, so it seems like its not the latest. It's 1.17-6

**Comment by MoriyaShiine** [comment]
Can you try with just Bewitchment, and find what mod causes it because I can't reproduce this at all

**Comment by mogneto** [comment]
I tried only bewitchment (1.17-7) and its requirements, the coffin still won't let me sleep

**Comment by mogneto** [comment]
BTW i'm downloading the mods from curseforge app
