### ISSUE TITLE
Srver Sided Crash

### ISSUE THREAD

**Issue by jantendog** [MoriyaShiine/bewitchment#207]
[crash-2021-09-26_15.01.24-server.txt](https://github.com/MoriyaShiine/bewitchment/files/7231433/crash-2021-09-26_15.01.24-server.txt)

Something to do with a snake.
Mod Version is in the Report.
I migrated form version bewitchment-1.17-6.jar to bewitchment-1.17-7.jar then to the "final" Version bewitchment-1.17-8.jar.

**Comment by jantendog** [comment]
Downgrading to bewitchment-1.17-6.jar fixes it for now.

**Comment by MoriyaShiine** [comment]
This is only a problem on old worlds; I've released a fix to stop the crashing but you'll need to break and replace all of your poppet shelves since they don't work if they were placed prior to 1.17-7

**Comment by jantendog** [comment]
> 
> 
> This is only a problem on old worlds; I've released a fix to stop the crashing but you'll need to break and replace all of your poppet shelves since they don't work if they were placed prior to 1.17-7

Thanks alot.
