### ISSUE TITLE
Not compatible with Doggo Mod

### ISSUE THREAD

**Issue by Kurage36** [MoriyaShiine/bewitchment#208]
The mod tweak of wolf, and break Book Of Shadows.
![2021-10-07_22 58 24](https://user-images.githubusercontent.com/92105696/136411135-eaf22e52-8ca4-47ae-b9da-4b04fea10285.png)

**Comment by MoriyaShiine** [comment]
This is unfixable since the Doggo Mod completely replaces the wolf. Any mod will break if it expects the wolf to exist.
