### ISSUE TITLE
magic energy alway not enoug

### ISSUE THREAD

**Issue by barryslol007** [MoriyaShiine/bewitchment#210]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod, do not provide the version of the mod you are using, or are using "latest." "Latest" doesn't mean anything to developers, so please avoid using the term and state the specific version, even if it does happen to be the latest release at the time.

You may delete this text when creating your issue.

**Comment by MoriyaShiine** [comment]
Closed due to invalid issue report

I suspect it's because you're using 1.16 which has a bug on servers; this is fixed on 1.17
