### ISSUE TITLE
I can't summon demon

### ISSUE THREAD

**Issue by barryslol007** [MoriyaShiine/bewitchment#211]
there are alway your source magic not powerful enough but I'm in mutiplayer my mod version are v.1.17-11

**Comment by MoriyaShiine** [comment]
You need altar power to use rituals. Please join the discord for support, not github issues

**Comment by CammiePone** [comment]
Have you considered getting more altar power?

**Comment by barryslol007** [comment]
> You need altar power to use rituals. Please join the discord for support, not github issues

my altar power is 720 but summon need 666

**Comment by CammiePone** [comment]
Join the Discord if you want more help
