### ISSUE TITLE
Werepyre bug

### ISSUE THREAD

**Issue by Superboomya** [MoriyaShiine/bewitchment#213]
I can't be a werepyre for some reason. When I start a new world, curse my self with susceptibility, got a totem of undying, and then nearly died from werepyre while holding totem of undying.

--------------------------------------------------------------------------------------------------------------------------------------------
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: de.aelpecyem.besmirchment.common.entity.WerepyreEntity cannot be cast to net.minecraft.class_1657
Exit Code: -1
--------------------------------------------------------------------------------------------------------------------------------------------
[crash report thing I need.txt](https://github.com/MoriyaShiine/bewitchment/files/7447815/crash.report.thing.I.need.txt)

**Comment by MoriyaShiine** [comment]
Werepyres are not part of Bewitchment, they're part of an addon called Besmirchment

**Comment by Superboomya** [comment]
oh sorry, I though this was the Besmirchment github thing
