### ISSUE TITLE
Origins incompat mixin

### ISSUE THREAD

**Issue by red2blue** [MoriyaShiine/bewitchment#214]
1.17.1
Latest version of Bewitchment and Origins

Getting this warning in console on starting dedicated server

`[20:06:20] [main/WARN]: @Mixin target io.github.apace100.apoli.power.PreventItemUsePower is public in bewitchment.mixins.json:integration.origins.PreventItemUsePowerMixin and should be specified in value`

**Comment by MoriyaShiine** [comment]
I don't see this any more so I'm gonna guess it's fixed lol. It was just a warning anyway and didn't do anything
