### ISSUE TITLE
Wrath negative damage

### ISSUE THREAD

**Issue by Alex-2Pi** [MoriyaShiine/bewitchment#215]
version: v1.17-12
after signing a Wrath contract, the player deals negative damage.
![image](https://user-images.githubusercontent.com/35408350/141514979-cc7f8a80-216e-4923-97ed-4196b6b4ca35.png)

using a coffin and bed, the contract has not ended after more than 7 days

**Comment by MoriyaShiine** [comment]
Sleeping doesn't change the timer at all, but I can look into dealing negative damage when I get home
