### ISSUE TITLE
Ravagers that show up from insanity can permanently damage blocks

### ISSUE THREAD

**Issue by Skeithh** [MoriyaShiine/bewitchment#216]
Using Version 1.17-12, I casted a curse of insanity on myself for funsies and began experiencing the expected effects. Much to my surprise, an insanity-ravager spawned. I wasn't all too worried about this because I found it wasn't real... Except it kind of was as it did permanently damage a large amount of leaf blocks I had around my home, and there was no way for me to stop the ravager from doing said damage.

**Comment by MoriyaShiine** [comment]
It would appear I have missed a mob lol
