### ISSUE TITLE
Origins unable to run commands 

### ISSUE THREAD

**Issue by Illest8** [MoriyaShiine/bewitchment#217]
Bewitchment commands will not run when using the "execute_command" power feature on Origins 1.17.1.

**Comment by MoriyaShiine** [comment]
I'm not sure why this isn't working, I suggest making an issue at https://github.com/apace100/apoli/issues

**Comment by Illest8** [comment]
Ran the command as an MC function instead and still getting an error. I posted the error below: 
https://pastebin.com/zY61p0yR
