### ISSUE TITLE
xaero icon integration, for you.

### ISSUE THREAD

**Issue by Wile64** [MoriyaShiine/bewitchment#218]
Hello,

I create a modpack with xaero and bewitchment (some others too :)) and I have making the xaero icon integration.

I send to you the file, you can add into your mod if you want ;)

[bewitchment.zip](https://github.com/MoriyaShiine/bewitchment/files/7570499/bewitchment.zip)
.

**Comment by MoriyaShiine** [comment]
Thanks! Unfortunately, it looks like some of them don't work and I tried fixing them myself but due to how this mod's models work, I don't think xaero can render it properly.
