### ISSUE TITLE
polymorph potion screwing server up and players

### ISSUE THREAD

**Issue by red2blue** [MoriyaShiine/bewitchment#220]
A player drank a witch brew and got disconnected immediately from the dedicated server. When they joined back, every single player in the server got disconnected. I asked for logs, but there is no crash. they sent me a latest.log, which isn't really helpful. Every time the player who drank the witch brew joins, they get disconnected, along with other players.

1.17.1 
Fabric 0.20.5
Bewitchment Version: 1.17.13 and 1.17.4

https://pastebin.com/t76SuqFs Latest log

**Comment by red2blue** [comment]
[Got a crash log](https://pastebin.com/WYDK1141)

**Comment by red2blue** [comment]
![image](https://user-images.githubusercontent.com/35115304/142708709-04dfd69e-5b5a-457f-b5e7-3f641117ddfe.png)


in case this helps

**Comment by MoriyaShiine** [comment]
Tested this with just Bewitchment installed and nothing happens. Can you try to find what mod causes this?

**Comment by red2blue** [comment]
Was it tested in single player or a server with people on?

**Comment by MoriyaShiine** [comment]
It was 2 people on a dedicated server

**Comment by MoriyaShiine** [comment]
Can you see if this happens using the impersonate command too, or just polymorph potions?

**Comment by MoriyaShiine** [comment]
Still seems to work just fine, but if it's still a problem then I would report it to https://github.com/Ladysnake/Impersonate/issues

**Comment by Micaxs** [comment]
This happens with any mod that changes the player name. Thinks like luckperms, ftbranks, etc.
