### ISSUE TITLE
[Compatibility Request] Alloy Forgery compatibility for Bewitchment ores

### ISSUE THREAD

**Issue by LordDecay26** [MoriyaShiine/bewitchment#221]
I know this says that i cant make suggestions here, but i've been banned / unbanned from the Bewitchment discord like 6 or 7 times now, so im putting this here.
The modpack im working on has Alloy Forgery Installed alongside the latest version of Bewitchment for 1.17. Bewitchment ores cannot be smelted in the Alloy Forge. would be nice if i could smelt my Bewitchment ores in that thing the way i do my vanilla ores.

**Comment by MoriyaShiine** [comment]
I can't really do this without having log spam every world load if you don't have the mod installed, but here's a data pack for it

[bewitchment-alloy_forgery-compat.zip](https://github.com/MoriyaShiine/bewitchment/files/7603919/bewitchment-alloy_forgery-compat.zip)
