### ISSUE TITLE
WitchAltarBlockEntity.scan() makes the server lag a lot.

### ISSUE THREAD

**Issue by khiivl** [MoriyaShiine/bewitchment#222]
Version: 1.17-14
Spark profiler results link: https://spark.lucko.me/JXEA4tmBnJ
Basically, when i put down a carpet on a Witch Altar it makes the tps go up 9000%

**Comment by khiivl** [comment]
Apparently it's caused by the Druid Band

**Comment by serioos** [comment]
I have this problem on my server too. It's fine at first, but then the server is overwhelmed gradually until everything lags out.

**Comment by MoriyaShiine** [comment]
Are you sure you sent the right profile? I don't see Bewitchment in there at all.

**Comment by khiivl** [comment]
> Are you sure you sent the right profile? I don't see Bewitchment in there at all.

my bad, wrong link. https://spark.lucko.me/ltNBOyiADM
there is a lot happening under WitchAltarBlockEntity.scan(), and my tickrate goes to literally 1500% over average if i place a carpet on an altar.

**Comment by MoriyaShiine** [comment]
I can't reproduce this oddly enough, can you send an export of your modpack so I can do testing there?

**Comment by khiivl** [comment]
> I can't reproduce this oddly enough, can you send an export of your modpack so I can do testing there?

i did some further testing, and it appears that the issue only shows up on my server and on my world. this is very strange. 
i uploaded the client and server packs to google drive.
client: https://drive.google.com/file/d/1nGjON4zhGRpL1k1snpiuuuaU0FZ50kDN/view?usp=sharing
server: https://drive.google.com/file/d/1ZGRpzdio5iNJ6TSmzx-gg1O5t-1TEdN1/view?usp=sharing
you can also join my server in the servers list that should be on the client if you want, you're op there

**Comment by khiivl** [comment]
i just updated the server pack (sorry if you already downloaded it..), had to remove already placed altars for convenience of testing.

**Comment by MoriyaShiine** [comment]
All good, I was able to log in just fine lol

**Comment by khiivl** [comment]
![image](https://user-images.githubusercontent.com/73498201/143452591-b9d6238d-06a1-434b-8cfa-1fa5e9e4dab6.png)
this happens again, did you see this on my server? happens only in this place, near my house. tested it on spawn - no luck
