### ISSUE TITLE
Crash on multiplayer - Owl Error

### ISSUE THREAD

**Issue by serioos** [MoriyaShiine/bewitchment#223]
On a multiplayer server, the server closed on its own and crashed with the crash log below.

Fabric Loader: 12.5
Fabric API: 0.42.1
Mod List: https://pastebin.com/mVbHxVkZ
Crash Log: https://pastebin.com/iVLQFKTH

**Comment by MoriyaShiine** [comment]
This doesn't look like a bewitchment problem - something to do with Gourdians? I have no idea what that is but it sounds pumpkin related, do you have any mod like that?

**Comment by DrizzyBo1** [comment]
I'm having the same issues with my server but my server isn't opening after I added some mods to it giving me a minecraft:wolf entity id error can you try and help. I have been trying to find what the name of the mod is and I can't find it is there a workaround for my server?



![Screenshot 2021-11-23 162050](https://user-images.githubusercontent.com/94890780/143131027-ea738d3f-fadb-4b6c-9642-85ab7e2f73cc.png)


if the screenshot doesn't show 

Registry remapping failed: Received ID map for minecraft:entity_ type
contains IDs unknown to the receiver
- minecraft:wolf

**Comment by MoriyaShiine** [comment]
I'm gonna guess you have the doggo mod, which is incompatible with anything that expects wolves to exist

**Comment by DrizzyBo1** [comment]
I was playing with that mod before I'm not sure How I can fix this

**Comment by serioos** [comment]
I don't have any pumpkin related mods. Hmm...maybe the last version of Croptopia? But I don't think it makes any changes to pumpkins.

**Comment by MoriyaShiine** [comment]
Odd. I guess binary search (remove half of your mods until it stops crashing) so you can find what mod does it?

**Comment by serioos** [comment]
I was on version bewitchment-1.17-14 so I switched back to bewitchment-1.17-12. That was the last version that worked fine for me before I updated all the mods, except for the altar causing extreme lag after a while issue. And it's still crashing. I got this crash log:

https://pastebin.com/7uP4z17z

I think it's a mod conflict then. I'll let you know if I find out which mod it is.

**Comment by DrizzyBo1** [comment]
I got my server back up thanks a lot bud

**Comment by MoriyaShiine** [comment]
Yeah I can say with certainty this isn't a bewitchment problem, your new crash report is caused by an axolotl, so some other mod is causing crashes even with vanilla entities. It's expecting everything to be a PlayerEntity, which will obviously not always be true.

**Comment by serioos** [comment]
I found the source of it. It was MC Dungeons Armors 1.8.0 mod. 

https://github.com/chronosacaria/MCDungeonsArmors/issues/26

It is fixed now in its newest update. Thanks for trying to help. <3
