### ISSUE TITLE
wrong tags

### ISSUE THREAD

**Issue by Chuunkyz** [MoriyaShiine/bewitchment#224]
some of tags related to silver and salt are different than those from tech mods, for example the raw silver ore have the c:raw_silvers tag, and it should be c:raw_silver_ores
so be sure to rectify all of them

**Comment by Chuunkyz** [comment]
oh and also, the salt block has no tag at all

**Comment by MoriyaShiine** [comment]
I've added a missing c:salt_blocks item tag (it was in the block tags though), but that's all there is to change. Raw materials are not ores so they should not be added to an ores tag; other mods should be adding to c:raw_silvers/c:raw_leads/etc for consistency's sake.
