### ISSUE TITLE
Launcher crashes on initialize game: could not execute entrypoint stage main due to errors provided by bewitchment

### ISSUE THREAD

**Issue by Taggart1993** [MoriyaShiine/bewitchment#226]
[crash-2021-12-01_13.21.10-client.txt](https://github.com/MoriyaShiine/bewitchment/files/7637630/crash-2021-12-01_13.21.10-client.txt)
Using CurseForge Fabric app.

**Comment by MoriyaShiine** [comment]
Fixed on curseforge (no more commits for 1.17 on github)
