### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bewitchment'!

### ISSUE THREAD

**Issue by bluetrash07** [MoriyaShiine/bewitchment#230]
I have downloaded everything that my friend sent me including the relations of the bewitchment mod. but nothing has worked. please help me.
[
![yuyuh](https://user-images.githubusercontent.com/95667042/144958489-6ebc3a52-12da-440f-94f7-b0048b1c5189.png)
](url)

**Comment by MoriyaShiine** [comment]
I have no idea what version you're using, but make sure you're up to date. Pehkui 3.0.0 removed deprecated stuff so if you're using 1.16 then use Pehkui 3.6.0
