### ISSUE TITLE
Player randomly crashed

### ISSUE THREAD

**Issue by red2blue** [MoriyaShiine/bewitchment#231]
From my modpack, Another Quality Modpack 2 1.18 

Player reported crashing and gave me this log. 

"player left, and rejoined
then server crashed
tried restarting
and when people joined it crashed again
didn't happen a third time tho"

another player crashed; 
![image](https://user-images.githubusercontent.com/35115304/145535407-8d6b008f-77b4-4bfc-a5d3-e4a491af77f2.png)

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/9/21, 2:28 AM
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1293 cannot be cast to class io.github.apace100.apoli.access.HiddenEffectStatus (net.minecraft.class_1293 and io.github.apace100.apoli.access.HiddenEffectStatus are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1e67b872)
	at net.minecraft.entity.LivingEntity.localvar$zec000$modifyStatusEffect(LivingEntity:6645)
	at net.minecraft.entity.LivingEntity.addStatusEffect(LivingEntity)
	at net.minecraft.entity.LivingEntity.addStatusEffect(LivingEntity:937)
	at java.util.HashMap$Values.forEach(HashMap.java:1064)
	at moriyashiine.bewitchment.common.entity.living.WerewolfEntity.tick(WerewolfEntity.java:63)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:696)
	at net.minecraft.world.World.tickEntity(World:487)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:357)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:325)
	at net.minecraft.server.MinecraftServer.redirect$blh000$fixUpdateSuppressionCrashTick(MinecraftServer:6250)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:324)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823)
	at net.minecraft.server.MinecraftServer.handler$beh000$modifiedRunLoop(MinecraftServer:5356)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1309.localvar$zec000$modifyStatusEffect(class_1309.java:6645)
	at net.minecraft.class_1309.method_37222(class_1309.java)
	at net.minecraft.class_1309.method_6092(class_1309.java:937)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1064)
	at moriyashiine.bewitchment.common.entity.living.WerewolfEntity.method_5773(WerewolfEntity.java:63)
	at net.minecraft.class_3218.method_18762(class_3218.java:696)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:357)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:325)
	at net.minecraft.server.MinecraftServer.redirect$blh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:6250)

-- Entity being ticked --
Details:
	Entity Type: bewitchment:werewolf (moriyashiine.bewitchment.common.entity.living.WerewolfEntity)
	Entity ID: 86167
	Entity Name: Berserk Lifesteal Yeeter Alchemist Werewolf
	Entity's Exact location: -49.50, -21.00, -266.50
	Entity's Block location: World: (-50,-21,-267), Section: (at 14,11,5 in -4,-2,-17; chunk contains blocks -64,-64,-272 to -49,319,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,ActiveEffects:[{Ambient:0b,Amplifier:20b,Duration:9999980,Id:21b,ShowIcon:1b,ShowParticles:1b},{Ambient:0b,Amplifier:2b,Duration:999999980,Id:5b,ShowIcon:1b,ShowParticles:1b}],Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:1.0d,Name:"stepheightentityattribute:stepheight"},{Base:0.4d,Name:"minecraft:generic.movement_speed"},{Base:16.0d,Modifiers:[{Amount:-0.04064869258525665d,Name:"Random spawn bonus",Operation:1,UUID:[I;1857437877,-1907275007,-1714009867,-1236967522]}],Name:"minecraft:generic.follow_range"},{Base:15.0d,Modifiers:[{Amount:9.0d,Name:"effect.minecraft.strength 2",Operation:0,UUID:[I;1686990948,1784696665,-1967209790,980277161]}],Name:"minecraft:generic.attack_damage"},{Base:20.0d,Modifiers:[{Amount:84.0d,Name:"effect.minecraft.health_boost 20",Operation:0,UUID:[I;1567558562,294012588,-1198078436,1559140812]}],Name:"minecraft:generic.max_health"}],BalmData:{},Brain:{memories:{}},CanPickUpLoot:0b,CustomName:'{"translate":"Berserk Lifesteal Yeeter Alchemist Werewolf"}',DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:-1s,HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:104.0f,HurtByTimestamp:0,HurtTime:0s,Invulnerable:0b,KubeJSPersistentData:{},LeftHanded:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PersistenceRequired:0b,PortalCooldown:0,Pos:[-49.5d,-21.0d,-266.5d],Rotation:[56.894825f,0.0f],StoredVillager:{AbsorptionAmount:0.0f,Age:0,Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[],BalmData:{},Brain:{memories:{}},CanPickUpLoot:1b,DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:-1s,FoodLevel:0b,ForcedAge:0,Gossips:[],HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:20.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[],Invulnerable:0b,KubeJSPersistentData:{},LastGossipDecay:0L,LastRestock:0L,LeftHanded:0b,Motion:[0.0d,0.0d,0.0d],OnGround:0b,PersistenceRequired:0b,PortalCooldown:0,Pos:[0.0d,0.0d,0.0d],RestocksToday:0,Rotation:[2.9072258f,0.0f],UUID:[I;-762123274,-18659690,-2031657775,-19145923],VillagerData:{level:1,profession:"minecraft:none",type:"minecraft:plains"},Xp:0,arcanus:{DiscombobulatedTimer:0,IsDiscombobulated:0b},cardinal_components:{},checkedIfInLampChunk:0b,cpaCooldown:0,cpadidTP:0b},Tags:["collective-fabric.checked"],UUID:[I;-311001585,-1143847102,-1648931490,-1215575610],Variant:2,arcanus:{DiscombobulatedTimer:0,IsDiscombobulated:0b},cardinal_components:{"apoli:powers":{Powers:[]},"bewitchment:additional_water_data":{Submerged:0b,WetTimer:0},"bewitchment:blood":{Blood:100},"bewitchment:curses":{Curses:[]},"bewitchment:fake_mob":{TargetUUID:""},"bewitchment:familiar":{Familiar:0b},"bewitchment:minion":{MasterUUID:""},"eldritch_mobs:eldritch_modifiers":{eldritch:0b,elite:1b,rank:1b,saved_mods:{alchemist:"alchemist",berserk:"berserk",lifesteal:"lifesteal",yeeter:"yeeter"},ultra:0b},"onsoulfire:on_soul_fire":{OnSoulFire:0b}},checkedIfInLampChunk:1b,cpaCooldown:0,cpadidTP:0b}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:357)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:325)
	at net.minecraft.server.MinecraftServer.redirect$blh000$fixUpdateSuppressionCrashTick(MinecraftServer.java:6250)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$beh000$modifiedRunLoop(MinecraftServer.java:5356)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 4 total; [class_3222['AK8221'/26545, l='ServerLevel[world]', x=130.15, y=143.25, z=-231.38], class_3222['SenkoTheFox'/15580, l='ServerLevel[world]', x=62.30, y=101.00, z=-205.69], class_3222['FluffyDoggo2832'/25671, l='ServerLevel[world]', x=46.63, y=66.00, z=-259.43], class_3222['Flame6969_'/86091, l='ServerLevel[world]', x=-87.69, y=-50.00, z=-175.64]]
	Chunk stats: 3664
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,95,0), Section: (at 0,15,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 322318 game time, 384168 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 3855 (now: false), thunder time: 5659 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$beh000$modifiedRunLoop(MinecraftServer.java:5356)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Linux (amd64) version 5.11.0-41-generic
	Java Version: 17, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 546301752 bytes (520 MiB) / 2036334592 bytes (1942 MiB) up to 2036334592 bytes (1942 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel Core Processor (Haswell, no TSX)
	Identifier: Intel64 Family 6 Model 60 Stepping 1
	Microarchitecture: Haswell (Client)
	Frequency (GHz): -0.00
	Number of physical packages: 4
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: GD 5446
	Graphics card #0 vendor: Cirrus Logic (0x1013)
	Graphics card #0 VRAM (MB): 32.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3881.14
	Virtual memory used (MB): 3372.37
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.0
		additionalbars: Additional Bars 2.2.0
		adorn: Adorn 3.0.0-rc.1+1.18-rc3
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		adventurez: AdventureZ 1.4.5
		ae2: Applied Energistics 2 10.0.0-alpha.3
		agape_space: Space Dimensions 0.4.2
		alloy_forgery: Alloy Forgery 2.0.7+1.18
		animal_feeding_trough: Animal Feeding Trough 1.0.2+1.18
		apoli: Apoli 2.2.0
		appleskin: AppleSkin mc1.18-2.2.0
		aqupdcaracal: Caracal mob 1.18-1.3.4
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
		arcanus: Arcanus 1.24
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.1.45
		balm-fabric: Balm 2.1.1+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		bclib: BCLib 1.0.2
		beehivetooltips: Beehive Tooltips 1.4.0
		beenfo: Beenfo 1.18-fabric0.43.1-1.3.3
		betternether: Better Nether 6.0.2
		bettersleeping: BetterSleeping 0.5.1+1.18
		bewitchment: Bewitchment 1.18-2
		bitsandchisels: BitsAndChisels 2.6.1
		blockus: Blockus 2.3.3+1.18
		blue_endless_jankson: jankson 1.2.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		botania: Botania 1.18-424-FABRIC
		buildinggadgets: st'ructure tools 1.0.6
		calio: Calio 1.4.2
		campchair: Camp Chair 1.0.0
		capybara: Capybara 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-block: Cardinal Components API (blocks) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cardinal-components-item: Cardinal Components API (items) 4.0.0
		cardinal-components-level: Cardinal Components API (world saves) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.56
		carpet-tis-addition: Carpet TIS Addition 1.26.1
		carrier: Carrier 1.9.0
		chalk: Chalk 1.1.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.0.45
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.1
		collective-fabric: Collective (Fabric) 3.13
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		compress: Compress 'em [v1.5]
		concreteconversion: Concrete Conversion 6.1.0.0
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		config2brigadier: Config to Brigadier 1.0.2
		conjuring: Conjuring 1.0.17+1.18
		consistency_plus: Consistency Plus 0.4.2+1.17
		cosmetic-armor: Cosmetic Armor 1.2.0
		craftingtweaks: Crafting Tweaks 13.0.0
		creativeonepunch: Creative One-Punch 1.3
		croptopia: Croptopia 1.7.2
		crowdin-translate: CrowdinTranslate 1.4+1.18
		crusade: Crusade 1.2.5
		culinaire: Culinaire 2.2.0
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		dark-enchanting: Dark Enchanting 0.6.0-1.18
		dawn: Dawn API 3.1.0
		disenchanter: Disenchanter 0.1.3+1.18
		doom: Doom Fabric 4.0.24
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dragonloot: DragonLoot 1.0.9
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		earthtojavamobs: Earth2Java 1.7.4+1.18
		eldritch_mobs: Eldritch Mobs 1.10.1
		elementalcreepers: Elemental Creepers: Refabricated 1.4.0+1.18-pre5
		enchant_giver: Enchant Giver 1.1.0
		endgoblintraders: End Goblin Traders 1.4.2
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		exlineawnings: Exline's Awnings 1.18
		exlinefurniture: Exline's Furniture 1.18
		expandedstorage: Expanded Storage 7.3.2
		extragenerators: Extra Generators 1.1.1-BETA+1.18
		extraorigins: Extra Origins 1.18-1
		ezpas: Ezpas 2.0.0
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d9514
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5514
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricenchantments: Fabric Enchantments 0.6.0
		fabricloader: Fabric Loader 0.12.8
		fabrictailor: Fabric Tailor 1.7.3
		fallingtree: FallingTree 2.15.2
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fireworkfrenzy: Firework Frenzy 1.7
		flan: Flan 1.18-1.6.4
		fluidtank: Fluid Tank 18.0.399-fabric
		forgeconfigapiport: Forge Config API Port 3.0.1
		friendsandfoes: Friends&Foes 1.0.2
		fryingpan: Frying Pan! 2.0.0
		furnacerecycle-fabric: Furnace Recycle (Fabric) 1.0
		geckolib3: Geckolib 3.0.22
		giantspawn-fabric: Giant Spawn (Fabric) 2.7
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.0-1.18
		gobber2: Gobber2 2.5.52
		goblintraders: Goblin Traders 1.4.1
		graveyard: The Graveyard 1.0
		greater_eye: Greater Eye of Ender 1.3.16
		guardiansgalore: GuardiansGalore 1.18-3.0
		hammermod: War-Hammers Mod 1.18
		harvest_scythes: Harvest Scythes 2.3.0
		healthcare: Health Care 1.0.10
		heartbond: Heartbond 1.2.0
		hologram-api: Hologram API 0.2.1+1.18-pre5
		hookshot: Hookshot 23.0
		horseinfo: Horse Info 0.4.0-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		impaled: Impaled 1.0.2
		impersonate: Impersonate 2.4.0
		incantationem: Incantationem 1.1.2+1.18-pre1
		invview: InvView 1.4.7-1.18-rc3+
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		jump: Platformer 1.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kjsextras: KubeJS Extras 1.5.0
		krypton: Krypton 0.1.5
		kubejs: KubeJS 1800.4.0-build.230
		kyrptconfig: Kyrpt Config 1.2.3-1.18
		lank: Lankaster's Origins 1.0.0
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.10.0
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.4-BETA+1.18
		lithium: Lithium 0.7.6-rc1
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magiccombatwands: Magic Combat Wands 1.0.1
		magna: Magna 1.7.0-1.18-pre1
		mambience: MAmbience 3.2.0+1.18
		mavm: More Axolotl Variants Mod 1.0.5
		mcda: MC Dungeons Armors 1.8.2
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdw: MC Dungeons Weapons 3.6.0-1.18
		mcf-reap: MaxVar reap for fabric 1.7.0
		megane: megane 6.1.0
		megane-base: megane-base 6.1.0
		megane-fabric-transfer: megane-fabric-transfer 6.1.0+1.5.4-b4f4f6cda9
		megane-kibe: megane-kibe 6.1.0+1.9.4-BETA-1.18
		megane-lib-block-attributes: megane-lib-block-attributes 6.1.0+0.10.0
		megane-modern-industrialization: megane-modern-industrialization 6.1.0+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.1.0+5.1.0-beta.2
		megane-runtime: megane-runtime 6.1.0
		megane-team-reborn-energy: megane-team-reborn-energy 6.1.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.1.0+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.1.0+1.18
		midnightlib: MidnightLib 0.3.1
		milk_plus: Milk+ 1.3.0
		minecraft: Minecraft 1.18
		mining_dims: Mining Dimensions 1.2.35
		miningutility: Mining Utility 1.2+1.18-pre1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.18
		mocolors: Mo' Colors 1.3.0
		modern_industrialization: Modern Industrialization 1.0.0-alpha.04
		morebannerfeatures: More Banner Features 1.1.2
		morerespawnanchors: More Respawn Anchors 1.0.3
		morevillagers-fabric: MoreVillagersFabric 3.0.0-SNAPSHOT
		mtmechs: Magitek Mechs 1.0.9-rc.2
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		mythic-mounts: Mythic Mounts 4.0
		mythicmetals: Mythic Metals 0.11.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.6
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.18-1
		org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.29
		origins: Origins 1.3.0
		origins-classes: Origins: Classes 1.2.3
		owo: oωo 0.3.8+1.18
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18-60-FABRIC
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		pickupnotifier: Pick Up Notifier 3.0.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		polymer: Polymer 0.2.0-beta.8+1.18
		polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-beta.8+1.18
		puddles: Puddles 1.2.0
		pugh_lib: Pugh Lib 1.2.11
		pugh_tools: Pugh Tools 1.1.13
		puzzleslib: Puzzles Lib 3.0.1
		quarryplus: QuarryPlus 18.0.444
		quartzelv: Quartz Elevator 2.0.0+1.18
		quickshulker: Quick Shulker 1.3.1-1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.3
		redstonebits: Redstone Bits 1.6.0
		repurposed_structures: Repurposed Structures 3.1.6+1.18.0
		resourceful_tools: Resourceful Tools 1.2.26
		respawnablepets: Respawnable Pets 1.18-1
		rhino: Rhino 1800.1.6-build.81
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.0.346
		ruined_equipment: Ruined Equipment 1.4.0
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		sgui: sgui 1.0.0-rc6+1.18-pre5
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		silkspawners: SilkSpawners 1.1.0
		simple_backpack: SimpleBackpack 1.2.24
		simple_shelves: Simple Shelves 1.0.1
		skeletonhorsespawn-fabric: Skeleton Horse Spawn (Fabric) 1.9
		soaringstructures2: Soaring Structures 2 1.18 - 1.9.3
		stacc: Stacc 1.2.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		storagecabinet: Storage Cabinet 1.4.2
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.1.0-beta.3
		teenycoal: Teeny Coal 1.0.3-1.16.x-1.17.x-1.18.x
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0_b0.1.8
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		things: Things 0.2.8+1.18
		thonkutil: ThonkUtil 1.3
		tinyskeletons: Tiny Skeletons 3.0.0
		tolaserblade: ToLaserBlade 1.18-0.4.5.0
		toms_storage: Tom's Simple Storage Mod 1.1.19
		torchbowmod: TorchBowMod 1.0
		trashslot: TrashSlot 11.0.0
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		twigs: Twigs 1.1.0
		universal-graves: Universal Graves 1.2.2+1.18
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.18
		veggie_way: The Veggie Way 1.2.23
		veinmining: Vein Mining 0.0.11-1.18
		villager-hats: Villager Hats Mod 1.2.1
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.3+mc1.18-rc3
		ward_blocks: Ward Blocks 1.2.19
		waystones: Waystones 2.3.2
		wfw: Warhammer Fantasy Weapons 0.1.4-1.18
		wthit: wthit 4.3.1
		xaerominimap: Xaero's Minimap 21.22.3.1
		xaeroworldmap: Xaero's World Map 1.18.6.1
		xlpackets: XLPackets 2.1-1.17.1
		zihlaunchpads: ZIHLaunchpads 1.2.0
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0
	Server Running: true
	Player Count: 4 / 100; [class_3222['AK8221'/26545, l='ServerLevel[world]', x=130.15, y=143.25, z=-231.38], class_3222['SenkoTheFox'/15580, l='ServerLevel[world]', x=62.30, y=101.00, z=-205.69], class_3222['FluffyDoggo2832'/25671, l='ServerLevel[world]', x=46.63, y=66.00, z=-259.43], class_3222['Flame6969_'/86091, l='ServerLevel[world]', x=-87.69, y=-50.00, z=-175.64]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Minecraft (minecraft), Bewitchment (bewitchment)

**Comment by MoriyaShiine** [comment]
This is an issue with Origins/Apoli, fixed in dev but not released yet

**Comment by apace100** [comment]
Fixed in version 1.3.1 of Origins which just released
