### ISSUE TITLE
Bewitchment 1.18

### ISSUE THREAD

**Issue by vfluaitt001** [MoriyaShiine/bewitchment#232]
Has anyone gotten bewitchment 1.18 to work? The Optinfabric 1.12.7 is causing an error and is incompatible with Bewitchment 1.18. Any thoughts?

**Comment by MoriyaShiine** [comment]
Optifine is incompatible with Bewitchment and many other mods, use Sodium/Iris instead

**Comment by vfluaitt001** [comment]
The Optifabric dependency is incompatible with Bewitchment 1.18 but it is on the list of dependencies. If it is in there, the system cannot function. If it is not in there, the game crashes.

**Comment by MoriyaShiine** [comment]
CurseForge's dependencies tab is dumb and doesn't distinguish categories; go to the actual file and you can see the required, optional, and incompatible dependencies

**Comment by vfluaitt001** [comment]
Thank you for that tip. We were able to get rid of the nonsense.

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 12, 2021 at 3:14 PM, ***@***.***> wrote:   


CurseForge's dependencies tab is dumb and doesn't distinguish categories; go to the actual file and you can see the required, optional, and incompatible dependencies

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
