### ISSUE TITLE
Bewitchment / Requiem conflict?

### ISSUE THREAD

**Issue by NoxVerna** [MoriyaShiine/bewitchment#234]
Hi, First attempt at making one of these issues, I was unsure if being an undead mob in the Requiem mod being able to pass through the salt line was supposed to be an unintended feature or was a bug that didn't get a overlook at the time.

**Comment by MoriyaShiine** [comment]
What version are you on? 1.18 doesn't have requiem compability yet

**Comment by NoxVerna** [comment]
Hi, I had been using the 1.18-2 version of Bewitchment, for Requiem i had been using 2.0.0 beta 3.

**Comment by MoriyaShiine** [comment]
Requiem support probably isn't happening in 1.18 so I'm gonna close this for now
