### ISSUE TITLE
juniper doors only have textures on one side

### ISSUE THREAD

**Issue by Reeses-Puffs** [MoriyaShiine/bewitchment#236]
![2021-12-23_20 05 52](https://user-images.githubusercontent.com/73549793/147303694-ea86fd2c-300d-488d-92c0-c477e78bbb25.png)
I am using *bewitchment-1.18-4.jar*
I am not using any rendering mods
I am using a core shader called [Vanilla++](https://github.com/Godlander/vpp)

**Comment by MoriyaShiine** [comment]
Can you get latest.log?

**Comment by Reeses-Puffs** [comment]
[here you go](https://github.com/MoriyaShiine/bewitchment/files/7772029/latest.log)

**Comment by MoriyaShiine** [comment]
Hmm. Does it work without the shader?

**Comment by Reeses-Puffs** [comment]
sorry for the late response, it works fine without the shader

I should probably move this issue over to the V++ repo
