### ISSUE TITLE
vampires spawning all over the place light or darkl

### ISSUE THREAD

**Issue by wackoamd1** [MoriyaShiine/bewitchment#237]
first off i tried going to the discord but all i find are channels that look like help pages .
no general channel or anything just channels that link to this github issues , or faq or whatever .

but my wife is getting hammered by vampires , she lives on the edge of plains and taiga  if that matters , pretty light up but not even 4 iron golems can keep the vampires of her back.
is this a bug or can i tone down the spawnrate or anything to help.

edit: this is on 1.18 -2

**Comment by MoriyaShiine** [comment]
You can change the spawn rate in the config, they shouldn't spawn that frequently though. You also need to read the rules on the discord to get access to the other channels

**Comment by wackoamd1** [comment]
thanks for the update but now its messed up where the config doesnt do anything  ;-)
i "fixed" the previous version by putting the min and max to 0 , and they didnt spawn , now after the update they just spawn no matter what setting iks in the config ;-(
