### ISSUE TITLE
[Bewitchment 1.18-4] Trapped in Fire when teleporting with Cauldrons

### ISSUE THREAD

**Issue by DarianLStephens** [MoriyaShiine/bewitchment#238]
When I teleport using a cauldron, I end up underneath the cauldron, trapped in the fire.

Before teleporting:
![2021-12-30_13 45 20](https://user-images.githubusercontent.com/15375876/147717520-05a1ab36-8c9e-4b3c-8f7f-1d42f259d192.png)
After:
![2021-12-30_13 45 21](https://user-images.githubusercontent.com/15375876/147717526-f42cb7e2-d517-407e-9c23-867de973de3e.png)

The cauldron I was trapped under after teleporting:
![2021-12-30_13 45 40](https://user-images.githubusercontent.com/15375876/147717535-54b61dfb-33c3-42a0-abb3-d60508993b11.png)

**Comment by mathi14811** [comment]
I still have that issue with every cauldron, regardless of what's beneath : flames, campfire or lava.
