### ISSUE TITLE
Bottle of blood not dropping when killing with the athame (1.18.1)

### ISSUE THREAD

**Issue by Jamie787** [MoriyaShiine/bewitchment#241]
Whenever i try to get bottles of blood it doesn't give anything. I've tried putting the bottle in my offhand but it still won't drop. I've tried killing cows, villagers and pillagers but it still wont drop. 

If there is a solution and it isn't a bug please tell.

**Comment by hollyhocc** [comment]
i've experienced this same bug: for some reason, though, it worked when i killed a villager the same way but at night!

**Comment by Jamie787** [comment]
nvm killing them at night totally works

**Comment by MoriyaShiine** [comment]
It's not supposed to only work at night
