### ISSUE TITLE
Can't get some things to work

### ISSUE THREAD

**Issue by TinyGubbins** [MoriyaShiine/bewitchment#242]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod, do not provide the version of the mod you are using, or are using "latest." "Latest" doesn't mean anything to developers, so please avoid using the term and state the specific version, even if it does happen to be the latest release at the time.

You may delete this text when creating your issue.

**Comment by TinyGubbins** [comment]
I'm using All Of Fabric Five 0.2.7 (Bewitched V 1.18-4) and have been getting into bewitchment. Main issue is that any curses I try to use with tag locks don't work. Even though my Alter power is 500+ and I've gotten a demon heart. I place all the items in the brazier but the simple curse never takes effect. I also haven't been able to get my voodoo poppet with a players tag to do anything. If you've got any solutions I'd greatly appreciate it. :)

**Comment by MoriyaShiine** [comment]
Both of those features are disabled in All of Fabric 5; you can enable them in the config (modpackroot/config/bewitchment.json) and remove the entries in disabledPoppets and set enableCurses to true
