### ISSUE TITLE
mob spawning config jank

### ISSUE THREAD

**Issue by wackoamd1** [MoriyaShiine/bewitchment#243]
thanks for trying to fix the spawnrate from my previous issue .
however now i think it disregards the config , cause i "fixed" my issue with the spawns by putting the min and max of vampires and ghost at 0.
now that i updated to 1.18-5 my ghost are spawning no matter the setting in config ;-(

**Comment by MoriyaShiine** [comment]
Try deleting the config and regenerating it, there were 2 config values added that may screw with loading. Nothing else has changed config wise, ghosts in particular haven't been touched

**Comment by wackoamd1** [comment]
strange i just deleted the config and let it regenerate but i dont see any difference between the config of this vesion and the previous version , and still i get ghost ;-( sorry

**Comment by MoriyaShiine** [comment]
Oh, I see the problem; I'm not sure how Minecraft handles 0 min and max spawn weight, you're supposed to set weight to 0. I'll add an extra check
