### ISSUE TITLE
Werewolves throw items and armor out of inv making it very likely that u lose your items on accident

### ISSUE THREAD

**Issue by WanderingCat27** [MoriyaShiine/bewitchment#247]
I started playing as a werewolf and immediately lost my diamond shovel because even though I realized that when I selected tools it would throw it away, It is still very hard not to accidentally select a tool and chuck it. I feel like this way of implementation is very hostile towards player experience. I feel like it would be better if u just made tools unusable ideally or even just move them out of ur hotbar into ur inv above or just out of ur hand anywhere without throwing them. I don't understand a good reason y i could lose tools I worked hard for just because I selected them while wanted to explore a part of this mod.

**Comment by SmallEnderman** [comment]
I understand your issue and concern and allow me to explain it a bit for you, werewolves throw their armor off together with the item they hold, ideally we would have liked to have some sort of invisible inventory where the items (such as your armor) would be put in and the tool would still fall out of your hand, however minecraft makes this a bit difficult to do.

I cannot give you more info/detail on this matter as moriya created it this way and i know its a bit inconvenient to lose your items so suddenly but this is what I can give you

**Comment by WanderingCat27** [comment]
> I understand your issue and concern and allow me to explain it a bit for you, werewolves throw their armor off together with the item they hold, ideally we would have liked to have some sort of invisible inventory where the items (such as your armor) would be put in and the tool would still fall out of your hand, however minecraft makes this a bit difficult to do.
> 
> 
> 
> I cannot give you more info/detail on this matter as moriya created it this way and i know its a bit inconvenient to lose your items so suddenly but this is what I can give you 

I never even thought about an inv but thats good idea, I understand its difficult to implement, but what about a pouch u can craft with maybe 9 slots for tools which gives u 4 armor 5 tools, when u transform armor and tools r placed in there and then otherwise items r thrown as normal? I could try making smth for it if the mod creator is busy? Looping thru the inventory and checking for tool tags like sword axe shovel pic hoe and put them in the pouch starting at the hotbar and moving thru maybe even prioritizing diamond tools. The storage could be similar to botania flower pouch just not picking up items when dropped but can only store tools and armor?

**Comment by MoriyaShiine** [comment]
fixed in https://github.com/MoriyaShiine/bewitchment/commit/b6295bf9d9d99d981be18706eabf4e82a90db57a
