### ISSUE TITLE
not really an issue but im on Mac and I use forge to download mods. I don't know any other way to download mods without forge. there's nothing on YouTube or anything

### ISSUE THREAD

**Issue by helloidk** [MoriyaShiine/bewitchment#248]
Please read before making your issue:

The issue tracker is not the place for suggestions, please join the discord for that.

If your issue fits any of the following criteria, it will be closed without a comment:
-You do not provide a crash report or log if the game crashed.
-Your issue has to do with using the wrong version of or not having a dependency. The fabric loader tells you exactly what you need to do.
-You are using an outdated version of the mod, do not provide the version of the mod you are using, or are using "latest." "Latest" doesn't mean anything to developers, so please avoid using the term and state the specific version, even if it does happen to be the latest release at the time.

You may delete this text when creating your issue.

**Comment by SmallEnderman** [comment]
If i can offer you my support, i can probably help you out with this. I don't know what you're using for downloading mods (just forge and then some mods or a modloader such as curseforge) but assuming that you don't use a modloader, i would highly recommend it. I'll tell you step by step what to do

Step 1. Download curseforge at curseforge.com
Step 2. Install it
Step 3. Once installed open it and search for minecraft in there, once found it will ask you to install it, do that and you get minecraft compatible with curseforge
Step 4. Once installed, you can either browse modpacks and download them, or create your own. For these steps ill tell you how to create your own
Step 5. Somewhere on the top right it should say "create own modpack" or something along those lines. Click that and you will get a pop up
Step 6. Give your modpack a name and select fabric as its modloader, also give it a minecraft version (best would be the latest), once all done click create
Step 7. Click on the modpack you just made, (not the play button but its profile). This will guide you to its profile where you can add mods, you do fhis by clicking "get more content" on the top right of your screen
Step 8. Find bewitchment using the search bar it provides, once found click install and you have installed bewitchment and its dependencies all in one go
Step 9. Go back to the modpacks display thingy and hit play
Step 10. Login using your mojang account and have fun

NOTE you can only do this if you have a minecraft account (premium not cracked or pirated)
