### ISSUE TITLE
Entrypoint 'main' error

### ISSUE THREAD

**Issue by eckseede** [MoriyaShiine/bewitchment#252]
Hello, I am trying to put together a personal mod pack using CurseForge and really wanted to include this mod but I keep coming across this issue of an entrypoint not opening(?) 

Mod Version: 1.16.5-18
Fabric Version: 0.42.0+1.16.jar
Game Verison: 1.16.5

Below is the copied crash report from the Minecraft launcher:

Time: 2/6/22 2:03 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bewitchment'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$3473/510608928.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoSuchFieldError: BASE
		at zabi.minecraft.extraalchemy.compat.pehkui.ModSizeModifiers.registerModifiers(ModSizeModifiers.java:29)
		at zabi.minecraft.extraalchemy.compat.pehkui.PehkuiCompatBridge.init(PehkuiCompatBridge.java:18)
		at zabi.minecraft.extraalchemy.ExtraAlchemy.onInitialize(ExtraAlchemy.java:33)
		at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2663/1559326570.accept(Unknown Source)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
Caused by: java.lang.NoSuchFieldError: WIDTH
	at moriyashiine.bewitchment.common.registry.BWScaleTypes.init(BWScaleTypes.java:24)
	at moriyashiine.bewitchment.common.Bewitchment.onInitialize(Bewitchment.java:220)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2663/1559326570.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$3473/510608928.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1173111784 bytes (1118 MB) / 2185232384 bytes (2084 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		adorn: Adorn 1.14.2+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.6
		alloy_forgery: Alloy Forgery 1.2.0
		appliedenergistics2: Applied Energistics 2 8.4.0-alpha.3
		architectury: Architectury 1.29.51
		arfo: Artificial Foliage 2.6
		arstheurgia: Ars Theurgia 1.0.6
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bannerpp: Banner++ 2.0.3-snapshot+mc.1.16.2-rc1
		below: Below 1.0.0
		besmirchment: Besmirchment 1.16.5-8
		betteranimalsplus: Better Animals Plus 1.16.5-11.0.4
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		bewitchment: Bewitchment 1.16.5-18
		bonappetit: Bon Appétit 0.8.5-3
		byg: BYG 1.3.5
		cardinal-components: Cardinal Components API 2.8.2
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.8.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-util: Cardinal Components API (utilities) 2.8.2
		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.6.59
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.13.49
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		collective-fabric: Collective (Fabric) 4.4
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.5-1.16.5
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		croptopia: Croptopia 1.4.0
		croptosis: Croptosis 1.1.0
		curios: Curios API 0.0.13-1.16.5
		darkpaintings: DarkPaintings 3.0.4
		darkrites: Dark Rites 1.16.5-2
		dynamicfps: Dynamic FPS 2.0.2
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		enchant_giver: Enchant Giver 1.0.3
		enchdesc: EnchantmentDescriptions 2.0.8
		enhancedcelestials: Enhanced Celestials 2.0.6
		entitybanners: Entity Banners 1.0-BETA
		extraalchemy: Extra Alchemy 1.4.5
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.12.12
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.11.5
		farmersdelight: Farmer's Delight 1.16.5-0.0.7
		fasttransferlib: Fast Transfer Lib 0.4.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		frex: FREX 4.5.201
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.3
		golemancy: Golemancy 1.0.1
		graveyard: The Graveyard 1.1
		healthoverlay: Health Overlay 4.0.1
		hoetweaks-fabric: Hoe Tweaks (Fabric) 1.2
		ignis-fatuus: Ignis Fatuus 1.1.3
		impersonate: Impersonate 2.2.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		json-model-extensions: JSON Model Extensions 1.19.172
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.3+1.16.5
		magna: Magna 1.5.1-1.16.5
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.3
		modern_industrialization: Modern Industrialization 0.4.0-alpha.11
		modmenu: Mod Menu 1.16.22
		morevillagers-fabric: MoreVillagersFabric 1.4.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-1.16.5
		mousetweaks: Mouse Tweaks 2.22
		mysticalagriculture: Mystical Agriculture: Refabricated 1.1.7
		mythicmetals: Mythic Metals 0.9.11
		naturescompass: Nature's Compass 1.16.5-2.0.1-fabric
		omega-config: OmegaConfig 1.0.4
		optifabric: OptiFabric 1.12.10
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		patchouli: Patchouli 1.16.4-53-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.2.1
		playerex: PlayerEx 2.0.5
		potiondescriptions: Potion Descriptions fabric-1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		replantingcrops-fabric: Replanting Crops (Fabric) 2.5
		replaymod: Replay Mod 1.16.4-2.6.3
		requiem: Requiem 1.5.1
		requiemapi: Requiem-API 1.5.1
		riverredux: River Redux 0.1.6
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.12.385
		roughlyenoughitems-api: REI (API) 5.12.385
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.385
		roughlyenoughitems-runtime: REI (Runtime) 5.12.385
		roughlyenoughresources: Roughly Enough Resources 2.1.5
		satin: Satin 1.5.1
		seasons: Fabric Seasons 1.2.0.1-BETA+1.16
		somnus: Somnus API 0.0.12-1.16.5
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stylish_occult: Stylish Occult 0.4.0
		supernaturalcrops: Supernatural Crops 2.0.3
		supplementalsustenance: Supplemental Sustenance 1.0.0
		sweet_potato: Sweet Potato Mod 1.3.2+1.16.5
		team_reborn_energy: Energy 0.1.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.16
		tooltipfix: ToolTip Fix 1.0.2-1.16
		trinkets: Trinkets 2.6.7
		veinmining: Vein Mining 0.0.10-1.16.5
		villagernames: Villager Names 1.6.0
		waila: Hwyla 1.9.22
		wands: Building Wands 2.2.7_mc1.16.5
		xaerominimap: Xaero's Minimap 22.1.2
		xaeroworldmap: Xaero's World Map 1.20.1
		xp_storage: XP Storage 1.4+1.16.5
		yigd: You're in Grave Danger 1.0.3
		yungsapi: YUNG's API 1.16.5-Fabric-9
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.12.12-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

-- OptiFabric --
Details:
	OptiFine jar designed for: ~~NULL~~
	OptiFine jar version: ~~NULL~~
	OptiFine jar status: Not found
	OptiFine remapped jar: ~~NULL~~
	OptiFabric error: OptiFabric could not find the Optifine jar in the mods folder:
C:\Users\user\curseforge\minecraft\Instances\My Modpack\mods 

this probably tells me what to do but I don't really understand what this report is telling me in the first place. I just know that something with the mod is stopping the game from launching.

Any help would be greatly appreciated.

**Comment by MoriyaShiine** [comment]
Clone of #229, but I highly suggest updating; the 1.16 version of Bewitchment has a multiplayer bug that makes your internal magic bar unusable most of the time
