### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by TheCodingKitsune** [MoriyaShiine/bewitchment#254]
I made a mod pack with 1.16.5 bewitchment and everytime I try to load it, it says It could could not execute entrypoint stage 'main' due to errors, provided by 'bewitchment' Attached is the full crash log

[crash-2022-02-10_09.31.41-client.txt](https://github.com/MoriyaShiine/bewitchment/files/8039436/crash-2022-02-10_09.31.41-client.txt)

**Comment by MoriyaShiine** [comment]
Clone of #229
