### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hallo123492** [MoriyaShiine/bewitchment#255]
Bug

You may delete this text when creating your issue.
[crash-2022-02-21_21.47.38-client.txt](https://github.com/MoriyaShiine/bewitchment/files/8112006/crash-2022-02-21_21.47.38-client.txt)

**Comment by MoriyaShiine** [comment]
Clone of #229

**Comment by hallo123492** [comment]
I installed all of this using the curse launcher
this is also not a clone

also lies again in the fabic api

![Screenshot 2022-02-21 220737](https://user-images.githubusercontent.com/98216922/155026495-acf3c9a8-fd3a-4c76-ac9a-111dc7f42851.png)

**Comment by CammiePone** [comment]
Downgrade Pehkui, like the referenced issue says. It's literally the same crash.

**Comment by hallo123492** [comment]
sorry for the lateness of the night had too little time the mod is incompatible with the lame not fabic 0.13.0 even the api the new 0.42.1 will also be incompatible with the
