### ISSUE TITLE
Client crash on schematic save

### ISSUE THREAD

**Issue by mrsterner** [MoriyaShiine/bewitchment#256]
Steps to reproduce:
1. Place Poppetshelf
2. Save poppetshelf with schematic and quil from Create
3. Crash

Mods:
bewitchment-1.18-13
create-mc1.18.1_v0.4d+408

Crashlog:
[crash-2022-02-23_01.00.55-client.txt](https://github.com/MoriyaShiine/bewitchment/files/8120988/crash-2022-02-23_01.00.55-client.txt)

`Caused by: java.lang.ClassCastException: class net.minecraft.ClientWorld cannot be cast to class net.minecraft.ServerWorld (net.minecraft.ClientWorld and net.minecraft.ServerWorld are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @26be92ad)
	at moriyashiine.bewitchment.common.world.BWWorldState.get(BWWorldState.java:110) ~[bewitchment-1.18-13.jar:?]
	at moriyashiine.bewitchment.common.block.entity.PoppetShelfBlockEntity.method_11007(PoppetShelfBlockEntity.java:83) ~[bewitchment-1.18-13.jar:?]`

**Comment by itsdinkd** [comment]
How did this person get create, a forge mod, to work with bewitchment, a fabric mod?

**Comment by MoriyaShiine** [comment]
Create is also on fabric, we are using it in the official discord modpack
