### ISSUE TITLE
Book of Shadows won't load entries

### ISSUE THREAD

**Issue by BinxetyBinx** [MoriyaShiine/bewitchment#257]
Currently using the latest version of the mod 1.18-14 on Another Quality Modpack2 server. The book of shadows is currently not functioning at all.

Here is the error the book shows as well as the entry from latest.log.
![Untitled1](https://user-images.githubusercontent.com/47510715/155825551-531908cb-5eb0-4fa5-96e6-99d721c50471.png)
[Book of shadows.txt](https://github.com/MoriyaShiine/bewitchment/files/8145717/Book.of.shadows.txt)

**Comment by itsdinkd** [comment]
> 

Hello, Aqm2 creator here. I am not overwriting anything in the bewitchment book.

**Comment by MoriyaShiine** [comment]
Hmm, odd. I know it definitely isn't caused by bewitchment alone. Try removing mods until it stops? Once we figure out what it is, it can be reported to the relevant mod.

**Comment by MoriyaShiine** [comment]
The given log doesn't say much so I'd appreciate the full version

**Comment by BinxetyBinx** [comment]
Full log
[latest (1).log](https://github.com/MoriyaShiine/bewitchment/files/8146680/latest.1.log)

**Comment by MoriyaShiine** [comment]
Thanks

I still don't see why this would happen, however I can also see the judgment poppet is missing its recipe, along with a myriad of other items from a variety of different mods. Something went very wrong here unrelated to bewitchment (even some packets are failing to register) so I would suggest the binary search method (remove half of your mods until it starts working, then start adding back until you find which it was)

**Comment by itsdinkd** [comment]
All the items that say missing are intentional Moriya, that happens when you have kubejs logging and disable items on.

**Comment by itsdinkd** [comment]
Would it be possible that its due to not using the latest Patchouli? I don't understand much about it, but it looks like the latest added support for 
![image](https://user-images.githubusercontent.com/35115304/155853841-730154b7-c615-41ef-95bc-8315c9081b33.png)


And looking at the page in question, it uses ${1...)
![image](https://user-images.githubusercontent.com/35115304/155853851-86ab1a67-1976-4333-a796-7900a323c2f5.png)

**Comment by itsdinkd** [comment]
We're using -64

**Comment by MoriyaShiine** [comment]
Ah. Maybe try updating? I don't think it would change much but it's worth a shot

**Comment by itsdinkd** [comment]
Ah nevermind. that was AQM3 i was looking at, AQM2 does indeed use the latest.

**Comment by itsdinkd** [comment]
Figured it out. It was because I ran a recipe change using KubeJS on heaven extract apparently... 

```js

onEvent('recipes', function(event) {
	event.remove({output: "bewitchment:heaven_extract" })
	event.custom({
  "type": "bewitchment:oil_recipe",
  "ingredients": [
	{
	  "item": "bewitchment:juniper_bark"
	},
	{
	  "item": "magicfungi:impetus_essence"
	},
	{
	  "item": "bewitchment:mandrake_root"
	}
  ],
  "result": {
	"item": "bewitchment:heaven_extract"
  },
  "color": 16777215
});
});


```

**Comment by itsdinkd** [comment]
Do you know why this occurred by modifying the recipe? I've modified a bunch of recipes using KubeJS from mods that have patchouli guides, even items that are showing recipes in their book that I modified.
