### ISSUE TITLE
greed does not drop gold

### ISSUE THREAD

**Issue by WanderingCat27** [MoriyaShiine/bewitchment#259]
bewitchment-1.18-10.jar

https://drive.google.com/file/d/1RH0dgG6K3fsGnc-UC3i8sLmSCixgZnOp/view?usp=sharing

(sorry for brevity it is 1 am)

**Comment by MoriyaShiine** [comment]
Seems to work fine for me. Do you have anything overwriting the loot table?

**Comment by WanderingCat27** [comment]
> Seems to work fine for me. Do you have anything overwriting the loot table?

not that i know of, i can test in singleplayer and then with only bewitchment see if either yields diff results

**Comment by MoriyaShiine** [comment]
I'm unable to reproduce this, if you figure out what causes it then you can reopen the issue

**Comment by WanderingCat27** [comment]
> I'm unable to reproduce this, if you figure out what causes it then you can reopen the issue

oops sorry forgot to respond yea it just seems to work now? not sure what happened but its not broken anymore

**Comment by MoriyaShiine** [comment]
thocc
