### ISSUE TITLE
Pledging to Lilith or Herne does not work.

### ISSUE THREAD

**Issue by KamiSami** [MoriyaShiine/bewitchment#260]
Title pretty much, happens with both of them, i felt like losing my mind after several attempts with Herne originally, but after going to creative and testing this out, it still didn't work even i directly looked at them... Im surprised there's no reports here in github about this. I tried without most of my mods too, only ones i have as of current are:

architectury-3.6.17
bewitchment-1.18-14
cloth-config-6.2.57-fabric
fabric-api-0.46.4+1.18
InventoryHUD-fabric-[1.18] -3.4.2
MouseTweaks-fabric-mc1.18-2.22
Patchouli-1.18.1-65-FABRIC
Pehkui-3.1.0+1.14.4-1.18.1
polymorph-fabric-0.0.19-1.18.1
RoughlyEnoughItems-7.3.428
torohealth-1.18-fabric-2
trinkets-3.2.0
Xaeros_Minimap_22.1.0_Fabric_1.18
XaerosWorldMap_1.20.0_Fabric_1.18

...Also a something to mention, pledging with Baphomet at least worked, or at least it doesn't attack me and offers trading. Herne and Lilith though, do nothing. Can't transform at will to bat or werewolf. Checked server logs too, nothing indicating anything either. This "should" be reproduceable since i tried this so many times now...

**Comment by MoriyaShiine** [comment]
Did you make sure to unpledge from Baphomet? You can only have one pledge at a time

**Comment by KamiSami** [comment]
One at a time? Oh, that might explain it...  Does the book of shadows mention about of this on some page? I don't remember reading or knowing this at least till now.  I could try punch or kill (if i can lol) Baphomet and try pledge Herne again and see what happens. Gonna try that now. It may very likely be exactly why I couldn't pledge to Herne or Lilith in first place, but just in case, I will try it now and let you know what happens.

**Comment by KamiSami** [comment]
Yeah that indeed seemed to be the case... :/ Sorry for the inconvenience if this may've caused some! Feel free to close this, i don't know for sure if book has entry about pledging only one at a time which is only reason im leaving this open for you now, if it does, you can certainly close this.

**Comment by MoriyaShiine** [comment]
Don't worry about any inconvenience, that's what issue reports are for after all :)

The book doesn't mention that only one pledge at a time works so that's been added, thanks!
