### ISSUE TITLE
Teleporting in a cauldron freezes the server for a solid 6-10 seconds

### ISSUE THREAD

**Issue by WanderingCat27** [MoriyaShiine/bewitchment#261]
For a while my server has been having sudden lag spikes and after finally understanding how spark's only-ticks-over used ms not ticks, I was able to diagnose that the issue is when people use cauldrons to teleport

Version: bewitchment-1.18-14.jar

Spark traceback: https://spark.lucko.me/9a3xqRty0K (in case ur unfamiliar, it is easiest if u got to the top and switch the mode from all to sources, its the button with the eye on it)

**Comment by WanderingCat27** [comment]
if the profiler link is not working, i also saved the spark profiler as a file

**Comment by MoriyaShiine** [comment]
Fixed, but cauldrons will lose their name. Just add a new name tag and all is good :)

**Comment by WanderingCat27** [comment]
> Fixed, but cauldrons will lose their name. Just add a new name tag and all is good :)

ty sir!
