### ISSUE TITLE
MCA not compatible with Bewitchment

### ISSUE THREAD

**Issue by MrBossss** [MoriyaShiine/bewitchment#262]
This is not a bug but it dose stop you from being to like summon a demon and become a lich and the other stuff that needs you to kill a villager [i can't remember everything sorry]

heres the mod link https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn

Im using 
bewitchment-1.18-15.jar of the mod

**Comment by MoriyaShiine** [comment]
Closed as of https://github.com/Luke100000/minecraft-comes-alive/issues/109
