### ISSUE TITLE
Game crashes upon placing lectern

### ISSUE THREAD

**Issue by TranquilStar** [MoriyaShiine/bewitchment#268]
Whenever placing a lectern the game crashes and corrupts the world, I am using the 1.18.2 version
1.18.2-16 to be exact, thought it was just a 1.18.1 issue but it was not, it happens in both 1.18.2 and 1.18.1 for me
I use the 1.18.1 version because some mods are still not updated to 1.18.2

tried reading the log but I don't see what is causing it, your mod is the only mod installed plus dependencies 

the mod itself works fine but not when trying to place/use a lectern

[crash-2022-03-23_23.05.26-client.txt](https://github.com/MoriyaShiine/bewitchment/files/8338098/crash-2022-03-23_23.05.26-client.txt)

**Comment by TranquilStar** [comment]
also I am fairly certain upon going into a area/chunk with a lectern the game crashes as well but it luckily doesn't corrupt the world,
however I lost 20 hours of progress from this bug/issue and it didn't make me very happy

**Comment by MoriyaShiine** [comment]
Could you also open an issue at https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues?

**Comment by TranquilStar** [comment]
> Could you also open an issue at https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues?

yes I will go ahead

**Comment by TranquilStar** [comment]
what info do I give them myself, the same as what I gave here?
