### ISSUE TITLE
ME meter not rendering with RPG-Hud

### ISSUE THREAD

**Issue by OuroborosBoy** [MoriyaShiine/bewitchment#269]
In bewitchment1.18-15, the ME meter doesn't render if the player has RPG-Hud installed, regardless of if the new HUD elements from RPG-Hud are turned on or not. I'm not sure if this is an issue on Bewitchment's end or RPG-Hud's

**Comment by MoriyaShiine** [comment]
It looks like this mod has an effective @Overwrite for renderStatusBars, meaning it'll break anything that does stuff here, not just Bewitchment. I would make a report there instead.

https://github.com/KurodaAkira/RPG-Hud/blob/daeeb3cef76b0f4f98778fab977eaf4b7d5990c9/src/main/java/net/spellcraftgaming/rpghud/mixin/RenderOverlayMixin.java#L40
https://github.com/KurodaAkira/RPG-Hud/blob/daeeb3cef76b0f4f98778fab977eaf4b7d5990c9/src/main/java/net/spellcraftgaming/rpghud/mixin/RenderOverlayMixin.java#L231
