### ISSUE TITLE
crashing when using multiple mods

### ISSUE THREAD

**Issue by LevelNaomi** [MoriyaShiine/bewitchment#271]
i was using multiple mods it crashed, heres the log (i know for a fact it's not adorn, when i added it it started crashing)
[crash-2022-03-25_17.11.29-client.txt](https://github.com/MoriyaShiine/bewitchment/files/8353652/crash-2022-03-25_17.11.29-client.txt)
)

**Comment by MoriyaShiine** [comment]
Nothing here indicates it's Bewitchment, and if it is, 1.16 is unsupported

**Comment by LevelNaomi** [comment]
> Nothing here indicates it's Bewitchment, and if it is, 1.16 is unsupported

thanks, also i know because i removed it, worked, added it, not worked, if i'm just dumb then ok
