### ISSUE TITLE
Crashes upon attempting to generate lecterns in villages 1.18.1 & 1.18.2

### ISSUE THREAD

**Issue by 80Holes** [MoriyaShiine/bewitchment#272]
The 3 files below are from superflat worlds in Minecraft 1.18.1
Fabric 0.13.3
Fabric API 0.46.6
Bewitchment 1.18-15
Not Enough Crashes: 4.1.4
Patchouli 1.18.1-65
Pehkui 3.2.0
Trinkets 3.2.0

[crash-2022-03-26_12.55.52-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355926/crash-2022-03-26_12.55.52-server.txt)
[crash-2022-03-26_12.58.57-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355927/crash-2022-03-26_12.58.57-server.txt)
[crash-2022-03-26_12.54.55-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355928/crash-2022-03-26_12.54.55-server.txt)

This following logs are from a superflat world in Minecraft 1.18.2
Fabric 0.13.3
One crash was also caused by the placement of a lectern, that log was lost.
Fabric API 0.48.0
Bewitchment 1.18-16
Not Enough Crashes: 4.1.4
Patchouli 1.18.1-66
Pehkui 3.2.0
Trinkets 3.3.0

[latest.log](https://github.com/MoriyaShiine/bewitchment/files/8355941/latest.log)
[latest.log](https://github.com/MoriyaShiine/bewitchment/files/8355954/latest.log)
[crash-2022-03-26_13.15.15-client.txt](https://github.com/MoriyaShiine/bewitchment/files/8355955/crash-2022-03-26_13.15.15-client.txt)

And these are the reports from the process of isolating the  problem mod (1.18.1)
[crash-2022-03-26_11.45.29-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355960/crash-2022-03-26_11.45.29-server.txt)
[crash-2022-03-26_12.17.19-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355961/crash-2022-03-26_12.17.19-server.txt)
[crash-2022-03-26_12.36.31-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355962/crash-2022-03-26_12.36.31-server.txt)
[crash-2022-03-26_12.40.34-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355963/crash-2022-03-26_12.40.34-server.txt)
[crash-2022-03-26_12.48.07-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355964/crash-2022-03-26_12.48.07-server.txt)
[crash-2022-03-26_10.52.58-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355965/crash-2022-03-26_10.52.58-server.txt)
[crash-2022-03-26_11.15.52-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8355966/crash-2022-03-26_11.15.52-server.txt)

**Comment by MoriyaShiine** [comment]
clone of #268
