### ISSUE TITLE
Repeated entity ticking crashes

### ISSUE THREAD

**Issue by Finn900mc** [MoriyaShiine/bewitchment#274]
A ticking entity error occurs and crashes the server when chunk is loaded in. It is possible to delete them and fix the server but it happens every other hour. I think it has to do with a bewitchment NBT tags.

crash report: [crash-2022-03-27_23.31.53-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8359735/crash-2022-03-27_23.31.53-server.txt)

**Comment by MoriyaShiine** [comment]
clone of #268
