### ISSUE TITLE
Lich ritual not functional

### ISSUE THREAD

**Issue by WPeanuts** [MoriyaShiine/bewitchment#275]
The book states that, "Starting this ritual requires the lack of a soul, or in short terms, having the Apathy curse." it also states that "it will also require the sacrifice of a demonic entity." after setting the apathy curse up in the brazier, and then using at first a demon, but after several failed attempts I switched to greater demons (with no success)

**Comment by MoriyaShiine** [comment]
Liches are not part of Bewitchment, they are added by https://github.com/BloomhouseMC/Besmirchment
