### ISSUE TITLE
Incompatible mod set patchouli version 1.18.2-66 or later required but is installed

### ISSUE THREAD

**Issue by Konglomneshued** [MoriyaShiine/bewitchment#276]
Please read before making your issue:
Can't launch the game because it's telling me patchouli is not installed when I have 2 freaking versions, 66 and 67 (tried them both) and still telling me I don't have it.

It's making me angry.
![2](https://user-images.githubusercontent.com/94726665/163731343-f681c01b-2059-4652-82df-2f53882f91da.png)
![1](https://user-images.githubusercontent.com/94726665/163731347-df8437d6-58ca-4b62-9619-423d390f6bf0.png)

**Comment by MoriyaShiine** [comment]
Install patchouli fabric, not forge
