### ISSUE TITLE
Server crash when attempting to trade with demon

### ISSUE THREAD

**Issue by Atteecus** [MoriyaShiine/bewitchment#277]
[crash-2022-04-20_18.55.03-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8525933/crash-2022-04-20_18.55.03-server.txt)
 
When wearing the besmirched attire and right clicking on the regular demon the entire server crashes. I am not good with computer lingo so I can't tell based off the log if it is a mod compatibility thing or not. I am running the most up to date mod on the server and client.

**Comment by Atteecus** [comment]
1.18.2*

**Comment by Atteecus** [comment]
Not the trade gui, the contract gui I meant.  I tested in single player and it works.

**Comment by MoriyaShiine** [comment]
I have no idea what would cause this but it's not base Bewitchment; try removing half of your mods until it stops crashing, and then add them back one at a time until it does to narrow it down

**Comment by Atteecus** [comment]
Okay thank you!

**Comment by SticcyGem** [comment]
I'm also experiencing the same issue with only bewitchment and its dependency on a fresh new world on the server. Fabric, bewitchment, and its dependency are all fully updated to the latest version for 1.18.2
[crash-2022-04-25_05.07.05-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8551790/crash-2022-04-25_05.07.05-server.txt)
.
