### ISSUE TITLE
Server refuses to load when mod is installed.

### ISSUE THREAD

**Issue by Verbina29** [MoriyaShiine/bewitchment#28]
Here's the server log. The only mods on the server are Bewitchment, Cloth Config, Fabric API, Impersonate, Patchouli, Pehkui, and Trinkets. So, just Bewitchment and its dependencies.
[latest.log](https://github.com/MoriyaShiine/bewitchment/files/6040830/latest.log)

**Comment by Sunconure11** [comment]
@MoriyaShiine I think you messed up some client-sided stuff

**Comment by Aelpecyem** [comment]
What's your loader version? Are you using latest?

Additionally, @Sunconure11 tagging someone in an issue they get auto-tagged by is trivial, so don't.

**Comment by Verbina29** [comment]
I believe I am using the latest version of Fabric Loader, I'm using 0.11.2.
