### ISSUE TITLE
Ghost Death Bug

### ISSUE THREAD

**Issue by OzaKahuu** [MoriyaShiine/bewitchment#282]
### Mod version

v.1.18-19

### A description of the issue

I'm using the chest cavity mod along with the origin's and Origin's classes mods and I'm suffering a Game breaking bug where if i take damage or die the a high likely hood of me being stuck in a state where my hearts instantly go to zero <Possibly in the negative> and my screen tilts and starts jittering to the upright and tilted position and I can still move around like I am alive but I can't open my inventory for more than a second and mobs ignore me and I can't die and it won't give me the death screen so I can't respawn and the 2 times it happened a ghost was nearby so I believe that something is going on with the ghost that's breaking my game and the Bug is SO BAD that no matter what I did to fix it through commands </Kill, Insta health's, regen and death totems> I couldn't salvage my save so I forced to make a new world on the same seed

Also, I'm using the fabric version on curse forge

**Comment by OzaKahuu** [comment]
I did further test and bewitchment was not the cause of the glitch, it was the chest cavity mod after I had replaced my spine with an ender man spine and took damage sorry for assuming

**Comment by MoriyaShiine** [comment]
No worries
