### ISSUE TITLE
Feature placement

### ISSUE THREAD

**Issue by TheButterbrotMan** [MoriyaShiine/bewitchment#283]
### Mod version

1.18-20

### A description of the issue

I started my server and this error occured.

### Log or crash report

https://bytebin.lucko.me/qHLzQonJIU

**Comment by MoriyaShiine** [comment]
Does this happen with just Bewitchment and/or is it consistent? I don't do anything special when registering ores, just the vanilla way. I don't think I can do anything about this, but my guess is either some mod that touches world gen or just a one-off bug
