### ISSUE TITLE
Server Crash Log

### ISSUE THREAD

**Issue by Kuyuna** [MoriyaShiine/bewitchment#285]
### Mod version

1.18-20

### A description of the issue

Hi! Server crashed so here is the crashlog. Nothing suspicious happened or anything. If there are questions please ask me. :)

[crash-2022-05-28_20.12.53-server.txt](https://github.com/MoriyaShiine/bewitchment/files/8791837/crash-2022-05-28_20.12.53-server.txt)

### Log or crash report

https://gist.github.com/Kuyuna/0cf494ee9a3be9725d4cab556de8e869#file-crash-2022-05-28_20-12-53-server-txt

**Comment by MoriyaShiine** [comment]
Croparia seems to expect the same age value on all plants; this is not something I can fix myself and will break with all other mods that use a different age property. This can be fixed on their end by searching CropBlock#getAgeProperty() instead of what I assume to be a hardcoded check
