### ISSUE TITLE
Unpledging to Herne every time I rejoin world

### ISSUE THREAD

**Issue by Spadefly** [MoriyaShiine/bewitchment#287]
### Mod version

1.18.2

### A description of the issue

Every time I re-log onto the server I play on I lose the ability to transform on command that I gained from pledging to Herne. Only reporting it now that it's happened twice.

### Log or crash report

N/A

**Comment by MoriyaShiine** [comment]
Please provide an actual version, 1.18.2 means nothing. Does this happen with just Bewitchment? Send a log too please

**Comment by Spadefly** [comment]
Mod version is 1.18-20, The server I'm in is running AOF5 with no bewitchment addons besides Haema, and the server isn't mine so I'm unsure how to pull the logs

**Comment by MoriyaShiine** [comment]
Can you ask the owner for logs? I cannot reproduce this
