### ISSUE TITLE
Ticking entity I java.lang.ClassCastException

### ISSUE THREAD

**Issue by TheButterbrotMan** [MoriyaShiine/bewitchment#288]
### Mod version

Bewitchment 1.18-20

### A description of the issue

Server crashed tonight multiple times with this crashlog. Dont have any details.

### Log or crash report

https://bytebin.lucko.me/WG3jhE03vq

**Comment by MoriyaShiine** [comment]
This can't be Bewitchment, I don't have any mixins into TridentEntity
