### ISSUE TITLE
[SUGGESTION] add a way to blacklist curses

### ISSUE THREAD

**Issue by Sebas-Re** [MoriyaShiine/bewitchment#290]
### Mod version

bewitchment-1.18-20

### A description of the issue

I would like to suggest a way to blacklist curses. We have curses disabled on our servers to avoid new players being abused with vodoo dolls and stuff, but now people can't curse themselves

If you disable curses, players can't curse themselves to become Werewolves or vampires

**Comment by MoriyaShiine** [comment]
You don't need the curse to transform if it's disabled

**Comment by itsdinkd** [comment]
Another quality modpack creator here. I would really appreciate this addition to bewitchments config. Disabling all the curses, disables players from becoming a vampire or werewolf, which is something I definitely do not want disabled, but i'd love for the other curses to be disabled.

**Comment by itsdinkd** [comment]
> 

How do they transform then?

**Comment by Sebas-Re** [comment]
> You don't need the curse to transform if it's disabled

could you please tell me how to transform then? I couldn't find a way to do so

**Comment by itsdinkd** [comment]
> You don't need the curse to transform if it's disabled

How do they transform then with curses disabled?

**Comment by MoriyaShiine** [comment]
The same process but without needing the susceptibility curse

**Comment by Sebas-Re** [comment]
thanks a lot!
