### ISSUE TITLE
Question Advancements

### ISSUE THREAD

**Issue by Gamerbolts** [MoriyaShiine/bewitchment#292]
### Mod version

1.18-20

### A description of the issue

I was just wondering if Bewitchment is supposed to have a tab in the Advancements? I am making a modpack so did the command to give me all advancements but I do not see Bewitchment in the advancements tab.

**Comment by MoriyaShiine** [comment]
It doesn't have one

Please use the issue tracker for bug reports, questions are best for the discord server
