### ISSUE TITLE
1.18.2 Fabric crash Werewolf

### ISSUE THREAD

**Issue by Gamerbolts** [MoriyaShiine/bewitchment#294]
### Mod version

1.18-22

### A description of the issue

Hello! I am having an issue. I loaded my modpack world and had it running for a few minutes and then it crashed. I checked the crash report and it said something about the werewolf from bewitchment being the cause. I don't know for sure but wanted to post it here for you to look at just in case. Any help is greatly appreciated. Thank you!

### Log or crash report

https://gist.github.com/Gamerbolts/53a77bbd16860fd63de197eb75f5b161

**Comment by Gamerbolts** [comment]
Yep I will do that and see if I can pinpoint the mod. Thanks!

**Comment by Gamerbolts** [comment]
I removed bewitchment and besmirchment, tried again and it work fine, no crashing. Then I readded them back in tried again and it worked... This is a very illusive crash apparently.

**Comment by MoriyaShiine** [comment]
Gonna close this since I don't think I can do anything and it only happened once
