### ISSUE TITLE
Curses stuck on fire animation, without smoke

### ISSUE THREAD

**Issue by lllamma** [MoriyaShiine/bewitchment#295]
### Mod version

1.18-22

### A description of the issue

When using the brazier to cast any curse on sever or s/c single player:
You can place all items in the brazier and light it with the flint and steel. Instead of rejecting components because of lack of ME, or placing the curse and spitting out a glass bottle. It gets stuck on the flame animation. You can take the items out. 

I am using 1.18-22 in the AOF5 modpack. Someone else on the wiki seems to be having the same problem (also using AOF5)

If you could help with this issue that would be great.
Thank you

**Comment by MoriyaShiine** [comment]
Curses are disabled in All of Fabric; you can re-enable them in the mod config
