### ISSUE TITLE
1.18.1 summon raven breaks the world

### ISSUE THREAD

**Issue by Nidoskull** [MoriyaShiine/bewitchment#299]
### Mod version

Discovered on 1.18-15, does not appear to exist on 1.19-1?

### A description of the issue

When running the command /summon bewitchment:raven ~ ~ ~ {Variant:0}, which should spawn a 'shiny' raven, the world becomes "corrupted" (not sure what else to call it), crashing the game and making the world unjoinable. 
Not sure what exactly caused the crash, it appears to be a rendering issue? 

### Log or crash report

https://gist.github.com/Nidoskull/466dbc0cb10f5a8e9363950125039e2e

**Comment by MoriyaShiine** [comment]
Yeah doesn't seem to happen on 1.19-1

Maybe some other mod might be messing with it but I don't update old version, if it happens again then ask on discord and maybe we can find out what mod causes it
