### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Mysteriaa** [MoriyaShiine/bewitchment#30]
Opening the game with Bewitchment installed triggers a crash. Here's the crashlog: https://paste.atlauncher.com/view/b3438a6b

**Comment by MoriyaShiine** [comment]
Can you get a report without NotEnoughCrashes?

**Comment by Mysteriaa** [comment]
> 
> 
> Can you get a report without NotEnoughCrashes?

Here: https://paste.atlauncher.com/view/219d06a5

**Comment by MoriyaShiine** [comment]
clone of #29
