### ISSUE TITLE
Crash on when trying to start with Bewitchment installed. (1.19)

### ISSUE THREAD

**Issue by MrRagtime** [MoriyaShiine/bewitchment#300]
### Mod version

bewitchment-1.19-1 https://www.curseforge.com/minecraft/mc-mods/bewitchment/files/3862178

### A description of the issue

Every time I boot up Minecraft 1.19 with Bewitchment, my game crashes

The error below is what I believe is causing my game to crash: 
### Log or crash report

https://gist.github.com/MrRagtime/4ff8cb45453e243d72b4cf09bf296a14

**Comment by MoriyaShiine** [comment]
Update tooltipplus, the version you have overwrites a method so any mod that mixins into that method will crash; this seems to already be fixed on their end
