### ISSUE TITLE
Current Crash on Player Logging in

### ISSUE THREAD

**Issue by Echo0w0** [MoriyaShiine/bewitchment#301]
### Mod version

bewitchment-1.19-1.jar

### A description of the issue

Not too sure why bewitchment is causing this, but whenever someone tries to log into my server with bewitchment they can log in their first time perfectly fine but if they ever relog then the server just does a constant server ticking crash. The bug is fixed upon deleting the usercache.json but if the file exists then the crash happens. 

### Log or crash report

https://gist.github.com/Echo0w0/31b93cc0a9e4dfbbda817b5a2b4d91de

**Comment by MoriyaShiine** [comment]
Try installing https://www.curseforge.com/minecraft/mc-mods/advancements-debug, this looks like a vanilla bug

**Comment by Echo0w0** [comment]
Thank You! It was the advancements, literally saving my throat after 9 hours of trying to fix my stuff
