### ISSUE TITLE
Infinitely lasting demon contract

### ISSUE THREAD

**Issue by cnclt** [MoriyaShiine/bewitchment#302]
### Mod version

bewitchment-1.18-20.jar

### A description of the issue

I know that there is a warning that unless the bug still exists on the latest version, it will not be fixed so I was hoping I could get advice instead. I purchased the demon contract "Conquest" from a normal demon and I was wondering if the contract lasts 7 Minecraft days or 7 real life days. I've tried sleeping for 7 days straight in Minecraft but the pact hasn't gone away. I also tried purchasing another contract but the pact effect is still there and I am now down to a max of 2 hearts. I am not playing on the latest version because I am playing on a server with the mod pack Medieval Minecraft. This server was created before the new releases of this mod were released. I do not have access to restarting the server. I also have built so much on this server so I can't bear to start all over. Please advise. I am very distressed.

**Comment by MoriyaShiine** [comment]
It lasts 7 game days based on ticks elapsed. Sleeping will not make it go faster

**Comment by cnclt** [comment]
Hello! Sorry for bothering you but I just wanted to let you know it was miraculously fixed when I was killed by "claimed by the reaper". Regardless thank you for your quick response and helpfulness. I appreciate it. You made a great mod!
