### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by ryleu** [MoriyaShiine/bewitchment#305]
### Mod version

N/A

### A description of the issue

Without a license file, your code is not usable as an open-source project. If this is intended, why is your source visible? If this is not intended, may I recommend GPL, AGPL, or a CCA license?

**Comment by MoriyaShiine** [comment]
Bewitchment is All Rights Reserved but visible source; I want people to be able to see my code for if bugs need to be fixed on either my end (they can report it) or their end (they can see my code and how to adapt theirs)
