### ISSUE TITLE
Blocks ID error on server

### ISSUE THREAD

**Issue by Touch-Night** [MoriyaShiine/bewitchment#308]
### Mod version

bewitchment-1.19-3

### A description of the issue

When used this mod in server, some block is completly wrong on client side. You can see "Witch Altar Tree", "elder leaves door" and so on.
This issue only affect client. You can still open a dragon blood chest that looks like Altar.
This issue happens once bewitchment is installed, it's not a mod interaction issue.
![image](https://user-images.githubusercontent.com/102669562/179679501-efe2f18e-c143-4c5e-9e35-593ca2fca35c.png)
If load a world previously installed create 1.18, bewitchment will bring some chunks issues, making them unable to load.
![image](https://user-images.githubusercontent.com/102669562/179679856-b8cc98eb-d0f2-4511-bcc8-e0c79f1a3142.png)
![image](https://user-images.githubusercontent.com/102669562/179680012-919351e3-76b4-42c9-a43b-f7d0d3ab91f0.png)
[14:22:55] [MAIN/WARN]: Ignoring unknown attribute 'porting_lib:entity_gravity'

**Comment by MoriyaShiine** [comment]
Try deleting the .fabric folder on your sever. This is not bewitchment related and nothing can be done with the mod to fix it (caused by the fabric loader?) but that might fix it

**Comment by Touch-Night** [comment]
No, this issue happens even on a new world.

**Comment by Touch-Night** [comment]
plus I'm using quilt loader

**Comment by Touch-Night** [comment]
Adding Polymer can fix this issue
