### ISSUE TITLE
Pehkui weirdness with Werewolf

### ISSUE THREAD

**Issue by DungeonTurtle** [MoriyaShiine/bewitchment#31]
I set my scale to 2 times, and when I turned into a werewolf I got bigger I think as intended (As in 1.5 times height) but when I turned back my scale didn't go back to 2 times and stayed at 3 times scale, repeating it it allowed me to go even bigger and stay that way.

**Comment by GamyGamer** [comment]
I think this issue hasn't been fixed, right now I am using "bewitchment-1.16.5-4.jar" and this bug is still in game. I also tested this on new world and still same

**Comment by MoriyaShiine** [comment]
bruh I tested this extensively sadge
