### ISSUE TITLE
Immediate Crash On Launch

### ISSUE THREAD

**Issue by Ludicro** [MoriyaShiine/bewitchment#310]
### Mod version

1.19.1

### A description of the issue

Whenever I launch Minecraft it will immediately crash with an error code (the one I'm submitting says apoli but if I take origins out it says the same thing, just with 'bewitchment'. I also included a screenshot of the mods in my mods folder. I doubled checked to make sure they were all for Fabric and up to date so I do not believe that is the issue. 

![image](https://user-images.githubusercontent.com/65253062/181791248-f04d0341-ffee-45c8-8281-f2f491d560b5.png)

### Log or crash report

[<script src="https://gist.github.com/Ludicro/c1cf3bc78f8da45ddf9719de001826bc.js"></script>](https://gist.github.com/Ludicro/c1cf3bc78f8da45ddf9719de001826bc)

**Comment by MoriyaShiine** [comment]
Bewitchment isn't for 1.19.1 yet

**Comment by Ludicro** [comment]
Apologies, I didn't mean to put in the ".1." I just went and redownloaded all of them (and making sure I got 1.19 for all of them). I still get the same error.

**Comment by Ludicro** [comment]
Apparently the issue goes away if you use REI-9.1.517. REI-9.1.518 says it is 1.19 but I get the crashes when I use it.
