### ISSUE TITLE
bewitchment 1.19-4 Not compatible with 1.13.8 optifabric

### ISSUE THREAD

**Issue by Hallowedz** [MoriyaShiine/bewitchment#311]
### Mod version

bewitchment 1.19-4 

### A description of the issue

cannot load mod in 1.19 due to this issue, even though it is listed as a dependency.

**Comment by MoriyaShiine** [comment]
It's not a dependency, it's marked as incompatible. Look at individual files, the relations tab doesn't discern what tag each project has
