### ISSUE TITLE
Friend is getting this error when trying to join my aternos fabric server

### ISSUE THREAD

**Issue by Scarwolf124** [MoriyaShiine/bewitchment#312]
### Mod version

Recent 

### A description of the issue

They've been trying to join for awhile now, we thought they got it fixed till they got this error. Their character loads in game but it immediatly gave them this
Unknownrecipeserializer
bewitchment.ritual_recipe

**Comment by MoriyaShiine** [comment]
I need an actual version and a log file. I can't do anything without those

**Comment by Scarwolf124** [comment]
Mod version is 1.19-4 and the mc version is 1.19
Had to ask my friend for their log
[latest.log](https://github.com/MoriyaShiine/bewitchment/files/9238632/latest.log)

**Comment by MoriyaShiine** [comment]
Your friend doesn't have any mods installed; they need to install Bewitchment too

**Comment by Scarwolf124** [comment]
Thank you so much! I'll have to guide them through putting them in the correct folder then
