### ISSUE TITLE
Unable to make brew

### ISSUE THREAD

**Issue by Alfiebp11** [MoriyaShiine/bewitchment#313]
### Mod version

1.18-23

### A description of the issue

I am unable to create witches brew. Water bubbles and particles are created when mandrake root is added, but after adding potion ingredients, brew immediately turns brown and fails

**Comment by Nidoskull** [comment]
What's your altar power at? Right click it without anything in your hand to check. If it's under 150 this is not a mod issue, add more plants

**Comment by Alfiebp11** [comment]
> What's your altar power at? Right click it without anything in your hand to check. If it's under 150 this is not a mod issue, add more plants

Using a blessed stone, so have infinite power. When not using one, my altar has about 600 power

**Comment by Nidoskull** [comment]
[confused noises] What potion ingredients are you using, then? 
Please give more info, just in general- repeatedly asking is a waste of time for both ends.
The water *is* boiling, correct? (As in, you have lava, magma block, or campfire directly under the cauldron?)
I can't think of any other way potions would be screwed up if you have enough ME. The Cauldron is within 32 blocks of the altar, right??

**Comment by Alfiebp11** [comment]
The cauldron is above a magma block, and water bubbles when I put it in. The mandrake root causes the process to start, but any ingredient causes the water to simply go brown. I tried using apples at first, but have tried with a variety of ingredients from the book of shadows. The altar is 4 blocks away from the cauldron

**Comment by daylafai** [comment]
Having the same issue.
Have altar power over 800
Cauldron is working, can make elemental oils.
But can not make any other brews.
Throw in mandrage and watter bubbles.
Throw in anything after that and it goes brown/failed.
Tried differt things from the book of shadows, spider eye, bamboo, mandrake - egg - bonemeal etc but always goes brown no matter what i try.

**Comment by Comdec35000** [comment]
I'm unable to reproduce the issue on my side, the craft works for every items from the book of shadows, so I don't know what caused this to you on your side.
Maybe try to update the mod
