### ISSUE TITLE
Familiar Niffler Frozen

### ISSUE THREAD

**Issue by Alxxmeurt** [MoriyaShiine/bewitchment#316]
### Mod version

1.19-4

### A description of the issue

As stated in the Title, when the ritual is performed correctly, and a niffler spawn, they remain frozen, immune to fire, immune to gravity and non responsive of command (pet skill). After a few attempt such as piston to move it and damaging it to have it respond, i concluded it was worth pointing out as to possibly have a way to resolve the problem.
Your help would be welcome.

**Comment by MoriyaShiine** [comment]
I'm not exactly sure what a Niffler is but you should report it to whatever addon has that mob

**Comment by Alxxmeurt** [comment]
Oh im sorry, it was Bewitchment plus, my apologies for disrupting you.

**Comment by MoriyaShiine** [comment]
No worries
