### ISSUE TITLE
Not compatible with Better portals mod 

### ISSUE THREAD

**Issue by Exshotter01** [MoriyaShiine/bewitchment#318]
### Mod version

1.12.2

### A description of the issue

When better portals mod is in mod folder with bewitchment Minecraft fails to launch and dose not provide crash report or log since better portals has been discontinued wondering if something could be done on your side

**Comment by MoriyaShiine** [comment]
Bewitchment for 1.12 is also discontinued, this repository is for the 1.16+ version

**Comment by Exshotter01** [comment]
@MoriyaShiine any chance i can get any support for it, like anything i can do on my side?

**Comment by Nidoskull** [comment]
@Exshotter01 uninstall one or both 😊
