### ISSUE TITLE
Coffins don't skip to night

### ISSUE THREAD

**Issue by ryleu** [MoriyaShiine/bewitchment#319]
### Mod version

1.19-5

### A description of the issue

The title explains it all.

I am also using Haema, though it seems the issue with that mod was fixed. My pack can be found at https://github.com/ryleu/mcw-mods/releases, and it only works with PolyMC or MultiMC.

### Log or crash report

There is nothing in the log.

**Comment by Nidoskull** [comment]
I'm assuming you're playing in Multiplayer? To my knowledge all players need to sleep in a coffin for it to properly skip to night.
(Also that link leads to a 404)

**Comment by ryleu** [comment]
I fixed the link.

Just tried it with only one player and it does not work. I basically just want to know if this is a known issue before I binary search through 200+ mods.

**Comment by Nidoskull** [comment]
Looked through your pack real quick- it might be an issue between Adorn's hammocks and Bewitchment's coffins? No idea how or why this happens, but it *is* annoying.
(Did some quick testing myself in the mean time and I can almost guarantee it being Adorn's fault. None of the instances with Adorn have this issue, but all of the ones with them do.)

**Comment by ryleu** [comment]
I'll check just those two mods, along with any other mods that add sleeping things (such as Kibe) to see. Thanks for putting so much effort into this.

**Comment by Maeve811** [comment]
Any news on this issue? I also am dealing with the same problem.

**Comment by ryleu** [comment]
Update: I did check on the other two mods. They were not at fault.
