### ISSUE TITLE
[Bug] Goblet Issues

### ISSUE THREAD

**Issue by spiderking23** [MoriyaShiine/bewitchment#321]
### Mod version

Mod version 23

### A description of the issue

When drinking a Gold goblet of Blood as a Vampire, the actual Goblet was also consumed.
Alongside this, the Goblet doesn't display on an altar.

**Comment by MoriyaShiine** [comment]
Goblets aren't part of Bewitchment

**Comment by Nidoskull** [comment]
More in detail, goblets haven't been part of Bewitchment since Legacy (1.12 forge) versions, and support for 1.12 has long since ended.
It's entirely possible some addon or another re-adds them but you'll need to find the addon github, not the base mod github
(Also, mod version 23?????)

**Comment by mrsterner** [comment]
Goblets are from bw+, and they are not rendering on altars since the altar cant render BERs
