### ISSUE TITLE
Bewitchment legacy still mass spawning cambions.

### ISSUE THREAD

**Issue by Malodaster** [MoriyaShiine/bewitchment#324]
### Mod version

1.12.2

### A description of the issue

Does anyone have a fix for this? every bloodmoon nearby villiage are mobbed by several dozen cambions. cant upgrade past 1.12.2 too many good mods.

**Comment by Nidoskull** [comment]
Bewitchment Legacy is no longer officially supported. Official fix for this is 'stop playing 1.12 and upgrade to 1.16.5+'

**Comment by MoriyaShiine** [comment]
What Nidoskull said. This repository is for the 1.16+ version of Bewitchment
