### ISSUE TITLE
Book of Shadows Not Creating Entries

### ISSUE THREAD

**Issue by Akkibun** [MoriyaShiine/bewitchment#326]
### Mod version

1.18.2

### A description of the issue

So I have Bewitchment installed with a few other mods, and in one of my previous worlds it was working just fine, creating entries and giving information. But in all my current worlds the book is not creating entries regardless of how much stuff I gather/discover. Nothing I've done so far has worked. It's stalled my progress with the mod, since I cannot use anything without having to look it up, and the wiki just isn't giving me that kind of info. Anything I can do to resolve it?

**Comment by Nidoskull** [comment]
Which mods do you have installed, and which versions of said mods?
Are you sure you have the correct achievements? (I do believe the achievements that unlock book contents are mentioned on the Book of Shadows page.)
Also, when booting up a world- could we get an excerpt of the logs? It could point towards the direction of why it's having issues.
