### ISSUE TITLE
Corrupting chunk when combined with croparia greenhouse

### ISSUE THREAD

**Issue by Kasax007** [MoriyaShiine/bewitchment#331]
### Mod version

1.19-6

### A description of the issue

A bewitchment crop has been placed in a greenhouse from croparia, and now the chunk crashes the server as soon as loaded. 

### Log or crash report

https://gist.github.com/Kasax007/25d164cfd2f4bd5f9c9805d467a4988c

**Comment by MoriyaShiine** [comment]
clone of #330
