### ISSUE TITLE
Can't Remove Bewitchment

### ISSUE THREAD

**Issue by RandomNarrator** [MoriyaShiine/bewitchment#332]
### Mod version

1.12.2

### A description of the issue

When I remove the mod from my mods folder. Mc Starts, then crashes. I don't have a crash report, it doesn't generate one in the crash-reports folder.

**Comment by MoriyaShiine** [comment]
This is the repository for the 1.16+ version of the mod

Regardless, 1.12 has been unsupported for nearly 2 years. I can however suggest that you also remove dependencies l
