### ISSUE TITLE
Doggo mod incompatibility

### ISSUE THREAD

**Issue by LyonGalaxy** [MoriyaShiine/bewitchment#334]
### Mod version

1.19-6

### A description of the issue

When opening the Book of Shadows for the first time on my world, it shows "Loading Error! (Hover for info)", then, when i put my mouse on top of the words, it says 

"Error building entry bewitchment:creatures/wolf 

Error while loading entry bewitchment:creatures/wolf page 1

Unknown entity id:minecraft:wolf

Check your log for more"

I think it's an incompatibility with a wolf mod that i have, it's called Doggo mod, and when i checked in a creative world, that mod removes the minecraft wolf egg and replaces it with it's own. Removing Doggo mod allows me to see the Book of Shadows.

When i check my log just after loading the book of shadows, this is the information that shows:

### Log or crash report

https://gist.github.com/LyonGalaxy/3df0187a160b94a1fb679fad229f0e1b

**Comment by MoriyaShiine** [comment]
clone of #208
