### ISSUE TITLE
Crash When Breaking Altar

### ISSUE THREAD

**Issue by LunarOccultist** [MoriyaShiine/bewitchment#34]
When breaking the altar in a server it crashes the entire server. It was just a stone altar with a white carpet top.
[crash-2021-02-27_22.49.24-client.txt](https://github.com/MoriyaShiine/bewitchment/files/6056247/crash-2021-02-27_22.49.24-client.txt)

**Comment by LunarOccultist** [comment]
It also crashes when in creative mode.

**Comment by MoriyaShiine** [comment]
Fixed as of a commit that I forgot

**Comment by LunarOccultist** [comment]
Found out it only crashes and kicks players who are nearby the altar that breaks.
