### ISSUE TITLE
Achievements 

### ISSUE THREAD

**Issue by Piethong** [MoriyaShiine/bewitchment#340]
### Mod version

1.19-6

### A description of the issue

I've read the book a bunch of times and have been trying to progress, but I've hit a roadblock. I can not figure out what last achievement I need to do to unlock the last thing in the introduction section. I've built and done everything in the introduction, but can't seem to unlock it. I can't find a list or map anywhere that shows where the achievements are in order or at all. Would anyone be able to help me?

**Comment by MoriyaShiine** [comment]
If this is still an issue, I suggest joining the discord to see if anyone can help
