### ISSUE TITLE
Familiar died and I am still bound

### ISSUE THREAD

**Issue by farquad0318** [MoriyaShiine/bewitchment#341]
### Mod version

1.19.2

### A description of the issue

I am playing on a modded minecraft server with my friends. One of my friends, a werewolf, accidentally hit my familiar and killed it. I still have the buff to armor and poppets, but my familiar is deceased and I am unable to sever my connection with it.

**Comment by MoriyaShiine** [comment]
Unable to reproduce; if it happens again, please send a log
