### ISSUE TITLE
Hellhound Crash (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by xErrorAmelie** [MoriyaShiine/bewitchment#342]
### Mod version

1.19-6

### A description of the issue

When you go near a hellhound/spawn a hellhound the game will instantly crash.
This happend to every player in the Modpack who did some adventureing in the nether, so it's more of a crictical issue x)

### Log or crash report

Crash-report: https://mclo.gs/Zv85yYp

**Comment by xErrorAmelie** [comment]
Same thing happens with the werewolf
Crash-report: https://mclo.gs/HsgW0QG

**Comment by itsdinkd** [comment]
any chance we can get this update released to curseforge as this affects a lot of modpacks today.


@comdec_

**Comment by MoriyaShiine** [comment]
fixed as of https://github.com/MoriyaShiine/bewitchment/pull/345
