### ISSUE TITLE
Energy bar with the stats of the altar energy is not showing when i click

### ISSUE THREAD

**Issue by Firesplit** [MoriyaShiine/bewitchment#344]
### Mod version

v1.19-6

### A description of the issue

So i play on a mod pack called Medieval Mc and i started to use bewitchment mod but when i want to know how many energy my altar have , it justs don't appears .

Help please ?

**Comment by MoriyaShiine** [comment]
The magic bar on the left only appears when it changes. Send a picture of your altar, it probably isn't built correctly

**Comment by Firesplit** [comment]
Hey well it wasnt what it was the effortless fabric mod that didn't with bewitchement so it s fine now
