### ISSUE TITLE
ME Not increasing when near Altar.

### ISSUE THREAD

**Issue by LunarOccultist** [MoriyaShiine/bewitchment#35]
Not sure if this is a visual bug or the Altar just breaking.
When I first placed it, my ME was increasing but it did keep jumping around but after a while, it just stopped increasing.
![2021-02-28_10 08 57](https://user-images.githubusercontent.com/46800115/109423689-8e15dd00-79ae-11eb-9e53-19e4bc0e9eb0.png)

**Comment by MoriyaShiine** [comment]
It's filling your player magic
