### ISSUE TITLE
I can't find the right verision of this mod to work with optifabric

### ISSUE THREAD

**Issue by MugoIsBored** [MoriyaShiine/bewitchment#350]
### Mod version

1.19-6

### A description of the issue

![Screenshot 2023-03-09 141049](https://user-images.githubusercontent.com/127440440/224143841-7a4f881c-4a40-40ba-adae-129f956c6238.png)

Showing this error on the screen after trying to launch Minecraft, I believe I have the wrong version of the Bewitchment mod, but I don't know the correct version or where to download it.

**Comment by MoriyaShiine** [comment]
No version of Bewitchment works with Optifabric, the mods are incompatible. If you want shaders, you can use https://www.curseforge.com/minecraft/mc-mods/irisshaders/, it supports the Optifine format
