### ISSUE TITLE
1.19.2 Brewing splash potions 

### ISSUE THREAD

**Issue by Elite708062** [MoriyaShiine/bewitchment#352]
### Mod version

1.19.2

### A description of the issue

Hello everyone, recently a group of friends and I started a server with the mod, but when I try to create a splash potion on the witch cauldron the potion becomes bad and unusable, is there an issue or was this an intended change, if so, how can I make splash potions in the mod.

**Comment by MoriyaShiine** [comment]
You make a regular brew and put it in a brewing stand with gunpowder
