### ISSUE TITLE
Purifying Earth

### ISSUE THREAD

**Issue by Marig0ld1** [MoriyaShiine/bewitchment#353]
### Mod version

1.12.2

### A description of the issue

When Zombies and Skeletons walk on the purifying earth, they do not set on fire like the description. If I am doing it wrong, there is no proper description on how to use the blocks. (I have placed them on the ground)

**Comment by MoriyaShiine** [comment]
This repository is for the 1.16+ version of Bewitchment; 1.12 is unsupported.

You can probably ask in the discord server and see if anybody knows
