### ISSUE TITLE
CANT CONTRIBUTE : Cannot build the repository due to a failing dependency. 

### ISSUE THREAD

**Issue by samuel-davis** [MoriyaShiine/bewitchment#354]
### Mod version

N/a

### A description of the issue

Please resolve the dependency error below.  I am not sure how you are building this locally on your machine but it doesn't work on this end.  I would like to contribute but until I can actually build the thing I cant help in anyway. 

`A problem occurred configuring root project 'bewitchment'.
> Could not resolve all dependencies for configuration ':modCompileOnly'.
   > Could not find com.github.apace100:apoli:624eb4d094.
     Searched in the following locations:
       - file:/home/sam/projects/dev-personal/minecraft/bewitchment/.gradle/loom-cache/remapped_mods/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.fabricmc.net/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://libraries.minecraft.net/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://libraries.minecraft.net/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.jar
       - https://repo.maven.apache.org/maven2/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - file:/home/sam/.gradle/caches/fabric-loom/624eb4d094/apoli.jar
       - file:/home/sam/projects/dev-personal/minecraft/bewitchment/.gradle/loom-cache/624eb4d094/apoli.jar
       - https://jitpack.io/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://ladysnake.jfrog.io/artifactory/mods/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.jamieswhiteshirt.com/libs-release/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.terraformersmc.com/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.shedaniel.me/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.blamejared.com/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.ryanliptak.com/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://api.modrinth.com/maven/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
     Required by:
         project : > com.github.apace100:origins-fabric:1.7.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
`

**Comment by MoriyaShiine** [comment]
That's origins being broken on that version, but as per the readme, pull requests are not being accepted at the moment so it's not something that needs to be fixed right now

**Comment by MoriyaShiine** [comment]
However, I am curious on what you'd like to contribute; I may make an update if it is substantial enough. If so, changing what origins (or apoili) version is used may fix it locally

**Comment by Comdec35000** [comment]
The dependency is already updated and fixed on https://github.com/Comdec35000/bewitchment
