### ISSUE TITLE
Altars don't work

### ISSUE THREAD

**Issue by Bloomyex** [MoriyaShiine/bewitchment#355]
### Mod version

1.18.2

### A description of the issue

I'm not exactly sure what's wrong, but I have setup my altar with tons of different plants and the ME bar on my screen did show up at one point.

But when I try to right click the Altar to see how much ME it's getting there's nothing...
I've been trying to perform the Familiar Ritual and figure out what the issue is, but to no avail. I have no idea how to fix this myself.

**Comment by mhkdepauw** [comment]
Did you find a fix for this?

**Comment by Bloomyex** [comment]
@mhkdepauw I can't remember exactly what it was as it was a very long time ago. But I'm pretty sure it had something to do with another mod conflicting with it?
