### ISSUE TITLE
no texture bug

### ISSUE THREAD

**Issue by C4T4P1LL4** [MoriyaShiine/bewitchment#36]
![Untitled](https://user-images.githubusercontent.com/34222029/109428977-b9042f00-79b6-11eb-9f2d-3ec129f30cde.png)

idk if anyone else is having this but ive made the hedge witch n alchemists robes n it looks like this

**Comment by cybercat5555** [comment]
This is a conflict with optifine/optifabric. Remove them and it should fix this.
