### ISSUE TITLE
Discord bug

### ISSUE THREAD

**Issue by BryceMalloy** [MoriyaShiine/bewitchment#361]
### Mod version

0.0.0

### A description of the issue

I've joined the discord but I don't have access to any roles to be able to chat anywhere or make suggestions, my discord is bry#9141 if you have further questions. Also, I've been in for about 30 minutes now and nothing changed if it was reliant on time in the server.

Also sorry, I know this is for Bewitchment bugs but I don't have anywhere else to say anything.

**Comment by MoriyaShiine** [comment]
The rules channel may be worth a read :)

**Comment by BryceMalloy** [comment]
![rules](https://github.com/MoriyaShiine/bewitchment/assets/28682819/0a7480df-6b6c-4be0-aa42-701a2e2e20ac)
![roles](https://github.com/MoriyaShiine/bewitchment/assets/28682819/69776480-835e-4617-8260-02874d60acb2)
![directory](https://github.com/MoriyaShiine/bewitchment/assets/28682819/99a08012-301e-43e9-8090-e4c78e1d4f9c)

Sorry to say but the rules aren't very helpful for my situation.

**Comment by MoriyaShiine** [comment]
Dyno may be down, give it a bit and it might respond again. If it isn't working in a couple hours, I'll look into it

**Comment by BryceMalloy** [comment]
That sounds good bro, thanks for the help! In the meantime, is there a way I can ask you about a couple of things regarding controlling the spawns of the custom trees added by the mod?
