### ISSUE TITLE
Transformation bug

### ISSUE THREAD

**Issue by HiddenFlerken** [MoriyaShiine/bewitchment#362]
### Mod version

v1.18-23

### A description of the issue

For some reason I can no longer transform into a bat. I'm not sure what happened since the night before, right after I got done with the ritual, I was able to transform. My bind key is '\', I didn't change it after, I didn't really do anything. But for some reason the past few days I've been unable to transform.

For more content, I play in a multiplayer world with about ten people, I don't own the server, but I can talk to the owner if I need to. I've been really sad about not being able to become a bat because it was the main reason, I wanted to be a vampire, but since I can no longer be outside during the day my adventuring is done for and now, I'm regretting even letting my friend turn my into a vampire. I feel bad because it was such a long process for her...

**Comment by MoriyaShiine** [comment]
Was the Lilith you pledged to killed, or have you damaged any Lilith since you pledged?

**Comment by HiddenFlerken** [comment]
> Was the Lilith you pledged to killed, or have you damaged any Lilith since you pledged?

I asked the person who did the ritual and she said yes, she did die... Thank you so much for the info.

**Comment by MoriyaShiine** [comment]
No worries!
