### ISSUE TITLE
[1.19.2] harbinger boots crash

### ISSUE THREAD

**Issue by SpiceeBoy** [MoriyaShiine/bewitchment#363]
### Mod version

1.19-7

### A description of the issue

I like to use the cosmetic armor mod (https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor) and I have found in both single and multiplayer, putting the harbinger boots on your normal boots slot while wearing boots in a cosmetic slot crashes the game when anyone views your model. This includes the model view in the inventory, using F5 and normal players looking at you.

### Log or crash report

https://gist.github.com/SpiceeBoy/a0fbbc2ed1d8593c106d3547288e99ec

**Comment by MoriyaShiine** [comment]
I don't think this is Bewitchment's fault, Cosmetic Armor seems to crashing with GeckoLib (which we don't use)
