### ISSUE TITLE
All Players keep getting kick when someone who drank a polymorph potion joins

### ISSUE THREAD

**Issue by OrBlank** [MoriyaShiine/bewitchment#364]
### Mod version

bewitchment-1.19-7

### A description of the issue

Some players on my server drank a polymorph potion and whenever they try joining, it kicks all the other players out of the server. The server doesn't crash and it doesn't seem like anything important shows up in the console.

### Log or crash report

https://gist.github.com/OrBlank/24ae376c96e2b17ff3656b65131ae68c

**Comment by MoriyaShiine** [comment]
Clone of #360 

I'd report this to Impersonate if it's not already an open issue there

**Comment by OrBlank** [comment]
Alright thanks
