### ISSUE TITLE
Broom Crashes game

### ISSUE THREAD

**Issue by DCJCrazyy** [MoriyaShiine/bewitchment#365]
### Mod version

[1.19.2]

### A description of the issue

![CrashReport](https://github.com/MoriyaShiine/bewitchment/assets/67300864/d2991a59-a834-4e4f-82d4-c39a3443597a)

While on the broom if you press the forward key, it would crash your game.

### Log or crash report

https://gist.github.com/DCJCrazyy/7ec7a101878edc4c20d51cc217060618#file-crashreport

**Comment by MoriyaShiine** [comment]
Clone of #314
