### ISSUE TITLE
Altar not unlocking the Rituals chapter

### ISSUE THREAD

**Issue by Siruru1000** [MoriyaShiine/bewitchment#367]
### Mod version

bewitchment-1.19-7

### A description of the issue

I was going crazy trying to figure out why I couldn't unlock the chapters of the book of shadows when I had already done so in a previous world, until I realized that all the altars I crafted were made with mossy cobblestone instead of regular cobblestone, so I crafted one in regular cobblestone and it worked. I don't know if this is happening with the other altars as well but the mossy one definitely doesn't unlock the chapter. This happened on version 1.5.9 of  Another Quality Modpack (in case is because of some conflict)

**Comment by MoriyaShiine** [comment]
Rituals are unlocked with Chalk, not altars. It may have been a case of happening to get both chalk and a stone altar at the same time, or the modpack changing the unlock requirement.
