### ISSUE TITLE
vampirism issue

### ISSUE THREAD

**Issue by izzyw135** [MoriyaShiine/bewitchment#369]
### Mod version

1.19.2

### A description of the issue

its more of a concern really, but in 1.18.1-1.18.2 when you become a vmpire and pledge to lilth you had a better chance of not starving or your leather armor breaking, i noticed when i upgraded to 1.19.2 that this was completely different, when being a vmpire your food drastically decreases over seconds not minutes, i can transform into a bat and about 45 seconds later i am back to "human form" (minecrafts form)  but if wearing leather armor, it does not matter what kind of sunlight protection i put on, the leather instantly breaks within seconds as well.  i have looked over the config file to see if theres something i can potentially change but i am either lost or it does not exist. i would love for feedback or some insight.

**Comment by MoriyaShiine** [comment]
Does this still happen in 1.20-1?
