### ISSUE TITLE
cannot taglock other players

### ISSUE THREAD

**Issue by fioriemay** [MoriyaShiine/bewitchment#370]
### Mod version

1.19-7

### A description of the issue

hello,

i'm trying to get taglocks of other players, but whenever i right click them or their bed, nothing happens. 
however i have no issue getting a taglock of myself or any animal/mob.
what can i do to fix this issue?

thank you!

**Comment by MoriyaShiine** [comment]
Are they getting a notification in chat that you tried to taglock them? You have to be behind them for it to work. For beds, are they in a different world or offline?

**Comment by fioriemay** [comment]
@MoriyaShiine No notification at all.
I tested it out on my friend and when i right clicked her back and nothing happened -- same thing with the beds, and she was in the same world as me (online).

**Comment by MoriyaShiine** [comment]
Hmm
Can you test it on a 1.20.1 instance? 1.19 support is discontinued but if it's still a problem there then I can look into it

**Comment by fioriemay** [comment]
@MoriyaShiine unsure if this is relevant to the issue -- we are playing in the all of fabric 6 modpack

**Comment by MoriyaShiine** [comment]
Might be a mod conflict? An isolated 1.20.1 instance would still be useful, both to see if it happens with just Bewitchment installed and if it's a problem in 1.20.1 as well
