### ISSUE TITLE
Crafting in AE2 bug

### ISSUE THREAD

**Issue by dimondking2016** [MoriyaShiine/bewitchment#371]
### Mod version

1.19.2

### A description of the issue

I was playing the prominence Fabric mod pack, chilling making some Energy Cells when the recipe for energy cells suddenly made 1337Fleece. Like what even is that?
The energy cell recipe is working fine in a crafting table, I don't even have to select a recipe or anything with the polymorph mod but as soon as I use the applied crafting grid, can't make any energy cells only 1337Fleece.

Also checking the recipe for 1337 Fleece it is blank for whatever reason. confusing.

![2023-07-21_20 47 18](https://github.com/MoriyaShiine/bewitchment/assets/54517209/6008ddc1-9f8f-4c3a-8227-37c5ab1f4e47)
![2023-07-21_20 44 20](https://github.com/MoriyaShiine/bewitchment/assets/54517209/5294c3f0-a731-4eea-bc57-6d9e9053e5d6)

**Comment by dimondking2016** [comment]
Forgot to add the mod version.
bewitchment-1.19-7.jar
also to note: bewitchmentplus-1.19-11.jar

**Comment by MoriyaShiine** [comment]
Bewitchment isn't Bewitchment Plus, report to them instead

**Comment by dimondking2016** [comment]
Sorry, will do, was sent here by the prominence discord
