### ISSUE TITLE
Mobs aren't loading correctly on server

### ISSUE THREAD

**Issue by KingNanner** [MoriyaShiine/bewitchment#372]
### Mod version

1.20-3

### A description of the issue

I use Quilt

So made a server (Fabric) with mods. When I started exploring I saw some owls just fine, but after a while I found some weird mobs in the form of a Spear and Sliver Arrows just moving around. I wasn't able to interact with them at all (I could move them but couldn't attack or lead them) but they made the regular noises. My friend was able to interact with them just fine and they would attack him when attacked. 

The issue started in version 1.20-2 and we had to wait to update the server to 1.20-3 because of the provider. After updating nothing had changed. 

Everything has been working normally on singleplayer from the small amount of testing out the mod I did.

Thanks for all your hardworks on the mod and I can't wait to continue playing it!

I attached images of the glitched mobs and my client mod list (all of which are the newest version as of today).

![2023-07-21_17 24 37](https://github.com/MoriyaShiine/bewitchment/assets/140211419/8bce7d98-eed1-4958-a206-0315947d55e5)
![2023-07-21_16 51 26](https://github.com/MoriyaShiine/bewitchment/assets/140211419/66b19499-d724-4c1b-b900-283d7d2b30bb)
![2023-07-21_17 24 35](https://github.com/MoriyaShiine/bewitchment/assets/140211419/46c674d0-93e9-447f-ba45-ee451dec856c)
![Modlist](https://github.com/MoriyaShiine/bewitchment/assets/140211419/e8e074cf-f0ba-4b9d-8645-15e75aadad80)

**Comment by KingNanner** [comment]
Using fabric there is no issue, but I would rather support quilt in the future. Thanks for your patience if you've read all this.

**Comment by MoriyaShiine** [comment]
If this only happens on quilt then can you check if another mod has this issue? I don't do anything special with mob spawns so it may be a quilt bug

**Comment by KingNanner** [comment]
It's most likely a quilt bug, I'll test it with other mods and let quilt know. Thanks!
