### ISSUE TITLE
Mod Wood Signs Currently Bigged

### ISSUE THREAD

**Issue by KingNanner** [MoriyaShiine/bewitchment#373]
### Mod version

1.20-3

### A description of the issue

Hi! I discovered recently that the sign textures are bugged and have the black and pink texture on it. Along with that, whenever they are on a wall and I break them, an oak sign is dropped instead of the intended sign.

Below I'm attaching a photo of each type of sign.

(Also thank you for this mod and your hard work. I've been playing it for the past few days and its been an amazing to discover all the neat things I can do. I'm most of the way through the progression but I can't wait to find out more from the book!)

![2023-07-24_02 12 57](https://github.com/MoriyaShiine/bewitchment/assets/140211419/e563c59b-71eb-422a-a749-baa202f5a4db)
![2023-07-24_02 13 05](https://github.com/MoriyaShiine/bewitchment/assets/140211419/c8221108-5f10-4207-91e4-68071b7d50aa)
![2023-07-24_02 13 03](https://github.com/MoriyaShiine/bewitchment/assets/140211419/3102ffb5-7287-4131-8c59-89a88eacc760)
![2023-07-24_02 13 00](https://github.com/MoriyaShiine/bewitchment/assets/140211419/84c26537-8830-4dac-bf1e-ba7022a5a1c1)

Thanks again for all your hard work!

**Comment by MoriyaShiine** [comment]
Fixed as of 1.20-4. Thanks for the kind words! :D
