### ISSUE TITLE
WerePyre pledge randomly being removed

### ISSUE THREAD

**Issue by endereye21** [MoriyaShiine/bewitchment#375]
### Mod version

1.20

### A description of the issue

Randomly I will loose the pledge that lets the Werepyre transform on demand, no matter how many times I repledge I eventually loose the ability.

**Comment by MoriyaShiine** [comment]
Werepyres aren't part of Bewitchment. Mod version is also invalid, so I wouldn't know which one is bugged.

If the issue still exists with the vanilla Bewitchment pledges then feel free to open another issue
