### ISSUE TITLE
Book of Shadows not loading for other person in LAN world

### ISSUE THREAD

**Issue by OfficialDio** [MoriyaShiine/bewitchment#377]
### Mod version

Latest

### A description of the issue

When the person on my LAN world opens the BOS it shows an error message
![image_2023-09-30_082639733](https://github.com/MoriyaShiine/bewitchment/assets/102207880/8606135d-3ea5-47b1-a46f-4da8fa0e2460)
![image](https://github.com/MoriyaShiine/bewitchment/assets/102207880/bee70e81-8ab6-4125-a276-6e360dbc0545)

**Comment by MoriyaShiine** [comment]
I can't do anything without a log
