### ISSUE TITLE
Hellhounds not spawning

### ISSUE THREAD

**Issue by VVath** [MoriyaShiine/bewitchment#380]
### Mod version

1.20-6

### A description of the issue

The title says it all. Could this be a conflit with Better Nether? I've tryed looking into config files from both mods but have found nothing relatable.

**Comment by Nidoskull** [comment]
BetterNether does affect Hellhound spawning due to mob caps, but they are not unable to spawn. They're just far rarer than without BetterNether.

**Comment by MoriyaShiine** [comment]
They spawn in Nether Wastes and Crimson Forests. You can add more biomes to the `bewitchment:spawns_hellhounds` biome tag
