### ISSUE TITLE
Broken Book of Shadows

### ISSUE THREAD

**Issue by RamienB** [MoriyaShiine/bewitchment#383]
### Mod version

1.20-6

### A description of the issue

Hello there,

I play on a private server modpack (Prominence 2 Fabric) with a few friends, but after updating the modpack the Book of Shadows has broke and stopped working for everyone.
![Screenshot 2023-11-18 220901](https://github.com/MoriyaShiine/bewitchment/assets/151402704/82173bc7-c56a-4944-a5de-f5a6592418da)

I'd assume you need a l

### Log or crash report

https://gist.github.com/RamienB/e23d759afd79e433c59419ff73dfca6a

**Comment by MoriyaShiine** [comment]
I'm unable to reproduce this, so I'd suggest reporting it to Prominence as it's much more likely this is a modpack issue
