### ISSUE TITLE
Dragon’s Blood Resin not harvesting

### ISSUE THREAD

**Issue by parhelionic** [MoriyaShiine/bewitchment#384]
### Mod version

1.20-6

### A description of the issue

When an athame is used on Dragon’s Blood Wood, no resin is added to the inventory or dropped, despite the slash appearing in the wood.

**Comment by MoriyaShiine** [comment]
wait lmao

**Comment by parhelionic** [comment]
Thanks! I guess I assumed it would drop immediately like the bark, lol. Guess I’m just impatient 😅
