### ISSUE TITLE
Hanging sign texture issue with Supplementaries mod

### ISSUE THREAD

**Issue by unoMato** [MoriyaShiine/bewitchment#385]
### Mod version

1.20-6

### Mods needed to reproduce
- Patchouli [1.20.1-83-FABRIC]
- Fabric API [0.91.0+1.20.1]
- Pehkui [3.7.11+1.14.4-1.20.2]
- Bewitchment [1.20-6]
- Trinkets [3.7.1]
- Supplementaries [1.20-2.6.31]
- Moonlight [1.20-2.8.66]

### Issue
- When Supplementaries mod is enabled Bewitchment hanging sign textures don't load when placing them in world.

Without Supplementaries
![2023-11-27_01 04 10](https://github.com/MoriyaShiine/bewitchment/assets/151737416/5dc40dfb-dc1b-4985-b106-3819de4db707)

With Supplementaries
![2023-11-27_01 06 33](https://github.com/MoriyaShiine/bewitchment/assets/151737416/c5eb3bc2-8d42-4d14-9a1e-0000c79e823e)

### Log or crash report

https://gist.github.com/unoMato/b5d61023946f186b74eef72fcb72ee89

**Comment by unoMato** [comment]
https://github.com/MehVahdJukaar/Supplementaries/issues/850#issue-2011324142

**Comment by MoriyaShiine** [comment]
I've updated from Terraform API 7.0.1 to 7.0.3. If it's still an issue on next release then it's a problem between Terraform and Supplementaries
