### ISSUE TITLE
dying as a bat sets my player scale to that of a bat

### ISSUE THREAD

**Issue by voidwalkerz213** [MoriyaShiine/bewitchment#386]
### Mod version

1.20-6

### A description of the issue

basically what the title says as when i die as a bat i inconsistently sometimes become squished, another guy on the server whos a werewolf becomes taller when he dies 

![image](https://github.com/MoriyaShiine/bewitchment/assets/152505631/b226f124-6bb0-43f7-b2f4-a5a71851fe35)

**Comment by MoriyaShiine** [comment]
I'm unable to replicate this, make sure your Pehkui config doesn't keep scales on death. If this is still an issue in the new update (releasing soon), please comment
