### ISSUE TITLE
Server crashing just closing when the Poppet shelfs is plased

### ISSUE THREAD

**Issue by Thebullfighter9** [MoriyaShiine/bewitchment#388]
### Mod version

1.20.1

### A description of the issue

When the poppet shelf is place it seems to crash the server it has never done this before, I am not the server owner so i dont have the logs

**Comment by Thebullfighter9** [comment]
07.01 23:35:19 [Server] Server thread/ERROR Encountered an unexpected exception
07.01 23:35:19 [Server] INFO java.lang.NoSuchFieldError: clientInventory
07.01 23:35:19 [Server] INFO at moriyashiine.bewitchment.common.block.entity.PoppetShelfBlockEntity.<init>(PoppetShelfBlockEntity.java:32) ~[bewitchment-1.20-6.jar:?]

**Comment by Thebullfighter9** [comment]
It was put abov ethe slab first  thats when it started

**Comment by anziepanzie** [comment]
did you find a solution?
