### ISSUE TITLE
Poppet Shelf Crash

### ISSUE THREAD

**Issue by IntrovertinHell** [MoriyaShiine/bewitchment#390]
### Mod version

1.19.2

### A description of the issue

Attempting to place a poppet shelf leads to an immediate game crash, server recovers and deletes the item but it kicks everyone for a short time. I'm not the server owner so i don't have the logs but the server is ran using Shockbyte.

**Comment by MoriyaShiine** [comment]
Clone of #389. update to 1.20 or downgrade Fabric Loader to <0.15.0

**Comment by Hypatech** [comment]
> Clone of #389. update to 1.20 or downgrade Fabric Loader to <0.15.0

@MoriyaShiine Create Fabric patch c on 1.19.2 requires the loader to be >0.15.3, making this an awkward situation to manage with addons and all. Could the fix be backported?

**Comment by MoriyaShiine** [comment]
There's a patch mod in the #announcements channel in the discord for 1.17 to 1.19

**Comment by Hypatech** [comment]
Oh awesome, thanks!
