### ISSUE TITLE
Cannot remove elder brooms.

### ISSUE THREAD

**Issue by alid0505** [MoriyaShiine/bewitchment#394]
### Mod version (NOT Minecraft version)

1.20-7

### A description of the issue

I was in creative and tested out an elder broom in my house, and now I am unable to delete, remove, move, or pick it up. This is very annoying because I do not want a broomstick floating in my living room.

### Log or crash report

unsure

**Comment by MoriyaShiine** [comment]
Attack it multiple times, it has a health bar
