### ISSUE TITLE
Poppet Shelves crashing server

### ISSUE THREAD

**Issue by RaptorCross5000** [MoriyaShiine/bewitchment#395]
### Mod version (NOT Minecraft version)

1.18-23

### A description of the issue

The server completely crashes when these shelves are placed. It causes the server to crash even when not interacted with.

### Log or crash report

https://mclo.gs/iOg0C0W

**Comment by MoriyaShiine** [comment]
There are 3 possible solutions:
- Downgrade Fabric Loader to before 0.15
- Install the additional patch mod at https://discord.com/channels/388818014058840065/863866636624461824/1196967856403918889
- Update to at least 1.20-7
