### ISSUE TITLE
Update to Forge

### ISSUE THREAD

**Issue by paytonheat** [MoriyaShiine/bewitchment#396]
### Mod version (NOT Minecraft version)

n/a

### A description of the issue

Please oh pleaseeeee make a port for Forge. I've missed playing witchery, and I can't bare to switch to Fabric.

### Log or crash report

n/a

**Comment by cybercat5555** [comment]
We will not port to fabric, but if you use Sinytra Connector, Connector Extras, forge version is 47.1.3, you have the fabric trinkets and the forge versions of Pehkui and Patchouli it works fine

But we will not provide any support for any issues on it
