### ISSUE TITLE
Incompatibility with Dye Depot

### ISSUE THREAD

**Issue by Occida** [MoriyaShiine/bewitchment#397]
### Mod version (NOT Minecraft version)

1.20-8

### A description of the issue

Received this error when attempting to boot the game with both Bewitchment and Dye Depot on Minecraft 1.20.1:

```
[...]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 21
	at moriyashiine.bewitchment.common.registry.BWObjects.createAltar(BWObjects.java:409)
	at moriyashiine.bewitchment.common.registry.BWObjects.<clinit>(BWObjects.java:220)
	... 11 more
[...]
```

Dye Depot seems to add its new dye colors in a way where some other mods, such as Supplementaries, automatically implement the new colors in their dyed objects. 

### Log or crash report

https://gist.github.com/Occida/cdc82d7fb792e445c604a086c6b9b70f

**Comment by f-raZ0R** [comment]
Oh dear... seems this wasn't actually fixed, there's still another spot that doesn't like the extra dyes...
[crash-2024-10-17_09.10.03-client.txt](https://github.com/user-attachments/files/17412987/crash-2024-10-17_09.10.03-client.txt)

**Comment by f-raZ0R** [comment]
this line here
https://github.com/MoriyaShiine/bewitchment/blob/1fedcfe1c49098e3a14a11ae5b1d27995b433a3e/src/main/java/moriyashiine/bewitchment/api/BewitchmentAPI.java#L267
