### ISSUE TITLE
maze

### ISSUE THREAD

**Issue by Mazeq12** [MoriyaShiine/bewitchment#398]
### Mod version (NOT Minecraft version)

1.20-8

### A description of the issue

My game gets buggy when I cast the apath curse and ı cant ride broom or ı cant use any wand how can i solve this problem

### Log or crash report

bug

**Comment by MoriyaShiine** [comment]
That's... what the Apathy curse does

**Comment by Mazeq12** [comment]
It prevents villagers and demons from trading with you. It is required for the reach lichdom ritual.

**Comment by MoriyaShiine** [comment]
![image](https://github.com/MoriyaShiine/bewitchment/assets/45156123/15baa031-4aaf-437e-9bd7-1fe383725a33)

**Comment by Mazeq12** [comment]
I'm sorry, I don't understand because my English is bad, so what should I do to remove the curse?

**Comment by MoriyaShiine** [comment]
You can either wait 7 in-game days for it to expire like usual, or you can cast the Cleansing ritual

**Comment by Mazeq12** [comment]
Thank you very much, your mood is very nice, I have been on it for 4 hours :D

**Comment by MoriyaShiine** [comment]
Thank you! Your English is very understandable, by the way.

**Comment by Mazeq12** [comment]
ı using translate :d

**Comment by Mazeq12** [comment]
I'm bothering you again, but I waited for about 10 days and did the teeth cleaning process, but it still hasn't gone away.
