### ISSUE TITLE
Advancement tracking for book of shadows progress on LAN attached to host

### ISSUE THREAD

**Issue by Zectorian** [MoriyaShiine/bewitchment#399]
### Mod version (NOT Minecraft version)

1.19-7

### A description of the issue

For players who join a LAN, their book of shadows progress is linked to the advancements of the host not their own

### Log or crash report

N/A

**Comment by MoriyaShiine** [comment]
I would open an issue on [Patchouli's](https://github.com/VazkiiMods/Patchouli/issues) issue tracker, as the Book of Shadows uses Patchouli and there isn't much I can do to change that
