### ISSUE TITLE
Mixin inject error on launch

### ISSUE THREAD

**Issue by NoalSimon** [MoriyaShiine/bewitchment#400]
### Mod version (NOT Minecraft version)

1.20-8

### A description of the issue

Mixin inject error on use with syntra connector, have the correct dependencies and version of minecraft, unsure what is causing the error

### Log or crash report

https://gist.github.com/NoalSimon/1c19b6256f7330d6b53acd9592eff2f1

**Comment by MoriyaShiine** [comment]
Sinytra Connector is unsupported, if there's an issue then please report to them instead
