### ISSUE TITLE
[1.18.2 Fabric] Oak Poppet Shelf Crashes Server

### ISSUE THREAD

**Issue by MiniRaptor** [MoriyaShiine/bewitchment#402]
### Mod version (NOT Minecraft version)

1.18-23

### A description of the issue

This shelf crashes my server when it inside someones inventory, and it crashes when i'm trying to break already placed shelf

### Log or crash report

https://gist.github.com/MiniRaptor/a60c1adf662932cc9f860a9d85b9351e

**Comment by MoriyaShiine** [comment]
The same suggestions above still apply. The issue itself was fixed in 1.20

**Comment by MoriyaShiine** [comment]
Minecraft's codebase changes significantly across versions, coupled with the fact that I don't play old versions or want to maintain them, I only support the latest version of all of my mods (as seen by the issue template). Both alternative solutions work well enough so I have little reason to

**Comment by MoriyaShiine** [comment]
That's generally to be expected by free hosts, in specifically that case your only options are use 1.20+ or make a datapack to disable crafting poppet shelves since the mod works fine otherwise

**Comment by MoriyaShiine** [comment]
I didn't make it, I don't have the rights to it
