### ISSUE TITLE
Crash On Opening Bewitchment Book

### ISSUE THREAD

**Issue by ClockyVaudeville** [MoriyaShiine/bewitchment#403]
### Mod version (NOT Minecraft version)

1.17.10

### A description of the issue

Everything seems to be working well enough, but when I attempt to open the book my game crashes with the crash java.lang.NoSuchFieldError: book_open. I've attached the secret gist url to the post but I'm also going to attach the crash report in notepad since idk how gist actually works or if I did the crash report right. It's not giving me any forewarning like lag or something that usually foretells a crash, it just opens and then the game crashes to the launcher again. 

[crash-2024-06-20_18.11.22-server.txt](https://github.com/user-attachments/files/15920697/crash-2024-06-20_18.11.22-server.txt)

### Log or crash report

https://gist.github.com/ClockyVaudeville/3b17d2a0f030100601d0822ae8fbde78

**Comment by MoriyaShiine** [comment]
1.17 is incredibly out of date, but all I can suggest is trying different Patchouli versions
