### ISSUE TITLE
ME Bar appearing for some players, but not all.

### ISSUE THREAD

**Issue by devilslily** [MoriyaShiine/bewitchment#404]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

bewitchment-1.20.-8

### A description of the issue

I started a modded minecraft server a few days ago and it has 148 mods. Today, a few friends and I started using bewitchment and the ME bar on the left side of the screen was not appearing for some players. In my experience, when I first placed the alter, I saw the ME bar for about 10 minutes and never saw it again. I also could not see it when loading into a single player world. I had a different friend test it out and he saw it both in the server and single player. He was on the exact same modpack/versions of mods as I am. 

I have attached my most recent log report, but I don't even know what could be beneficial in it. There was nothing that stood out around the time of the ME bar going away, I was just building. My friends and I goofed off for a while before I went to try and summon a demon and realized I had no ME bar. I crashed during this log (if I remember correctly) but it was from something completely separate than bewitchment. 

### Log or crash report

https://gist.github.com/devilslily/d1d0dd3545c6a62d48b2aec11272680c

**Comment by Nidoskull** [comment]
The ME bar on the side of your screen is a personal ME bar, used for things such as brooms and certain baubles. It only appears while it is changing- if you never do anything that requires ME, you won't see it appear outside of respawning.

If you're looking for an altar's ME level, you can right-click it with an empty hand. Note that the 2x/3x/etc refers to altar recharge rate rather than altar power.

**Comment by devilslily** [comment]
oh i guess i just didnt realize the ME bar on the side was personal, i thought that was the alter
