### ISSUE TITLE
where is the death protection poppet

### ISSUE THREAD

**Issue by Warwick-cloud** [MoriyaShiine/bewitchment#412]
### Confirmations

- [X] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.20.6

### A description of the issue

With a friend, I try to become a werewolf and we have everything needed but the only thing we miss is this poppet. In the book, it's here but there is no craft to create it, it's not there and even in the creative mode, it's nowhere to be found. I'm asking for help because I don't understand why it's not existing in this version ( btw we're playing this mod in Prominence 2 version 3.0.11)
![death poppet craft](https://github.com/user-attachments/assets/67c2946c-49ba-4254-ac53-c0a2effebe6b)

### Log or crash report

i don't know what th write here sorry

**Comment by MoriyaShiine** [comment]
It does exist, Prominence probably disables it. Feel free to comment if this is still an issue with the mod by itself and I'll reopen the issue

**Comment by Warwick-cloud** [comment]
> It does exist, Prominence probably disables it. Feel free to comment if this is still an issue with the mod by itself and I'll reopen the issue

i actually made a test and in Minecraft, the poppet is here, that's too bad if prominence disables it. But thank you for helping me

**Comment by TommyDong1998** [comment]
You can still use the totem of undying instead of the poppet.

**Comment by Warwick-cloud** [comment]
Oh really ? That's cool, I will try it thank very much ^^

Le jeu. 16 janv. 2025, 10:23, Tommy Dong ***@***.***> a
écrit :
