### ISSUE TITLE
Request: Curios Support

### ISSUE THREAD

**Issue by IdrisQe** [MoriyaShiine/bewitchment#42]
Curios API for Fabric is supported by a lot more mods in 1.16 than Trinkets, and is also more customizable. It would probably be a pain for such a large mod to support two seperate accessory APIs at the same time, but it would be nice to not have to install them both when using Bewitchment with various other mods that are compatible with Curios.

Not a high priority by any means, would just be a nice-to-have thing for the future! (Honestly the ideal solution would be for Trinkets and Curios to have cross-compatible APIs somehow but I doubt that's ever going to happen)

**Comment by Aelpecyem** [comment]
There are currently no plans to use Curios for Bewitchment, especially since the Fabric version is kind of dead

**Comment by IdrisQe** [comment]
Dead? How so? It's still getting updated, and is used by or at least supported by quite a few mods. Heck it just recieved an update today.

**Comment by Aelpecyem** [comment]
...
I may be stupid

**Comment by MoriyaShiine** [comment]
Curios is getting discontinued once Trinkets 3.0 comes out, so I see no reason to support it
