### ISSUE TITLE
Conflict With Origin Addon: Extra Origins and Werewolves

### ISSUE THREAD

**Issue by Donshotz** [MoriyaShiine/bewitchment#43]
When messing around with extra origins i made myself a inchling and a werewolf and i realised that Werewolves for some reason makes a inchling smalling (i also made a new power using the size change for a bigger then normal player and with that werewolves make em infinitly bigger)

From the looks of it something about werewolf amplifies whatever size they are (ie if smaller makes em smaller if bigger makes em bigger) but doesnt go away after transforming back making it so u can go to infinite sizes well until ur game crashes that is. (had a werewolf go above the clouds lmao without flying)

**Comment by Donshotz** [comment]
![unknown](https://user-images.githubusercontent.com/79949634/109854045-7ceafb80-7c4e-11eb-9a04-0ee57474a19c.png)
![unknown1](https://user-images.githubusercontent.com/79949634/109854118-912ef880-7c4e-11eb-9e7a-245a3af3ef19.png)

Heres some screenshots of it making it infinitly bigger

**Comment by MoriyaShiine** [comment]
fixed in extra origins dev, new build will come out eventually
