### ISSUE TITLE
Chests can't be used in most recipes

### ISSUE THREAD

**Issue by IdrisQe** [MoriyaShiine/bewitchment#45]
Bewitchment chests can't be used to craft vanilla or modded items that need chests.
An example being the backback from SimpleBackpack, which accepts BetterEnd chests, despite not having explicit compatability or even the same tags on either mod's end, as far as I can tell by looking through the source.

SimpleBackpack uses a "c:chest" tag to determine what blocks are chests. Interestingly, SimpleBackpack's chest tag only checks for minecraft:chest and minecraft:trapped_chest, and I don't see SimpleBackpack integration anywhere in BetterEnd, so something BetterEnd is doing with how they implement their chests must be making them be detected as Vanilla Chests or something? I'm honestly not sure how, given my limited knowledge, but it may be worth looking into how BetterEnd does it for compatability. Granted, their chests aren't perfect, and it seems Vanilla recipes still need to be manually remade to use each chest, and notably they miss the Chest Minecart recipe... But still.

**Comment by MoriyaShiine** [comment]
nice I typed the wrong thing, this was fixed
