### ISSUE TITLE
they are annoying

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [MoriyaShiine/bewitchment#49]
cen you decrease the spawns of ghost, they are annoying pls
i have a huge glass ceiling above my base hight cordinates 256 but i see the ghost no stop spawnsning by that place in my map
but in other maps without glass shield thare are spawning normally

or cen  you add a way to disable specific spawns

**Comment by Aelpecyem** [comment]
no u 


ghost spawn rates are configurable, set their spawn weight to 0 if you don't want them to spawn

**Comment by Aelpecyem** [comment]
you can also place candelabras to ward them off

**Comment by ShadowSlayerFX1** [comment]
why did you deliberately crash the mod with optifine can you fix that

**Comment by ShadowSlayerFX1** [comment]
why are you reducing the quality of the mod because a few people are sucking at you why you care about that

**Comment by Aelpecyem** [comment]
Optifine is a closed source mod with undocumented and questionable practices. We can't fix issues regarding it especially since we're solely using API method, go report that sort of stuff to the optifine repo

**Comment by Aelpecyem** [comment]
for more information, read https://web.archive.org/web/20210131212246/https://gist.github.com/jellysquid3/e46882e37907dfbb3d03d26f589b1c6a

**Comment by ShadowSlayerFX1** [comment]
I set the ghost's spawn weight to 0 and they still spawn

**Comment by ShadowSlayerFX1** [comment]
yes

**Comment by Aelpecyem** [comment]
update to latest
