### ISSUE TITLE
Crash involving Better Nether and Mixins 

### ISSUE THREAD

**Issue by cybercat5555** [MoriyaShiine/bewitchment#52]
Seems that the recent update of BW has a messed up mixin or something. Attempting to load BW v5 with Better Nether 5.0.7 causes the game to crash upon loading, I can't even access the title screen before it crashes. Removing BW fixes this. Relevant logs

https://pastebin.com/4dD9wMGA

https://pastebin.com/QHm606ui

**Comment by cybercat5555** [comment]
Removing BN does not fix the crash but causes another 

https://pastebin.com/XjD4eBHH

**Comment by cybercat5555** [comment]
Downgrading to BW v4 solves the crash

**Comment by MoriyaShiine** [comment]
this is a besmirchment issue

**Comment by Aelpecyem** [comment]
pain
