### ISSUE TITLE
Hellhounds Don't Spawn in select Nether Biomes.

### ISSUE THREAD

**Issue by toErIpNid** [MoriyaShiine/bewitchment#53]
When having their spawn rate increased across the board (weight=50, mingroup/maxgroup=3), hellhounds still don't spawn in Nether Wastes and Crimson Forest biomes. This feels like a bug due to me scouring the nether in creative and not finding a single hellhound. Even with their spawn rate cranked up so high, I've yet to actually find one.

**Comment by toErIpNid** [comment]
Update: Can't find any in the warped forest biome either.

**Comment by MoriyaShiine** [comment]
Do you have any nether mods installed? BetterNether and BYG don't set biome categories so they become extremely rare

**Comment by toErIpNid** [comment]
Correct, BetterNether is installed, would you guys be able to make them spawn in BN biomes?

**Comment by toErIpNid** [comment]
Otherwise i'll open an issue on BN github.

**Comment by MoriyaShiine** [comment]
No, we rely on biome categories (a vanilla field) and if a biome doesn't add that, we can't do anything about it.
