### ISSUE TITLE
Scale doesn't reset after dying

### ISSUE THREAD

**Issue by GamyGamer** [MoriyaShiine/bewitchment#54]
As in title, while testing mod I have noticed that players that were killed in werewolf form don't revert scale after death and spawning as human causing to be extended vertically. I was able to change form on demand and it was day when happened.

**Comment by MoriyaShiine** [comment]
What version are you on and what other mods do you have

**Comment by GamyGamer** [comment]
Running on 1.16.5

Pehkui-1.8.0+21w08b
bewitchment-1.16.5-5
Origins-1.16.5-0.5.2 (not extra origins)
immersive-portals-0.80-mc1.16.5-fabric

And others like REI ect.

I think issue is with one config value at Pehkui, it has option keep scale on death and I have set it on true (default is false) to make it consistient with scalable portals.

**Comment by MoriyaShiine** [comment]
This is technically intended behavior, you set it to not reset after death and I have no control over that
