### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by earthyie** [MoriyaShiine/bewitchment#58]
How do I turn off the ME bar when it is not in use, some people on my server don't use bewitchment and don't want the bar on the side

**Comment by MoriyaShiine** [comment]
It goes away after like 5 seconds

**Comment by earthyie** [comment]
> It goes away after like 5 seconds

Mine hasn't been going away unless I go into creative mode

**Comment by MoriyaShiine** [comment]
Sounds like a mod conflict, try finding which mod causes it

**Comment by earthyie** [comment]
thank you for your quick replies, I forgot to add that it depends on what world I'm in, when I join a singleplayer world the bar goes away but on the server, it stays, ill go through the mods and try to see if there are any mods that are conflicting

**Comment by earthyie** [comment]
I have now tested a few single-player and multiplayer worlds and in singleplayer the bar goes away and in multiplayer the bar stays, if I find the mod that's affecting it ill let you know

**Comment by earthyie** [comment]
Im not sure if it is exactly a mod conflict as I have the exact same mods on my server as I do on my client, yet multiplayer has the bug while singleplayer doesn't contain this bug

**Comment by MoriyaShiine** [comment]
I play on a server with a bunch of other mods and it works fine

**Comment by earthyie** [comment]
That's odd then, must be a mod that changes something on a server I guess, thank you for responding so quickly

**Comment by earthyie** [comment]
Is there anyway i could disable the ME bar?

**Comment by MoriyaShiine** [comment]
No
