### ISSUE TITLE
Werewolf form bug

### ISSUE THREAD

**Issue by Wakiza1** [MoriyaShiine/bewitchment#61]
Hey guys so i have a bug with the werewolf form idk how but after the first transformation, everytime i transform after i’m in my human form but i’m just taller, sorry for my bad english tho xD and i don’t know why. Ty for reading ^^

**Comment by MoriyaShiine** [comment]
What version are you using

**Comment by Wakiza1** [comment]
I‘m using Bewitchment 1.16.5-5, Pekhui 1.9.0

**Comment by MoriyaShiine** [comment]
Does this happen in a new world? If you were a werewolf in a previous version, it may have messed up

**Comment by Wakiza1** [comment]
I tried in a single player world and the model is not messed up, and if it’s the case how can i solve this bug ?

**Comment by MoriyaShiine** [comment]
There's a scale command that Pehkui adds, you can use it reset your scale to normal

**Comment by Wakiza1** [comment]
Update : i don‘t know how but the problem seems to be repaired, the only thing now is that when i de transform the night vision is still here, and thank you for your help !
