### ISSUE TITLE
Crashing when I installed Bewitchment, not sure why. 

### ISSUE THREAD

**Issue by SilverHatTrick** [MoriyaShiine/bewitchment#63]
[crash-2021-03-14_23.18.02-client.txt](https://github.com/MoriyaShiine/bewitchment/files/6143289/crash-2021-03-14_23.18.02-client.txt)

**Comment by Aelpecyem** [comment]
can you use the binary search method leaving bewitchment to find out what mod could be causing this? Have you checked your fabric version?

**Comment by SilverHatTrick** [comment]
What exactly was the listed error, if any? Currently the Fabric version is at its latest .58

**Comment by Aelpecyem** [comment]
I'm not sure but it's probably caused by a mod interaction in a way
