### ISSUE TITLE
Elder Leaves are acting "opaque" for some reason I think?

### ISSUE THREAD

**Issue by IdrisQe** [MoriyaShiine/bewitchment#65]
I have TinyTweaks, which lets me pass through leaves like cobwebs. This works fine with all leaves, but I've noticed odd behaviour with the Elder leaves in particular- unlike other Bewitchment leaves, they appear to be marked as non-transparent, despite clearly being transparent. When I enter them, I get a full-screen overlay of their texture like when you're stuck in a non-transparent block- this doesn't occur for any other leaves. They also appear to be blocking light too, which leads me to think they're being treated as opaque. No idea why, since looking through the code they seem to be registered as, and have the same properties as, every other leaf block in the mod.

**Comment by MoriyaShiine** [comment]
This happens to all leaves, not just Elder

**Comment by IdrisQe** [comment]
Ah, so it does... I must have gotten them mixed up with another mod's Cypress leaves when I was testing the first time.

Still strange though... It seems to be rather hit and miss as to which leaves do and don't work, from various mods... I may need to report this elsewhere instead.

**Comment by MoriyaShiine** [comment]
It's an issue with Terraform's leaf block, it doesn't properly copy the block settings
