### ISSUE TITLE
keeps Crashing on the game launcher 

### ISSUE THREAD

**Issue by SleepyPrince22** [MoriyaShiine/bewitchment#66]
hey um, so I got the latest mod of bewitchment, I had to update my API file to the latest file and the Fabric launcher file too but when I did everything and try to start up the game, it just keeps crashing on the MC launcher 

so I dont what is going on with it at all :( and I really do wanna play the mod too but it just keeps crashing 

so I need help on why it keeps doing it and if im doing something wrong??

**Comment by Aelpecyem** [comment]
can I see your mod folder? The game should also still output a crash log somewhere

**Comment by SleepyPrince22** [comment]
and I dont know how to get to my log at all :(

**Comment by Aelpecyem** [comment]
ok so, I don't need your log for this
check the curseforge page and go to the dependencies tab: 
![unknown](https://user-images.githubusercontent.com/41518251/111512810-71202e80-8750-11eb-8f45-5efa908db2ee.png)

**Comment by Aelpecyem** [comment]
you'll need all of the required dependencies 

also keep in mind that this is a fabric mod, you cannot use the forge mod loader for this

**Comment by SleepyPrince22** [comment]
ah okay then thank u I install them then
