### ISSUE TITLE
Leeching potion

### ISSUE THREAD

**Issue by DumCumpster** [MoriyaShiine/bewitchment#67]
Leeching potions dont seem to be working? I can create a leeching potion and I can extend its duration but not its effectiveness, if I try to it turns brown, also despite having the effect I am not gaining health from damage im dealing.

**Comment by MoriyaShiine** [comment]
You need altar power when you add modifiers. The leeching thing is my b, I'll fix it next update

**Comment by DumCumpster** [comment]
Thank you so much for such a swift response :> Ill b looking forward to the next update 😄
