### ISSUE TITLE
Chalk one-time use in survival

### ISSUE THREAD

**Issue by Zainyest** [MoriyaShiine/bewitchment#7]
Using the most recent test build I found that chalk was one-time use without durability. (survival mode for chalk durability)

**Comment by Ayrion** [comment]
It's gone back to the old witchery way of dropping items

**Comment by Zainyest** [comment]
oh oops I was using the wrong sizes of circles, ignore that part then

**Comment by MoriyaShiine** [comment]
This has been fixed as of 2 days ago
