### ISSUE TITLE
The Specter Bangle doesnt work

### ISSUE THREAD

**Issue by Rumplel** [MoriyaShiine/bewitchment#70]
The Specter Bangle does not give the invisibility effect. You can see the particles. I tried it in Creative and Survival (with ME).

**Comment by MoriyaShiine** [comment]
It's not supposed to give invisibility, it disabled the rendering and adds smoke particles

**Comment by Rumplel** [comment]
I do not understand. Then what is the ability

**Comment by Aelpecyem** [comment]
Invisibility but like not with a potion effect

**Comment by Aelpecyem** [comment]
Press F5 to find out lol

**Comment by Rumplel** [comment]
I did it, it was still visible and the mobs saw me too
