### ISSUE TITLE
Failed Brews: What to do?

### ISSUE THREAD

**Issue by IdrisQe** [MoriyaShiine/bewitchment#71]
So, since the book told me to experiment, and according to a wiki for the older versions, I figured I should be able to add gunpowder to make a splash potion. That very much didn't work even with my 599 Altar Power so I assume that isn't an option anymore (which means curing this zombie villager I found is going to be a pain >.> Time to get a Nether Portal I guess) but on that topic- I now have a failed brew sitting in my cauldron and have no idea what to do.

Do you need to break/re-place the cauldron any time you fail a brew? Because if so that's kinda annoying. I tried a bucket, nothing happenend, bottles, nothing happened (shame, it'd be neat if failed brews gave you a sort of suspicious stew styled thing with unpredictable bad effects for a few seconds or something) I tried right clicking with an empty hand, shift-right clicking, left right and shift-right clicking with Athame, nothing removes this brew. The Book of Shadows, as far as I can tell, says nothing on the matter either.

It would be nice if there was a simpler way to dump failed brews, maybe just shift-right clicking or something, which maybe would make a noxious AOE cloud around it for a few seconds or something from fumes off the dumped wastewater.

_Also, related Mini-suggestion: Right click a brew in a pot with arrows to make tipped arrows, 3 max, as sort of an early game way to get them without needing Dragon's Breath which is just obtusely expensive and endgame for how useless most tipped arrows are_

**Comment by Aelpecyem** [comment]
1. Only the listed modifiers (Redstone, Glowstone) are valid, you want a brewing stand to enhance your potions as splash brews
2. Add wood ash, it'll instantly clear your cauldron

**Comment by Aelpecyem** [comment]
idk about that tipped arrow suggestion, since it's very different to vanilla progression
