### ISSUE TITLE
Spectre Bangle is bugged

### ISSUE THREAD

**Issue by Plagearon** [MoriyaShiine/bewitchment#72]
This bug has already been brought up but was dismissed, which I believe was down to the previous individual not describing the issue properly.

Currently, when equipping the Spectre Bangle and sneaking, the player remains completely visible. By that I mean that you can still very clearly see the player model, and so can other players. Despite this however, the smoke particles continue to render at the player's feet. This has only been the case for the most recent versions of Bewitchment (the last 3 or so), and was working as intended prior to this. Before this issue the Bangle would make the player completely invisible, along with their armour, both in F5 mode and to other players.

This issue renders the Spectre Bangle entirely useless, and currently serves only to waste ME while providing a little smoke effect.

**Comment by MoriyaShiine** [comment]
With further testing, I think it has to do with https://github.com/emilyalexandra/trinkets/issues/68 and there's not much I can do.
