### ISSUE TITLE
Server Issues & suggestions

### ISSUE THREAD

**Issue by PDabro** [MoriyaShiine/bewitchment#73]
- effects from susceptibility (slowness & sinking) disappeared for no reason, restarting server doesn't fix the issue (**server)**
- other werewolves attacks player werewolves (I don't know if it should be like that) (**client and server**)
- holding silver ingot or silver ore doing nothing to me (**client and server**)
- player werewolves or vampires can jump over salt line (it would be cool if the collisions reached the build limit & breaking salt line could kill infected player instantly than just hurt him) (**client and server**)
- sometimes player werewolves can go sleep in full moon before transformation (**server**)
- I don't know why but somehow I transformed in 2 block height area and my character bugged out by scaling to 3 block height instead to werewolf model (**server**)
- blood amount bar doesn't show at animals when being a vampire (works with villagers and players) (**client and server**)
- it would be cool how the texture of the hand would change during the transformation as well (**client and server**)

I love this mod, keep up the great work!

**Comment by MoriyaShiine** [comment]
1: you only get those effects in water or rain
2: intended, might change
3: intended, won't change
4: intended, won't change
5: intended if you sleep before your transformation (being exposed to the full moon)
6: need more details
7: intended, might change
8: intended but unwanted, unknown how to fix

**Comment by PDabro** [comment]
1: I don't have those effects in rain or water I don't know why (I'm not under the tree and its raining)
![image](https://user-images.githubusercontent.com/12714045/112493194-3dfa2280-8d82-11eb-8fd7-2fa376cc3632.png)

6: I was just walking through doors inside glass room and somehow i went into swimming animation (the door was framed by blocks of glass)
8: Good luck with that in the future

**Comment by MoriyaShiine** [comment]
1: did the curse run out? Use the curse command and see if you still have it
6: him, might have to with poses
8: thank

**Comment by PDabro** [comment]
Yeah curse run out, I didn't know that it can run out, sorry
