### ISSUE TITLE
Hellhound Config Seems to not work?

### ISSUE THREAD

**Issue by toErIpNid** [MoriyaShiine/bewitchment#74]
Yeah yeah I'm using BN with bewitchment, HOWEVER when flying through vanilla nether biomes and their spawn rate put to THIS:
  "hellhoundWeight": 500,
  "hellhoundMinGroupCount": 5,
  "hellhoundMaxGroupCount": 8,

I've only ever saw a few, like 2 or four and not that big of groups. It's honestly starting to feel like the config file doesn't actually affect hellhound spawns, as I've never seen big groups of them (or many of them in general) as to be expected with the above minimum group count. Am I doing something wrong or is this a bug?

**Comment by MoriyaShiine** [comment]
They act the same as any other config value, probably just nether jank since the nether has wildly different weights than the overworld
