### ISSUE TITLE
Events for a more useful API

### ISSUE THREAD

**Issue by williambl** [MoriyaShiine/bewitchment#78]
For integration with other mods and bewitchment add-ons, some events could be useful.

Currently, if an add-on wants to, for example, do something when an entity gains blood, the only option  is to mixin to every place where `BloodAccessor#fillBlood` is called individually (as interface default methods cannot be mixed into).

If an addon wants to run its own code when a player's transformation is set to Vampire or Werewolf, it cannot do this, as the code is run in a mixin and is therefore unmodifiable.

A set of events, easily made with the fabric-provided `EventFactory`, would make Bewitchment more extensible.

**Comment by Aelpecyem** [comment]
HAHAH @MoriyaShiine I FUCKING TOLD YOU 

ok that aside, I second this; Callbacks are a good, reliable and functional approach to affect especially mixin driven content and a handful of them should definitely be included in the API

**Comment by Aelpecyem** [comment]
ok so starting with this, it'd probably best to define some rules for what should get events and what shouldn't, user input would be greatly appreciated

**Comment by Aelpecyem** [comment]
Generally speaking we can probably reduce this to events relating to mixins, as said (tho non mixin events would be nice too sometimes but that may just be out of the scope)

**Comment by Aelpecyem** [comment]
I honestly feel like it'd be fair patching in events only by demand via PR, so the rule is simply if there's demand for it, and if it can't be reasonably done with mixin

**Comment by Aelpecyem** [comment]
(also can we please have a ReviveEvent or something since you can't get the positive return value from the death protection revival without completely copying the code in needless ways)

**Comment by williambl** [comment]
>  a ReviveEvent or something since you can't get the positive return value from the death protection revival
@Aelpecyem this bit?
![image](https://user-images.githubusercontent.com/5115825/113873207-20768100-97a4-11eb-8604-220d0dd6b81b.png)

If so, where in it?

(btw, pending merge of [FabricMC/fabric#1394](https://github.com/FabricMC/fabric/pull/1394), this code can be moved out of mixin)

**Comment by Aelpecyem** [comment]
this bit, probably at the start before the damage check so it can be cancelled
re: FabricMC/fabric#1394 looks good, but would probably not erase the need for a callback regarding this

**Comment by williambl** [comment]
> would probably not erase the need for a callback regarding this

Yeah, I know, I was just mentioning it here mostly so that I don't forget about the fact that I can move all that out of the mixin.
