### ISSUE TITLE
World Gen Glitch

### ISSUE THREAD

**Issue by Rubyz67** [MoriyaShiine/bewitchment#79]
when i downloaded this mod, new chunks didn't generate even with pregen mods and /force gen command

**Comment by MoriyaShiine** [comment]
That sounds like an issue with the pregen mods, and I have no idea what the /force gen command is since it isn't in vanilla

**Comment by Rubyz67** [comment]
its not an issue with that it works fine without bewitchment

**Comment by MoriyaShiine** [comment]
That doesn't mean bewitchment is causing it

**Comment by Rubyz67** [comment]
it does i isolated everything

**Comment by MoriyaShiine** [comment]
Again, not our fault. We do everything the way fabric tells us to, so if pregen doesn't work with those mods then that's on their end

**Comment by Rubyz67** [comment]
does bewitchment generate anything huge?

**Comment by MoriyaShiine** [comment]
The only thing it generates are ores and trees

**Comment by Rubyz67** [comment]
nothing else?

**Comment by Rubyz67** [comment]
i have haema installed and i am a vampire so do u think that haema and bewitchment don't get along?

**Comment by Aelpecyem** [comment]
There shouldn't be any issues regarding that, and there is in fact compat between these two in the works

**Comment by Aelpecyem** [comment]
Either way regarding your issue
If you want to make sure we don't close it right away, it'd be best if you include a log
