### ISSUE TITLE
Unable to breed tamed bewitchment mobs

### ISSUE THREAD

**Issue by HDYB** [MoriyaShiine/bewitchment#80]
I've been trying to breed my tamed snakes and no matter what I do they won't breed, (I'm using raw chicken), so I went into a creative world and it seems like only untamed mobs can breed, also I can't seem to be able to tame toads no matter how many fermented spider eyes I feed them, it only seems to increase their max HP
![image](https://user-images.githubusercontent.com/71931720/113129098-2f4cb900-9223-11eb-87dd-7a299d654786.png)

**Comment by codegavran** [comment]
Do you have Charm? It has a (broken) feature to prevent player damage to pets that also prevents taglocks on tamed pets.
