### ISSUE TITLE
Taglock Recycling

### ISSUE THREAD

**Issue by codegavran** [MoriyaShiine/bewitchment#81]
I think it would be nice to be able to "empty" a taglock by crafting it by itself or maybe right clicking water to "wash" it out. Also a taglock that has been used for scrying cannot be used to scry again, if that isn't intentional.

edit: aw I can't self-label, but enhancement ofc.

**Comment by MoriyaShiine** [comment]
I didn't add this because otherwise you can just keep using it to avoid the effects of the sigils that prevent their use
