### ISSUE TITLE
Ghost Spawning

### ISSUE THREAD

**Issue by codegavran** [MoriyaShiine/bewitchment#82]
Possible bug/compat issue: kibe:big_torch (magnum torch) spawn prevention effect does not prevent ghost spawns.

Related enhancement: config for candelabra radius would be nice.

**Comment by codegavran** [comment]
Update: I've had the spawn rate set to 0 as a workaround, and I mostly believe they are still spawning as well (though in greatly reduced amounts if so). I've had a repeating command block killing them in the void for roughly two weeks, and it's still finding roughly 4 a minute or so. Cooooould be ones that were loaded before but considering I'm the only player online and I'm not moving while I tally them, and the command block and general area has been chunkloaded the entire time, it feels like they're still spawning.

v1.16.5-7, in case you've possibly fixed it in the last push

**Comment by Holgath** [comment]
I am having the same problem.  They also seem to spawn on mushroom islands... a lot of them.  Not sure why that is.  Aren't they hostile?

**Comment by MoriyaShiine** [comment]
fixed in https://github.com/MoriyaShiine/bewitchment/commit/72107a73f01ec76bc62b2ef03a6644552148aeb9
