### ISSUE TITLE
Crash Upon Joining Multiplayer World

### ISSUE THREAD

**Issue by Temmie19** [MoriyaShiine/bewitchment#87]
Now this is an odd one because I have litterally 0 idea how you could manage to get the `mouseClicked` handler to not even be found by the game, but it happened. And it's making me unable to join my pack's server. I'd love to use Bewitchment, seems like a lot of fun, but it's kinda hard when you get even play the game. This error only occurs when Bewitchment is added.

Expected result:
Joining a multiplayer world

Actual result:
https://pastebin.com/AX8kmNRM

Mod list:
In the crash report

**Comment by DevArcana** [comment]
Can you confirm that this still happens without Sodium enabled?

**Comment by MoriyaShiine** [comment]
I need a crash report without Not Enough Crashes

**Comment by Temmie19** [comment]
Removed Not Enough Crashes and now it crashes immediately.

https://pastebin.com/A30xkQ25

On investigation, it would seem that this is actually due to VoxelMap and was confirmed that this issue no longer occurs when VoxelMap is removed. I was able to join servers just fine. 

Upon further inspection of VoxelMap's source code, which I used a java decompiler to find, along with the crash report leads me to believe that something Bewitchment is doing is causing VoxelMap to be unable to process the coordinates of the player for some odd reason.

```java
//Code found at location
public static int xCoord() {
    return (int)((GameVariableAccessShim.minecraft.method_1560().method_23317() < 0.0) ? (GameVariableAccessShim.minecraft.method_1560().method_23317() - 1.0) : GameVariableAccessShim.minecraft.method_1560().method_23317());
}```

**Comment by MoriyaShiine** [comment]
Does this happen in single player?

**Comment by Temmie19** [comment]
I said it crashes immediately on game startup. You don't even get close to the menu.

**Comment by MoriyaShiine** [comment]
Oh right, sorry

**Comment by MoriyaShiine** [comment]
Regardless, VoxelMap is closed source so I can't fix this
