### ISSUE TITLE
Robe and Hat textures missing

### ISSUE THREAD

**Issue by TranquilStar** [MoriyaShiine/bewitchment#89]
I just installed the mod today because it finally is on newer versions of Minecraft, I went and created a new creative world to test out the brooms and other things like the Hats and Robes. Everything was working fine till I wanted to try and put on some of the Robes and Hats.

This is what I get when I do it:

This shows up with all witch hats:

![2021-04-14_20 30 56](https://user-images.githubusercontent.com/76603402/114797196-a1afb400-9d60-11eb-8194-070838b41496.png)

this shows up with all robes and hoods:

![2021-04-14_20 32 26](https://user-images.githubusercontent.com/76603402/114797204-a83e2b80-9d60-11eb-8819-e92f149cd71a.png)

other issues found:

Unknown broom feature?:
I don't know if it is an issue or a feature, when testing the elder tree broom, after trying to dismount it teleports you back to the original location the broom was placed, all other brooms work fine.

This is all the info I have about bugs right now.

These are the mods I have:
Bewitchment-1.16.5-8
cloth-api-1.5.48
cloth-config-4.10.13-fabric
fabric-api-0.32.9+1.16
impersonate-2.1.0
optifabric-1.9.6
Optifine_1.16.5_HD_U_G7
Patchouli-1.16.4-50-FABRIC
Pehkui-2.0.0+21w14a
somnus-fabric-0.0.11-1.16.5
trinkets-2.6.7

I was currently playing with shaders and resource packs, then turned them off to see if the issue was fixed, I removed optifine and Optifabric but the issue still occurred. I really would like to play this mod so I will wait to use the Clothes and try and focus on unlocking everything in the book. If anymore issues occur I will report them back to you.

**Comment by MoriyaShiine** [comment]
This is an Optifine issue we can't fix because Optifine is closed source.

**Comment by TranquilStar** [comment]
thankyou for the information, I didn't realize optimize was the culprit
