### ISSUE TITLE
summoning 21,000 baphomets lags the game

### ISSUE THREAD

**Issue by MoriyaShiine** [MoriyaShiine/bewitchment#9]
![image](https://user-images.githubusercontent.com/45156123/105766475-68b13180-5f1f-11eb-9de2-7a284389757c.png)

update: summoning 30,000 baphomets does not seem to rectify the issue

![image](https://user-images.githubusercontent.com/45156123/105768556-289f7e00-5f22-11eb-8e5c-eb4f62254d0f.png)

**Comment by Sunconure11** [comment]
bruh

**Comment by CammiePone** [comment]
bruh

**Comment by Ayrion** [comment]
bruh

**Comment by dairydan** [comment]
bruh

**Comment by cybercat5555** [comment]
bruh

**Comment by SmallEnderman** [comment]
bruh

**Comment by Zainyest** [comment]
bruh

**Comment by IanIsTheBoss** [comment]
bruh

**Comment by Aelpecyem** [comment]
bruh

**Comment by AzureDoom** [comment]
![](https://media1.tenor.com/images/2447097fcfe7ea9da2729f6a9231f44f/tenor.gif?itemid=14458907)

**Comment by CammiePone** [comment]
> 
> 
> ![](https://camo.githubusercontent.com/174f30f13ce4285d5cccb735586e333cacae6af8b17762ed2f85e3faab496d5f/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f696d616765732f32343437303937666366653765613964613237323966366139323331663434662f74656e6f722e6769663f6974656d69643d3134343538393037)
> that amount of any mobs would lag the game haha

no no, this is a serious problem that needs to be fixed. the game can't handle 21,000 goat bois? what's even the point of playing?!

**Comment by Sunconure11** [comment]
Need to respond just to see if something is going on. Namely, webhook stuff.

**Comment by Aelpecyem** [comment]
This should not be closed. The bug still persists, devs are just too lazy to fix it.

**Comment by stormdirus2** [comment]
Why is this closed? I still experience this issue.
Plz fix, it really lags out the server. :/
