### ISSUE TITLE
Odd bug? How to fix? Cauldron water is a clock

### ISSUE THREAD

**Issue by TranquilStar** [MoriyaShiine/bewitchment#90]
I am back once again, and sorry. But I'm sure it is a bug on my end and would like help on solving it, for it is quite odd.

When I put water in the cauldron, the water is a clock, I have no other mods except the required mods for bewitchment.
I had no resource pack on at the time either, but when I turned on the resource pack, the water in the cauldron was real water this time.

Pictures:

Without resource pack:

![2021-04-15_01 53 31](https://user-images.githubusercontent.com/76603402/114821013-eb62c380-9d8d-11eb-9159-9d7c68e27ef0.png)

With resource pack:

![2021-04-15_01 53 59](https://user-images.githubusercontent.com/76603402/114821043-f87fb280-9d8d-11eb-83e6-466539edc29a.png)

resource pack used:

bettervanillabuildingV2.49

Like I said it might just be a bug on my end, so It would be appreciated if it was helped with, thank you

**Comment by MoriyaShiine** [comment]
how

**Comment by TranquilStar** [comment]
I have no clue as to how I got this bug, I don't even know how I managed it in the first place but my 2head self did.

**Comment by TranquilStar** [comment]
I mean it is funny, but I have no clues as to how it appeared

**Comment by codegavran** [comment]
Obligatory: do you have optifine?

**Comment by TranquilStar** [comment]
I no longer have optifine installed, I just have the mods needed for bewitchment to run. It might have to do with me changing resourcepacks left and right

**Comment by Aelpecyem** [comment]
can you make sure to use the version of the texture pack that matches with the mc version (v2.49 is 1.17 snapshot)
