### ISSUE TITLE
Broom not moving

### ISSUE THREAD

**Issue by DrSnijder** [MoriyaShiine/bewitchment#91]
I took a broom from creative and was flying it. It works in creative but when in survival the broom refuses to move.
Am I missing something? I placed a altar with a blessed stone besides it.

**Comment by MoriyaShiine** [comment]
You need player magic

**Comment by cybercat5555** [comment]
Also, the altar must have the blessed stone placed _on top of it_. Not beside it or placed on the altar like a modifier, literally on top of it. Also make sure the altar is formed (put a carpet on it)

**Comment by DrSnijder** [comment]
> You need player magic

How do I get player magic? I tried reading the book of shadows but I cant seem to figure it out, also how do I get altar magic?

**Comment by DrSnijder** [comment]
> Also, the altar must have the blessed stone placed _on top of it_. Not beside it or placed on the altar like a modifier, literally on top of it. Also make sure the altar is formed (put a carpet on it)

I placed it on top of the altar but the broom was still refusing to move while in survival
Any idea if this  is normal?
