### ISSUE TITLE
Black and magenta armour

### ISSUE THREAD

**Issue by Quirellex** [MoriyaShiine/bewitchment#92]
Hi! All the custom armour (Silver, Besmirched, Hedgewitch and Alchemist clothing/armour) are magenta and black.

![image](https://user-images.githubusercontent.com/82614034/114934777-a6e13180-9e3a-11eb-9674-a68320bccbe6.png)

**Comment by Ayrion** [comment]
uninstall optifine

**Comment by MoriyaShiine** [comment]
Clone of #89
