### ISSUE TITLE
Bewitchment Compatibility?

### ISSUE THREAD

**Issue by DrSnijder** [MoriyaShiine/bewitchment#93]
I was wondering if this mod is compatible with Biome Makeover because the Bewitchment toads arent spawning in the swamps I think.

**Comment by Aelpecyem** [comment]
All bewitchment mobs safe for hellhounds use biome category names, which are configurable. Biome Makeover _should_ have those implemented

**Comment by DrSnijder** [comment]
> All bewitchment mobs safe for hellhounds use biome category names, which are configurable. Biome Makeover _should_ have those implemented / it should not affect frog spawning

How do you mean use biome category names? Thank you for the awnser on the frogs :-)

**Comment by Aelpecyem** [comment]
Biomes in Minecraft are assigned overlapping categories, i.e. there's a Forest category for Birch Forests, normal Forests, Dark Forests etc. and a Swamp category for Swamps. Biome Makeover should probably not mess with these since Bewitchment uses vanilla spawn categories

**Comment by DrSnijder** [comment]
Super!
Thank you for the quick responses and information.
