### ISSUE TITLE
Werewolves

### ISSUE THREAD

**Issue by Rumplel** [MoriyaShiine/bewitchment#95]
Bug: If I turn into a werewolf with r and then turn into a human again, the night vision effect is gone. But when day comes and I am transformed back by it, I keep the effect

Enhancement: Can you do it that you can transform yourself back into a human at night if you are not standing in the moonlight, would be nice.
Also, thanks for the great mod

**Comment by MoriyaShiine** [comment]
1) already fixed
2) it's intended that you can't turn back
