### ISSUE TITLE
Can't Get Bottle Of Blood, Specter bangle doesn't work

### ISSUE THREAD

**Issue by TranquilStar** [MoriyaShiine/bewitchment#97]
I have two Issues, 1 is with the Specter Bangle, and the second is with the Bottle of Blood. The Specter Bangle is supposed to make you invisible or completely invisible but it does not, I even tested this with a friend and nothing happened, he just said I was crouching. The Bottle of Blood issue is that I can't figure out how to get it whatsoever, I tried all the old ways.

I put a bottle in my off-hand then kill a chicken with an athame, didn't work. I need this item for a ritual but am not able to get this item.

**Comment by Tobix-irl** [comment]
Well you have to kill humanoid to get blood (villager, pillager, piglin*?).  To use spectre bangle u need to have it in aglet slot from trinkets and have ME. Bewitchment have desyncbug with ME so sometimes you see you have filled bar but you cant use broom etc.

**Comment by TranquilStar** [comment]
Thanks for the blood bottle fix, but the specter bangle doesn't work at all, I tried it multiple times and the first time I made it didn't work, I tried using it then asked a friend to try and use it, nothing happened.

**Comment by MoriyaShiine** [comment]
Already fixed
