### ISSUE TITLE
Sigils not working

### ISSUE THREAD

**Issue by AlltosSoul** [MoriyaShiine/bewitchment#98]
I place try to place them on dragon blood planks with ME source nearby and they just cant be placed

**Comment by MoriyaShiine** [comment]
Active sigils can only be places in block entities made of dragon's blood like doors, pressure plates, buttons, etc

**Comment by Ayrion** [comment]
Active sigils are for useable dragons blood blocks, like chests, doors and trapdoors, or brooms I guess
